### ISSUE TITLE
RFC:  Replace IP-Law course

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/computer-science#1003]
**Problem:**
Due to ongoing global events Intellectutal Property Law course by St. Petersburg on Coursera has been discontinued. 

**Duration:**
April 08, 2022

**Background:**
Intellectual Property Law course in Digital age by St. Petersburg on Coursera has been discountinued but an equally good course has been found to replace it.

[Introduction to Intellectual Property](https://www.coursera.org/learn/introduction-intellectual-property) by UPenn which has really good [reviews](https://www.coursera.org/learn/introduction-intellectual-property/reviews)

The course matches the CS2013 standards regarding Intellectual Property i.e, to introduce philosophical foundations of intellectual property. And will also introduce to major forms of intellectual property protection in the United States - copyright, trademarks, and patents, as well as alternative forms of intellectual property protection as prescribed by CS2013.

**Proposal:**
Replace the IP-Law course [Introduction to Intellectual Property](https://www.coursera.org/learn/introduction-intellectual-property). Respective Pull Request #1004 

**Alternatives:**

An Alternative can be [Intellectual Property for Entrepreneurs](https://www.coursera.org/learn/intellectual-property-for-entrepreneurs?)

**Comment by waciumawanjohi** [comment]
Relevant page in CS2013:
https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=200

This looks like a good replacement. I'm in favor.

**Comment by aayushsinha0706** [comment]
Its high time we should replace the broken course #1032 also mentions the same. Introduction to Intellectual Property Law is the best course to replace the previous one.

**Comment by waciumawanjohi** [comment]
I agree! Thanks @aayushsinha0706 for the original work to identify this replacement and for noting that this change had not yet been merged. Always feel free to mention when an RFC's comment period has completed!

Resolved by #1004
