### ISSUE TITLE
RFC: Replace Data Structures and Algorithms (Specialization)

### ISSUE THREAD

**Issue by german-ruiz** [ossu/computer-science#1005]
Problem:
Due to ongoing global events the specialisation [Data Structures and Algorithms (Specialization)](https://www.coursera.org/specializations/data-structures-algorithms) is no longer available,

Duration:
April 24, 2022

Background:
Data Structures and Algorithms (Specialization) by SC San Diego and HSE on Coursera has been discountinued but it is possible that the [UC San Diego MicroMasters](https://www.edx.org/micromasters/ucsandiegox-algorithms-and-data-structures) may have similar content and could serve the community.

Proposal:
Replace the [Data Structures and Algorithms (Specialization)](https://www.coursera.org/specializations/data-structures-algorithms).

Alternatives:
An Alternative can be [Data Science Foundations: Data Structures and Algorithms](https://www.coursera.org/specializations/boulder-data-structures-algorithms).

**Comment by waciumawanjohi** [comment]
Good noticing that this course in extras is no longer available.

Courses in extras need not be replaced if they are no longer available. Extras does not aim for completeness, and indeed it contains significant overlap between multiple courses.

I'm going to remove the DS and Algs specialization from Coursera. If there is a compelling reason that some course(s) should be added to Extras, I encourage opening an issue to do so.

**Comment by waciumawanjohi** [comment]
Huh, perhaps Coursera is hoping no one will notice. San Diego specialization ratings look reasonable. Simplest path forward is to do nothing. I'm closing my pull request and this issue.
