### ISSUE TITLE
RFC: Replace Introduction to Numerical Analysis

### ISSUE THREAD

**Issue by german-ruiz** [ossu/computer-science#1006]
Problem:
Due to ongoing global events the specialisation [Introduction to Numerical Analysis](https://www.coursera.org/learn/intro-to-numerical-analysis) is no longer available,

Duration:
April 24, 2022

Background:
Introduction to Numerical Analysis by HSE on Coursera has been discountinued but it is possible that the [Numerical Analysis, IIT Madras](https://nptel.ac.in/courses/111106101) may have similar content and could serve the community.

Proposal:
Replace the [Introduction to Numerical Analysis](https://www.coursera.org/learn/intro-to-numerical-analysis).

Alternatives:
An Alternative can be [Numerical Analysis](https://onlinecourses.swayam2.ac.in/cec20_ma11/preview).

**Comment by waciumawanjohi** [comment]
Good noticing, we should replace this course as it is part of the main curriculum.

There is currently an alternative suggested in the curriculum, MIT's Introduction to Numerical Methods. Unless there is compelling evidence that the IIT Madras course is better than this currently recommended course, OSSU should simply promote the MIT course to our main recommendation.

**Comment by waciumawanjohi** [comment]
I've taken a look at the course suggested. I like the fact that the course includes both lectures and a free textbook. The course also includes assignments. Unfortunately, the course does not include feedback on those assignments, either with an autograder or with solution sets.

I also came across [this PhD who has put together a youtube series on Numerical Analysis](https://www.youtube.com/playlist?list=PLldiDnQu2phsUDSmP4R_b7jzY627qnnXe). It does not look like it is paired with practice problems, so not appropriate for OSSU yet.

Another interesting resource for students is [the regularly updated course website for MIT's 18.335](https://github.com/mitmath/18335). These are the materials for the in-person MIT course, so resources like lectures are blocked to outsiders. But there may be material of interest to learners.

As a result, the current alt link, which is for MIT OpenCourseWare version of 18.335, is the most appropriate replacement for the missing course.
