### ISSUE TITLE
Why not add a translation to this repository..it will facilitate learning for all people in all the world

### ISSUE THREAD

**Issue by GAbdulWahab** [ossu/computer-science#1017]

**Comment by waciumawanjohi** [comment]
Hi Ghada Abdul Wahab,
We're an open source project and we welcome contributions in any language! OSSU has [a curriculum in Chinese](https://github.com/ossu/computer-science-cn) and has inspired [a curriculum in Portuguese](https://github.com/Universidade-Livre/ciencia-da-computacao). If you would like to donate time to the global learning community by translating this guide, we would be happy to have that contribution!

**Comment by Nageshwaram** [comment]
Legislative.assembly clone clone the restfull deleaf.

**Comment by GAbdulWahab** [comment]
@waciumawanjohi  Yes, I would like to contribute to this great community by contributing to its translation into Arabic.
