### ISSUE TITLE
RFC: "Intellectual Property Law in Digital Age" link is broken

### ISSUE THREAD

**Issue by cvdat2097** [ossu/computer-science#1032]
**Problem:**
Under [Core Ethics](https://github.com/ossu/computer-science#core-ethics) section, the link of "[Intellectual Property Law in Digital Age](https://www.coursera.org/learn/intellectual-property-law-in-digital-age)" course is broken.

**Comment by waciumawanjohi** [comment]
Thanks for pointing out the problem!

Resolved by #1004
