### ISSUE TITLE
Add Blockchain for learning

### ISSUE THREAD

**Issue by Jeevan-Kiran-Lenka** [ossu/computer-science#1037]
As you know in recent weeks or months there has been a great bump for learning and working in Web3 domain or Blockchain domain. So I think it would be great if **OSSU** can provide us enthusiastic learners some free and valid resources for learning and working in Blockchain or Web3.

**Comment by waciumawanjohi** [comment]
There are a myriad of topics which might be studied as part of an undergraduate degree. I encourage contributors interested in adding Blockchain to the curriculum to look at the CS2013 and evaluate what courses would be appropriate for undergraduate elective studies. Contributors may also look to other sets of academic standards (as Blockchain applications have grown considerably in the past decade). Absent tangible recommendations for additions to the curriculum, I am closing this issue. RFCs with proposals for additions are always welcome.
