### ISSUE TITLE
Suggestion Needed for making a beautiful, updated , full stack web app for OSSU. 

### ISSUE THREAD

**Issue by gentleatif** [ossu/computer-science#1040]
Hi , friends I am a student and a full stack web developer .
Currently I am working as a freelancer , 
I came across OSSU today , and really a great help for self taught dev. , I have also planned to follow this path .
But if we make a beautiful , full of information ,updated web app  and keep maintaining it , It will be quite excellent for anyone to read and understand about OSSU mission , and can follow this path easily. 

--> I am interested in making website for OSSU and I will keep maintaining and updating it .
Here are some of my web web app made by me :- 
https://fashionbrand.herokuapp.com/     (E-commerce clothing site)
https://spreadjoy.herokuapp.com/  (Book Donate Site by opening New Tabs)
https://dreamtrip-2-0.herokuapp.com/     (Trip-advisor)
https://love-calculator-2-0.herokuapp.com/ (Love-calculator)
https://gentleatif.github.io/v3.codingblocks.com/  (Coding Blocks )
https://gentleatif.github.io/sbi/      (SBI - Landing Page)
My portfolio web site:- 
https://portfolio-37bad.web.app/ 

But , I need financial support for this , so I want to add a contribute button at the end of page , in OSSU web app. So if anyone want to support can support me , 

If you guys are agree on this , please let me know ..

**Comment by waciumawanjohi** [comment]
At the moment OSSU is powered by the contributions of time and care from our community. Time to evaluate courses, to moderate communication, to tutor other learners is all donated by individuals dedicated to bringing OSSU to life. I will keep your offer in mind if that changes (if OSSU raises funds to compensate contributors or moves to an optional financial donation system for contributions).

Thank you for reaching out!

**Comment by huchg** [comment]
您好，邮件已收到，尽快给您回复。
 
      From  Hu。
