### ISSUE TITLE
Discontinued Course - Machine Learning

### ISSUE THREAD

**Issue by t-miller** [ossu/computer-science#1044]
Another course is being deprecated per the screenshot below.
![image](https://user-images.githubusercontent.com/19845698/172464267-8fb8f60c-d6d4-4129-b536-ba657334dea8.png)

The link in the email pointing to a description leads to [this website](https://www.deeplearning.ai/program/machine-learning-specialization/).

**Comment by waciumawanjohi** [comment]
The link in the curriculum now goes to this course:
https://www.coursera.org/learn/machine-learning

This is the first of 3 new courses by Ng. There's a quick overview of the differences from Class Central: https://www.classcentral.com/report/coursera-sunsets-machine-learning/

I'm going to close this issue, as there is not an actionable change proposed.

I will point out for those who want to propose a replacement for this course, CS2013 recommends that students learn about search...
• Problem spaces (states, goals and operators), problem solving by search
• Factored representation (factoring state into variables)
• Uninformed search (breadth-first, depth-first, depth-first with iterative deepening)
• Heuristics and informed search (hill-climbing, generic best-first, A*)
• Space and time efficiency of search
• Two-player games (introduction to minimax search)
• Constraint satisfaction (backtracking and local search methods) 

...before learning about the general categories of learning (supervised, unsupervised) and general problems in learning (overfitting).

A course covering these issues well would be a strong candidate to replace Machine Learning in the core curriculum.

**Comment by waciumawanjohi** [comment]
This course looks like it may be more narrowly tailored to the introductory ML expectations of CS2013: [https://www.coursera.org/learn/practical-machine-learning](https://www.coursera.org/learn/practical-machine-learning)
