### ISSUE TITLE
RFC: No more "Audit" option on EdX courses

### ISSUE THREAD

**Issue by pedromassango** [ossu/computer-science#1064]
**Problem:**
No more "Audit" option on EdX courses. Users does not have the option to audit courses anymore on EdX, which means, users will not be able to test their knowledge during a Fee Edx course unless they pay for it.

<img width="1267" alt="Screen Shot 2022-07-20 at 1 14 29 AM" src="https://user-images.githubusercontent.com/33294549/179864025-e7a2655b-2662-4276-b415-f580daf9068d.png">

**Alternatives:**
Find another platform that provides a similar couse for free. Or just update the github repo to remove misleading information about edx courses's audit option.

**Comment by muzimuzhi** [comment]
It seems that Edx now thinks "audit track" the same as "free access".
- https://support.edx.org/hc/en-us/articles/360013426573-What-are-the-differences-between-audit-free-and-verified-paid-courses-
- https://support.edx.org/hc/en-us/articles/1500003964681-What-does-audit-mean-What-is-the-audit-track-

**Comment by waciumawanjohi** [comment]
This does not look new and I haven't received any emails or seen articles that indicate a change in edX's audit policy. The curriculum currently references this:

> **Cost**. All or nearly all course material is available for free. However, some courses may charge money for assignments/tests/projects to be graded.
Note that both [Coursera](https://www.coursera.support/s/article/209819033-Apply-for-Financial-Aid-or-a-Scholarship?language=en_US) and [edX](https://courses.edx.org/financial-assistance/) offer financial aid.

As such, I'm closing this issue. Feel free to reopen if there is additional context to share.

**Comment by waciumawanjohi** [comment]
> This is not what the OSSU github repo says about the "audit" option

Can you quote the text in the OSSU repo that you are referring to?

> Could you please clarify how can I unlock the assignments for free?

The text I quoted above notes that financial aid is available from Coursera and edX and has links to their documentation.

**Comment by pedromassango** [comment]
> Can you quote the text in the OSSU repo that you are referring to?
> 
> >

[This](https://github.com/ossu/computer-science/blob/master/FAQ.md#:~:text=Find%20the%20text,Click%20Audit.) should lead you to the related text.

**Comment by waciumawanjohi** [comment]
That snippet refers specifically to Coursera, not to edX.

There's [a section just below](https://github.com/ossu/computer-science/blob/master/FAQ.md#is-it-necessary-to-purchase-the-verified-upgrade-for-edx-courses) for edX:
> If you just want to watch the videos, it is never necessary for any edX course on our curriculum.

**Comment by pedromassango** [comment]
Hoo, didn't notice that. My bad!

**Comment by hkakutalua** [comment]
> Hoo, didn't notice that. My bad!

@pedromassango, just to add on @waciumawanjohi's comments, for some courses on OSSU (maybe the majority), the assignments are freely available on our Discord group.
