### ISSUE TITLE
RFC: Add TeachYourselfCrypto.com to Advanced Applications

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1067]
**Problem:**
Blockchain computation, Web3, and cryptocurrencies are an upcoming part of computer science but are not yet covered by the OSSU.

**Duration:**
3 months.

**Background:**
Ethereum is a decentralized computer and blockchain computation is the fastest growing frontier in the field of computer science. 

Unfortunately cryptocurrencies, blockchains, smart contracts, etc. are not covered at all in the OSSU curriculum as it exists today.

I recommend the creation of an "Advanced Application" section to Advanced CS where [TeachYourselfCrypto.com](https://teachyourselfcrypto.com/) is added. 

This is a completely free course on crypto and covers blockchain, Bitcoin, Ethereum, Smart contracts, Web3, DeFi, privacy enhancing technologies on the blockchain, and more.

I propose adding modules 1, 2, and 3 as they are relevant to computer science. Module 4 is finance related and module 5 is related to privacy (not computer science). 

This represents an addition of 39 hours of material to the OSSU, so about 7 weeks at the recommend rate of 6 hours per day.

**Proposal:**
- Addition of TeachYourselfCrypto.com to Advanced Applications

**Alternatives:**
- Alternatively, we can find a different course that covers the same topics. 

I do not believe we should go for an alternative as the proposed course is completely free, extremely comprehensive, and requires no pre-existing knowledge.

**Comment by Sergiofuenav** [comment]
I think this would make an excellent addition to the OSSU curriculum.

**Comment by waciumawanjohi** [comment]
Students have previously suggested adding blockchain courses to the curriculum (see #1037 and #539). As expressed in those issues, the topic is worthy of advanced (elective) study. We simply need to find an appropriate resource or set of resources.

This RFC proposes a learning resource: TeachYourselfCrypto.com. The RFC describes the coverage of the resource:
> covers blockchain, Bitcoin, Ethereum, Smart contracts, Web3, DeFi, privacy enhancing technologies on the blockchain, and more

Along with coverage, we must evaluate quality. Unfortunately, the RFC doesn't speak to the quality of the resource.

Some useful sources of quality are online communities dedicated to a topic (for example, blockchain subreddits), third party MOOC review aggregators (e.g. class central), and attestations from OSSUnians who have taken a course.

I will say that I have a few concerns about OSSU recommending TeachYourselfCrypto:
1. The course is not developed by an academic. [The author is a layman who writes about many topics](https://lifemathmoney.com/who-is-harsh-strongman-and-what-this-blog-is-about/) (Appearance and Personality, Strength and Diet, etc). The course is not backed by an educational institution or a learning community.
2. The actual learning resources in the modules are not created by the author, and are instead links to material developed by others.
3. I did not find any assignments in the materials.
4. I haven't found students who have taken TeachYourselfCrypto and become a promoter of the course.

**Comment by waciumawanjohi** [comment]
I will note that there are many available blockchain courses.
[ClassCentral.com lists over 150](https://www.classcentral.com/tag/blockchain?lang=english&subject=cs%2Cprogramming-and-software-development) nearly 50 of which are [from universities](https://www.classcentral.com/tag/blockchain?lang=english&subject=cs%2Cprogramming-and-software-development&university=true).

Hackr.io assembles votes for the best learning resources for [blockchain](https://hackr.io/tutorials/learn-blockchain), [bitcoin](https://hackr.io/tutorials/learn-bitcoin) and [solidity](https://hackr.io/tutorials/learn-solidity) (some overlap).

And there are plenty of Reddit discussions about which resources learners have found most valuable in learning about blockchain, for example [here](https://www.reddit.com/r/ethdev/comments/q1t6r0/the_best_courses_out_there_to_learn_and_become/), [here](https://www.reddit.com/r/ethdev/comments/jvce0f/please_recommend_me_a_good_course_on_blockchain/), and [here](https://www.reddit.com/r/CryptoCurrency/comments/97g9n0/an_extensive_list_of_blockchain_courses_resources/).

**Comment by riceeatingmachine** [comment]
I agree with the other OSSUnians that a course on blockchain and crypto is much needed.

> The course is not developed by an academic. [The author is a layman who writes about many topics](https://lifemathmoney.com/) (Appearance and Personality, Strength and Diet, etc). 

I do not believe this is a requirement for the OSSU. If we can find great courses (and free) from non-academic sources, we should not reject them simply for not being from a university.

I see that there are two authors in the about me section, one being an OSSUnian himself and the other being a software engineer from Amazon.

> has worked at Amazon (developing Alexa) as a software engineer

I would not call them laymen, however, that being said, the focus should be on education and not on credentials.

> Unfortunately, the RFC doesn't speak to the quality of the resource.
> The course is not backed by an educational institution or a learning community.

As mentioned above, it is not wise to give much weight to "institutional" resources (especially in this field, as crypto/blockchain by their very nature are non-institutional) - we must focus on course quality alone.

> I will note that there are many available blockchain courses. [ClassCentral.com lists over 150](https://www.classcentral.com/tag/blockchain?lang=english&subject=cs%2Cprogramming-and-software-development) nearly 50 of which are [from universities](https://www.classcentral.com/tag/blockchain?lang=english&subject=cs%2Cprogramming-and-software-development&university=true).

I can offer some anecdotal evidence:

There are several courses offered by universities, and I have taken some of them before I found the one I proposed.

Here are some of them:
https://www.coursera.org/specializations/blockchain-financial-services
https://www.coursera.org/learn/introduction-blockchain-technologies
https://www.coursera.org/specializations/blockchain

There were several problems with these courses.

1) Lack of depth and primarily superficial coverage
2) Extremely out of date (the crypto industry moves really fast and these courses are a few years old already and have not been updated)

> And t[here](https://www.reddit.com/r/ethdev/comments/q1t6r0/the_best_courses_out_there_to_learn_and_become/) are plenty of Reddit discussions about which resources learners have found most valuable in learning about blockchain, for example [here](https://www.reddit.com/r/ethdev/comments/jvce0f/please_recommend_me_a_good_course_on_blockchain/), [here](https://www.reddit.com/r/CryptoCurrency/comments/97g9n0/an_extensive_list_of_blockchain_courses_resources/), and here.

This includes these reddit threads themselves (one is 2 years and one is 4 years old) and the courses listed are thus older/outdated too. 

> The actual learning resources in the modules are not created by the author, and are instead links to material developed by others.

The course I propose, although it uses lots of third partly links, is frequently updated and kept current. It is not a problem that the videos are links from other places. The links themselves are the best teaching materials out there and are frequently updated to stay current. 

It is important to have high quality and up to date learning resources, not that the learning materials be developed by the authors themselves (Many of the resources in the course are from the developers - eth resources include those from eth devs, monero resources include those from monero, the same for zcash, chainlink, web3, The Graph, etc.. They just seem to be handpicked to make sense in order and provide background).

> I did not find any assignments in the materials.

Although not assignments, there are various "Practical Exercises" throughout the course.

Quoted:

Resource | Effort
-- | --
[Installing Metamask](https://www.youtube.com/watch?v=CmpKKTRnJsw)	 | 10 m
[Getting Test Ether](https://youtu.be/f_AFrBW8V0I) | 10 m
[Simple Smart Contract Example Explained](https://youtu.be/JavvPruQNeg)	 | 10 m
[How to Compile and Deploy a Smart Contract](https://youtu.be/EeKhkovqD2E) | 20 m
[The Problem With Random Number Generation in Ethereum](https://youtu.be/Soy55Up4Bqc) | 10 m

> I haven't found students who have taken TeachYourselfCrypto and become a promoter of the course.

I found several endorsements from students and people who are heavily into crypto.

[You can find hundreds here.](https://twitter.com/search?q=teachyourselfcrypto.com&src=typed_query)

I have attached some below:

![image](https://user-images.githubusercontent.com/50071043/182013956-fda23e87-5f7d-4c48-b7d2-ad48f8bf57e1.png)
![image](https://user-images.githubusercontent.com/50071043/182013974-fbc7738a-43b8-445b-82b4-22a1c54c93fd.png)
![image](https://user-images.githubusercontent.com/50071043/182013978-1c69cfcd-8536-451e-967b-23f9042cab82.png)
![image](https://user-images.githubusercontent.com/50071043/182014002-b470a4e5-600c-4297-b88e-45c374927e5d.png)
![image](https://user-images.githubusercontent.com/50071043/182014185-291313cc-fedf-4a24-b92d-58b6e97d73b8.png)

I have also found several that are from web3 founders themselves:

Founder of Radiawallet:
![image](https://user-images.githubusercontent.com/50071043/182014069-3b34bb32-a0b6-4838-95a1-01dc99c977c6.png)

Recommendation from Pillow:
![image](https://user-images.githubusercontent.com/50071043/182014099-45edd816-2e46-4f78-8ded-ced83fff70d0.png)

I also found the course listed on various crypto learning resources (https://monerica.com/#education) and endorsed by the developers of Monero (the most popular privacy based cryptocurrency) and CakeWallet. 

![image](https://user-images.githubusercontent.com/50071043/182014531-b1905106-3f28-4695-b679-6faec5dba2ff.png)

Anecdotally, from the other courses I have taken (listed above) and the problems associated with them (listed above), and considering the hundreds of reviews from the people who have taken the course (although they are from social media and not organized places like classcentral), endorsements from web3 and crypto developers themselves, and that it's entirely free of charge, the proposed resource seems to be the best one out there for our purposes.

**Comment by waciumawanjohi** [comment]
> I see that there are two authors in the "about me" section of the course, one being an OSSUnian himself and the other being a software engineer from Amazon.

Good eye. It's a bit hard to figure out who's who, there's no linkedIn page for either creator and the links to one's website are broken. But yes, the site calls out two folks creating.

> I would not call them laymen

I don't see any evidence that either author has a degree in blockchain technology, has authored an article about blockchain published in a peer reviewed publication, has a job as an engineer working in the blockchain space, or has founded a company able to hire other professionals in the blockchain space. These are some examples of experience/qualification that would make me say these are not laymen.

> one being an OSSUnian himself

I didn't see that in the description. Let me ask, @riceeatingmachine are you one of the creators or do you know the creators of the curriculum?

**Comment by riceeatingmachine** [comment]
Hah, good catch. Yes, I am one of the creators of the curriculum. I was inspired to produce it after I finished the OSSU (and made a few contributions to it!), wanted to get into the crypto space, did a bunch of courses that sucked, and so I made one that's actually good.

As unbiased as I can be, I do think it's a great fit for the curriculum and is a vastly superior course than other existing resources. 

It's fine if it is decided to include a different resource in the course though. I figured I'd share it here as the OSSU is the basis of my technical background and was the inspiration to produce our own curriculum and is also why it is free.

If it is a requirement that the course should come from a university or non-laymen, I'd recommend Blockchain and Money by MIT as it is the least out of date (but only covers Bitcoin).

**Comment by waciumawanjohi** [comment]
> I was inspired to produce it after I finished the OSSU (and made a few contributions to it!), wanted to get into the crypto space, did a bunch of courses that sucked, and so I made one that's actually good.

I've definitely been happy to have your contributions to OSSU in the past. And I'm glad that the curriculum both inspired your contributions to the education ecosystem and provided the CS background to enable that creation.

> As unbiased as I can be

This is definitely one of the concerns. It's hard to be unbiased. As a 501c3, the board members of OSSU even fill out disclosure statements to ensure that any potential conflicts of interest are stated and acknowledged.

> I figured I'd share it here as the OSSU is the basis of my technical background and was the inspiration to produce our own curriculum and is also why it is free.

I'm very happy to promote the teachyourselfcrypto as "Here is a resource created by an OSSUnian. Check it out, see what you think." For example, writing an announcement of it in the Discord and ping learners. And that could lead to students who take the course affirming that it is a better fit for the curriculum than other resources!

**Comment by riceeatingmachine** [comment]
> I'm very happy to promote the teachyourselfcrypto as "Here is a resource created by an OSSUnian. Check it out, see what you think." For example, writing an announcement of it in the Discord and ping learners. And that could lead to students who take the course affirming that it is a better fit for the curriculum than other resources!

This sounds like a great idea. Let's do this! Would you be posting it? I'll also increase the RFC duration to 3 months to collect additional data.

**Comment by waciumawanjohi** [comment]
Yes, I will post it. I will note that it is taking me time to write up a blurb. If you (@riceeatingmachine) are able to write a 1 paragraph announcement blurb here I can edit that and post in Discord. (Do not feel that's a requirement, just something that would help me speed the process along.)

**Comment by riceeatingmachine** [comment]
Allow me 2 days.

**Comment by riceeatingmachine** [comment]
The OSSU needs a course covering blockchain and cryptocurrency technologies. Decentralized consensus and trust are the newest frontiers of computer science. An OSSUian has created an in-depth course on crypto covering all of it's major developments - Bitcoin, Ethereum, Web3, DeFi and Privacy Coins. 

The course is completely free and can be found at teachyourselfcrypto.com. 

If you are interested in the subject, please take the course and let us know what you thought in the RFC. If you like the course, we will include it in the curriculum.

(Feel free to modify as necessary!)

**Comment by waciumawanjohi** [comment]
Thanks for the draft. I've modified it a bit and it's [posted in the Discord](https://discord.com/channels/744385009028431943/748916047264088158/1021261291924496425). Looking forward to student feedback!

**Comment by riceeatingmachine** [comment]
Looks good! Is it possible to modify it such that teachyourselfcrypto.com
becomes a clickable link?

**Comment by romanbird** [comment]
I don’t see it as a good fit. Quality-wise, it’s just not comparable to the other courses on the spec, and I think there’s a level of dishonesty in pretending to be a third-party to promote your own resource.

**Comment by riceeatingmachine** [comment]
Ah didn't intend on being dishonest, just didn't want to link two different
anonymous identities together, and this account has contributed to the
couse many times so I figured it would be taken more seriously than an
entirely new GitHub account.

We don't live in good times with regards to freedom of speech.

I'd be happy to have a look at any courses you think are better, and
welcome any suggestions that you might have that can improve the content of
the course.

The goal is to make the best free cryptocurrency course for everyone.

**Comment by xxylem** [comment]
I agree with @romanbird that the suggested course is not appropriate for inclusion in the curriculumn.

- The OP stands to gain financially from the inclusion of the course in the curriculum and did not declare this up front.
- The first reading in the course is from the course author's website (https://lifemathmoney.com/the-history-and-evolution-of-money/) - "The # 1 Self-Improvement Website for Men". The website seems to have a pretty strong bias and isn't of academic quality ("red pill truths", "Make over 10K/Month online"). Also, it excludes students who do not identify as men and seems to have a sexist angle. For example, see this article written by the course author: https://lifemathmoney.com/the-wine-aunts-problem/ ("The wine aunt is just like all women: she’s hypergamous. This means that she wants a man that is better than her." / "The wine aunt’s problem is that she only wants a highly successful man because she herself is financially successful, but no successful man wants her because she’s old and less fertile."). By including the course, and there being prominent links on the course to that website, we would be condoning these attitudes towards women.
- There are bold claims used to advertise the certificate for the course (https://lifemathmoney.gumroad.com/l/cert):

> "Anybody who understands the effects of endless money printing, uncontrolled inflation, and the complete loss of public trust in any central authority cannot deny the inevitability of the decentralized, trustless, tamper-proof  blockchain revolution."
> "It is highly likely that all jobs in the future will require a basic, working knowledge of crypto, similar to the way that experience with computers and the internet is a basic qualification today."
> "Moreover, crypto companies are looking for crypto-literate professionals to join their teams. Most of these companies offer pay in 6 figures, with remote- WFH options available, consistent with the crypto culture."
> "The course is very comprehensive and covers everything you need to know about crypto."

- These claims are not substantiated, and have a strong bias.
- There is a lack of material critical to cryptocurrency - environmental impact, scams, ponzi, pump & dumps, regulatory efforts, etc. - that you might expect in a course of academic quality.

If we have to have a cryptocurrency course, I can recommend the Princeton course on Coursera (https://www.coursera.org/learn/cryptocurrency). It was a pretty reasonable introduction and a fairly neutral exposition of the technology as well as some limited social context. It includes programming assignments for understanding the consensus algorithms and the data structures involved.

**Comment by riceeatingmachine** [comment]
Hello @xxylem, I would like to address your concerns.

> The OP stands to gain financially from the inclusion of the course in the curriculum and did not declare this up front.

You are right, I did not declare it up front. The course is entirely free for all learners, however, there is a paid certification option that I did not mention. This does not make the course any better or worse with respect to it's inclusion in the curriculum, as it doesn't impact the content of the course.

> The first reading in the course is from the course author's website (https://lifemathmoney.com/the-history-and-evolution-of-money/) - "The # 1 Self-Improvement Website for Men". The website seems to have a pretty strong bias and isn't of academic quality ("red pill truths", "Make over 10K/Month online"). Also, it excludes students who do not identify as men and seems to have a sexist angle. For example, see this article written by the course author: https://lifemathmoney.com/the-wine-aunts-problem/ ("The wine aunt is just like all women: she’s hypergamous. This means that she wants a man that is better than her." / "The wine aunt’s problem is that she only wants a highly successful man because she herself is financially successful, but no successful man wants her because she’s old and less fertile."). By including the course, and there being prominent links on the course to that website, we would be condoning these attitudes towards women.

This is a bit of a logical fallacy (Person said X I did not like, so anything else he says is bad). Once again, this does not impact the materials of the course we're talking about. 

If an author of any other course in the OSSU said something that some students of the OSSU disagree with, would we remove their course from the OSSU? 

Of if an author of a course that was not in the OSSU was to say something that some students of the OSSU particularly agreed with, would we include their course in the OSSU? 

If the answer to both of these questions is "no", then it shows that what we need to consider is that course in question, and not the author's personal opinions on his personal blog.

> There is a lack of material critical to cryptocurrency - environmental impact, scams, ponzi, pump & dumps, regulatory efforts, etc. - that you might expect in a course of academic quality.

This is not strictly true. Many of the resources talk about those subjects, some explicitly so. For example, the course links [here](https://news.bitcoin.com/bitcoin-energy-consumption-is-far-more-efficient-and-greener-than-todays-banking-system/) which talks about electric consumption and compares it with that of the banking system.

However, they are not deeply covered for the simple reason that they are political topics and not particularly related to cryptocurrency technology.

(It is for the same reason the OSSU doesn't talk about how computers are used for war, and/or why computers should be regulated for whatever reason.) 

> If we have to have a cryptocurrency course, I can recommend the Princeton course on Coursera (https://www.coursera.org/learn/cryptocurrency). It was a pretty reasonable introduction and a fairly neutral exposition of the technology as well as some limited social context. It includes programming assignments for understanding the consensus algorithms and the data structures involved.

Thank you for recommending an alternative resource that can be used to improve the OSSU. 

This particular course, however, is really old (made in 2016) and has not been updated. It uses the word "bitcoins" which gives you an idea of its age, and spends a week discussing dead concepts like "Bitcoin as smart property" ([many Colored Coins wallet shut down in 2018-19](https://www.coindesk.com/markets/2018/03/29/colored-coins-startup-coinprism-is-shutting-down/)) and "secure multi-party lotteries in bitcoin" - all of these companies have moved on to Ethereum or are building a layer 2 solution like [STX](https://www.stacks.co/).

It only covers the concepts superficially and lacks depth and also all the recent developments in bitcoin.

To top it off, it does not teach anything about Ethereum and web3 (as those concepts are not around/popular when Princeton made the course.)

With regards to this, I do not recommend the inclusion of the Princeton course to the OSSU. It is incomplete and _extremely_ dated.

**Comment by xxylem** [comment]
> This is a bit of a logical fallacy (Person said X I did not like, so anything else he says is bad). Once again, this does not impact the materials of the course we're talking about.

It is not a logical fallacy. The association is quite clear. The curriculum recommends the course. The course links as required material to the Life Math Money website. That website is very biased. It is not unreasonable that a student would follow those steps and end up at that website, and from there explore other articles on the website. It is not a question of what I do not like, more a question of not excluding a segment of students needlessly, in a field with a gender diversity problem (https://www.computerscience.org/resources/women-in-computer-science/).

It is really not hard to find problematic content on that website. Here is another example: https://lifemathmoney.com/buy-1-bitcoin-while-you-still-can/. It provides inappropriate financial advice to invest in a highly volatile, speculative asset, alongside transphobia ("If not, they’ll ask, “Daddy, why didn’t you buy a whole coin? Why do we have to eat grasshoppers and go to transgender public school?”")

> This is not strictly true. Many of the resources talk about those subjects, some explicitly so. For example, the course links [here](https://news.bitcoin.com/bitcoin-energy-consumption-is-far-more-efficient-and-greener-than-todays-banking-system/) which talks about electric consumption and compares it with that of the banking system.

Bitcoin.com is by no means an appropriate source for exploring criticism of cryptocurrency.

> This particular course, however, is really old (made in 2016) and has not been updated. It uses the word "bitcoins" which gives you an idea of its age, and spends a week discussing dead concepts like "Bitcoin as smart property" ([many Colored Coins wallet shut down in 2018-19](https://www.coindesk.com/markets/2018/03/29/colored-coins-startup-coinprism-is-shutting-down/)) and "secure multi-party lotteries in bitcoin" - all of these companies have moved on to Ethereum or are building a layer 2 solution like [STX](https://www.stacks.co/).

As an introduction to cryptocurrency, it suits perfectly fine. It exposes the underlying technology. An interested student is of course free to explore topics in more depth should they find something of interest.

**Comment by xxylem** [comment]
> Why is Bitcoin.com not an "appropriate source"?

Bitcoin.com has a strong commercial interest in the success of Bitcoin and other cryptocurrencies. This naturally makes it challenging to use a source when exploring criticisms of cryptocurrency.

> It does not cover "cryptocurrencies" as concepts like smart contracts, Ethereum, oracles, web3, etc. are not covered in any detail.

Again, for an introduction, none of that is necessary. You have a commercial bias towards recommending your course and de-recommending any courses you feel compete with yours. The Princeton course is perfectly fine as an introduciton to cryptocurrency.

**Comment by riceeatingmachine** [comment]
> Again, for an introduction, none of that is necessary. You have a commercial bias towards recommending your course and de-recommending any courses you feel compete with yours. The Princeton course is perfectly fine as an introduction to cryptocurrency.

The course took 2 people about 1000 hours to make and the content is available for free. The certificates are entirely optional and cost $20 each. Other resources in the OSSU also offer certificates. It is clearly not the most profitable use of time as more money could have been made on more remunerative projects.

I'm happy to see any other courses that might be better suited for the OSSU, however, the princeton course is not a good recommendation for the reasons mentioned. 

The Princeton course is not even a proper introduction to bitcoin in 2022 as it doesn't even cover segwit. And bitcoin is a small subset of cryptocurrency technologies.

None of the criticisms I have provided for the Princeton course so far seem personally motivated. So far I have pointed out:

- The princeton course is really old (made in 2016) and has not been updated.
- Spends a week discussing dead concepts like "Bitcoin as smart property" ([many Colored Coins wallet shut down in 2018-19](https://www.coindesk.com/markets/2018/03/29/colored-coins-startup-coinprism-is-shutting-down/)), "secure multi-party lotteries in bitcoin", "Bitcoin-Backed Altcoins", - all of these companies have moved on to Ethereum or are building a layer 2 solution like [STX](https://www.stacks.co/).
- That the programming assignments are a positive point for the princeton course as compared to the course I proposed.
- it does not teach anything about Ethereum, Oracles, and Web3 (as those concepts are not around/popular when Princeton made the course.) Although, it does spend 1 week discussing "altcoins" in general.
- That it is incomplete even with respect to Bitcoin (as it doesn't cover Segwit, and segwit transaction form the majority of Bitcoin transactions in 2022 ([About 85% of addresses are segwit addresses](https://buybitcoinworldwide.com/stats/segwit-adoption/)). 

I believe these to be legitimate criticisms of the Princeton course and not a bias towards de-recommending any course other than the one I proposed.

**Comment by bradleygrant** [comment]
Recommend for rejection as inappropriate commercialization.

**Comment by angle943** [comment]
While I can appreciate the fact that teachyourselfcrypto.com is very detailed and tremendous amounts of work have been invested into creating it, I do not think that it fits the type of courses that OSSU provides.

1. The section(?)s are a just a variety of articles found on the web and/or youtube videos. While I'm sure an extensive amount of time have been spent on curating these into a logical fashion, it nonetheless makes it very different from a traditional OSSU course, where a single (or group of) instructors curates you through the whole subject, making it more focused and academic.

2. As @waciumawanjohi already pointed out, there are no typical homework problems in the traditional sense. Sure, @riceeatingmachine has pointed out that there are 'projects', but it nonetheless is a stray from the typical type of courses OSSU has.

3. It almost looks too detailed to be part of the OSSU curricula. I am not a crypto expert by any means, so I can be very off base here, but it looks like the course goes very in details of every nitpick details related to cryptos. At OSSU (and typical universities) in general, it is to my understanding that we generally don't do that. For example, why doesn't OSSU offer detailed courses that goes in depth into Front-End technologies, such as React, Angular, Vue? Why not go deeper than that, such as looking at libraries in frameworks, such as Redux (in React ecosystem) and so on? Instead OSSU (and university) courses typically give a more general education that can be applied to more niches. So maybe if we had a course on blockchains in general, for example, that might seem more appropriate then going more nitty gritty details into things (again I might be really off base here due to my lack of knowledge. Apologies in advance if I am)

4. Crypto space is a highly controversial space, and so we should be extra careful into what type of curriculum we are introducing. We can already see in the discord announcements that many are not happy with this announcement. I understand that crypto is in general a very rapidly-evolving space, and that many university courses that are available may be outdated now (as @riceeatingmachine has pointed out about the Princeton course). But due to the controversial nature of this area, I would strongly advise we take a hard stance on ONLY using university courses to teach this space, instead of from a non-accredited source. If there are currently no good viable alternatives, then we just wait. After all, the purpose of OSSU isn't to be in the forefront of everything, but rather to give you a good solid base in computer science.

**Comment by aayushsinha0706** [comment]
The resource teachyourselfcrypto is way too un-academic in my concern and it just links articles and random YouTube videos together. The very first resource mentioned is very questionable. 

There are better resources out there although I am not advocating addition of blockchain and money because the field is more finance than computer science. Although if someone still wants to add Blockchain and cryptocurrency. 

Some resources I recommend are : 

MITs course on
**[BLOCKCHAIN AND MONEY](https://ocw.mit.edu/courses/15-s12-blockchain-and-money-fall-2018/)**

Some really good resources have mentioned here by Summer of Bitcoin
> Summer of Bitcoin is a global, online summer internship program focused on introducing university students to bitcoin open-source development and design. 

[Getting started with Bitocin](https://guide.summerofbitcoin.org/the-proposal-round/getting-started-with-bitcoin)

**Comment by waciumawanjohi** [comment]
> "red pill truths"

> alongside transphobia

Thank you for pointing out these issues.

OSSU has a [Code of Conduct](https://github.com/ossu/code-of-conduct). This includes:
> No sexist, racist, homophobic, transphobic, or any other prejudiced or discriminatory language or actions

The statements highlighted above are not sufficiently separate from course content and violate the Code of Conduct. There are similar issues in content in the course. [This is the first article](https://lifemathmoney.com/the-history-and-evolution-of-money/) in the first module. The article assumes that in imagining themselves in the past, the student will imagine themselves as male. It further characterizes both sex and children as something that women give to men in exchange for protection from violence.

I'm going to close the RFC. If the course is changed so that it meets our community guidelines, users will be welcome to reopen the RFC. In the meantime, there is actionable feedback above that the authors can use.
