### ISSUE TITLE
RFC: Swap Intro CS to OpenCourseWare Version

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#1070]
**Problem:**
The edX version of Intro CS expires, while the OCW version does not.

**Duration:**
Aug 15

**Background:**
The current recommendation for Intro CS is for a course on edX. This means that after a set amount of time students' access to the course will expire. This means that students who are making their way through the course at a slow pace will be prevented from finishing. An even larger harmed group are students who did finish auditing the course who are prevented from referring back to the lectures and materials.

The same course material is available on OpenCourseWare and does not expire. This is currently listed as the alternative for Intro to CS.

**Proposal:**
Make the OCW course the recommended version of Intro to CS.

**Alternatives:**
Status Quo

**Comment by r0hitm** [comment]
I support the change.

**Comment by therealironjaw** [comment]
Is there any difference in those two courses other than prosperity with regards to MIT?

**Comment by waciumawanjohi** [comment]
I neglected to link to this issue from the Data Science curriculum that just carried out the same change: https://github.com/ossu/data-science/issues/92

**Comment by huchg** [comment]
您好，邮件已收到，尽快给您回复。
 
      From  Hu。
