### ISSUE TITLE
RFC: Replace Logic course in Advanced Math

### ISSUE THREAD

**Issue by spamegg1** [ossu/computer-science#1076]
**Problem:**
Introduction to Logic course on Coursera is broken and unmaintained.

**Duration:**
September 10, 2022 - September 24, 2022

**Background:**
The Stanford Introduction to Logic course on Coursera is broken.

Almost all of the external links of the course content and exercises
![189353676-4e3db6cc-32cb-44d1-a90b-10cf404009c0](https://user-images.githubusercontent.com/4255997/189471522-5c6fa668-2154-46a6-8489-2fff3b321aef.png)

end up dead:

![189353745-4967887e-4716-4598-be26-a1505968cfc2](https://user-images.githubusercontent.com/4255997/189471531-0574290c-7296-4224-8bd7-ae7c75d9a19e.png)

It's been like this for about a year. There were other issues with the course several years before that as well, such as broken proof tools, incorrect assignments that let you pass without submitting anything, etc. Many learners commented in Discussion forums but the issues don't get fixed.

A previous discussion / RFC about Logic courses was held on the [OSSU Math](https://github.com/ossu/math/issues/9) repository. The ForallX project was chosen as the most suitable.

Here is the relevant pull request: #1075 

**Proposal:**
Replace with the [ForallX project](https://forallx.openlogicproject.org/)

**Alternatives:**
The other two options that were also discussed in OSSU Math:
- [An Introduction to Formal Logic](https://www.logicmatters.net/ifl/) by Peter Smith
- [Logic in Action](https://logicinaction.org/)

**Comment by waciumawanjohi** [comment]
I think this is a good change for OSSU CS.

**Comment by riceeatingmachine** [comment]
I have a question: Why is logic in the syllabus? (sorry if it's an obvious question)

The basics are covered in Math for CS. I don't know why logic is related to computer science. I'm over halfway thorough the course and I haven't made the connection.

**Comment by spamegg1** [comment]
@riceeatingmachine Excluding basic logic covered in Math for CS, Logic is in the curricular guidelines:
- IS/Advanced Representation and Reasoning (Elective) 124
- IS/Natural Language Processing (Elective) 126
- IS/Advanced Machine Learning (Elective) 127
- PL/Logic Programming (Elective) 166
- SE/Formal Methods (Elective) 185

(These are electives so it's in Advanced Math.) It's used a lot in software verification, compilers, automated reasoning, AI/ML and so on.

> I'm over halfway thorough the course and I haven't made the connection.

Did you know that [all computer programs are actually mathematical proofs](https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence) ?

**Comment by spamegg1** [comment]
Closing the issue after the time period, proceeding with the Proposal.
