### ISSUE TITLE
RFC: Add Databases: Advanced Topics in SQL to curriculum.

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1077]
**Problem:**
The 3 databases courses in the curriculum are missing content related to foreign key / referential integrity constraints.

**Duration:**
1 Month.

**Background:**

Foreign key constraints are an important database topic that have not been covered in the 3 databases courses included in the course. The same teacher has another course called [Databases: Advanced Topics in SQL
](https://www.edx.org/course/advanced-topics-in-sql?index=product&queryID=70742b22d4d357721def93bb7b635c1f&position=4) that covers this topic. 

**Proposal:**
Add Databases: Advanced Topics in SQL to OSSU. This covers a few other topics as well and adds little overhead to the curriculum (only 2 weeks). 

**Alternatives:**
1. Find an alternative set of database courses.

**Comment by waciumawanjohi** [comment]
The three current database courses are in Core Applications and all learners are encouraged to take those courses. In [our curricular guidelines](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=115) Foreign Key Constraints are an elective topic, part of "Information Management: Relational Databases". From that, [Databases: Advanced Topics in SQL](https://www.edx.org/course/advanced-topics-in-sql?index=product&queryID=70742b22d4d357721def93bb7b635c1f&position=4) would most appropriately be added to an advanced section, (as all learners are encouraged to choose one or more advanced sections to focus upon). Identifying a set of courses that cover the breadth of Information Management elective topics would be helpful for students interested in learning more.

**Comment by riceeatingmachine** [comment]
In that case we could also add some courses on JSON, XML etc. There's
another database course in that series by Jeniffer Widom, but they are
outdated (10ish years old, and most things have changed).

Do we have a policy againt udemy courses? They are paid but they are
usually good and cover specific topics, so they can be used to fill holes
in the curriculum.

**Comment by waciumawanjohi** [comment]
From the curriculum:
```
Courses must:

Be open for enrollment
Run regularly (ideally in self-paced format, otherwise running multiple times per year)
Be of generally high quality in teaching materials and pedagogical principles
Match the curricular standards of the [CS 2013](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md): Curriculum Guidelines for Undergraduate Degree Programs in Computer Science
```
followed by
```
All or nearly all course material is available for free. However, some courses may charge money for assignments/tests/projects to be graded.
```

Udemy courses generally lock lectures behind a paywall. Such courses are not eligible for inclusion in the curriculum.

**Comment by AbdesamedBendjeddou** [comment]
is there any previous RFC or any discussion about the database course form [Berkely](https://cs186berkeley.net/), it seems more comprehensive, and all materials are available for free.

**Comment by waciumawanjohi** [comment]
@AbdesamedBendjeddou The course you linked looks very interesting. I did notice that all of the lecture videos are unavailable. While video lectures are not a hard requirement, in practice OSSU prefers courses with available lectures. The course does provide assignments and it looks like there are automated tests around these. Always good to see. You asked if there's been any discussion of a database course from Berkeley, I couldn't find any and the course you link is the one being taught this semester at Berkeley. (Which begs the question, are there earlier versions with both videos and assignments?)

This may be worth an RFC. I'd expect discussion on the two topics I mentioned (videos and assignments). And taking some time to demonstrate what topics in the [curricular guidelines](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=115) the course covers will be valuable to reviewers.

**Comment by waciumawanjohi** [comment]
On the current RFC, I'm going to close it as having insufficient support. As I mentioned, a proposal for an Advanced Databases section of the curriculum with 3-5 courses covering elective topics from the CS2013 would be very interesting.

**Comment by AbdesamedBendjeddou** [comment]
@waciumawanjohi if you click on resources tab you will find the previous iterations with all the video lectures and course materials available, I too didn't notice it at first.

**Comment by waciumawanjohi** [comment]
Good find! Do you feel comfortable opening an RFC suggesting a change to the databases offering? There is a template when you open an issue. General guidance is [here](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes).

**Comment by AbdesamedBendjeddou** [comment]
yes, I will open one later in the evening, God willing.
