### ISSUE TITLE
RFC: An OSSU DAO to fund paid courses

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1079]
**Problem:**
We can't add paid courses to the curriculum. 

**Duration:**
6 months (as it would be a big structural change)

**Background:**
Currently, the rule for the OSSU says the courses is that the courses need to be free of charge. Some courses in the curriculum aren't particularly great (eg. [Object-Oriented Design](https://www.coursera.org/learn/object-oriented-design) [Design Patterns](https://www.coursera.org/learn/design-patterns) [Software Architecture](https://www.coursera.org/learn/software-architecture) as they teach these topics in roundabout ways using android development tools).

Students would be better served with something like [this](https://www.udemy.com/course/uml-and-object-oriented-design-foundations/) and [this](https://www.udemy.com/course/design-patterns-in-java-concepts-hands-on-projects/) cover these topics. These courses are fairly cheap (449 Indian Rupees = 5.5 USD), shorter, and have better curriculum and teaching resources.

I understand why the OSSU decides to stick to free resources as some students might find even $5.50 to be a lot of money, but I think I have a solution to this.

**Proposal:**
1. We create a DAO like system were the OSSU has a bank account. Someone like @waciumawanjohi or anyone can manage the bank account.
2. We change all the links to Coursera, EdX, and other platforms to affiliate links to raise money for the DAO, and also accept donations from students.
3. We recommend paid courses upto $10-$20 per course in the curriculum in cases where the free courses are not up to par and the paid course is exceptionally good.
4. A student who can't afford paid courses can pay for the course once, complete it, and send us their proof of completion along with a proof they paid for the course. We then reimburse them via PayPal.

This allows us to include paid courses (where they are significantly better than the free alternative) without adding financial burden on our poorer (no offense, not sure about the right word) students.

If we decide to go ahead with this: To get the ball rolling, I will contribute $1000 to the DAO. In the future, we can decentralize it to make it a "real" DAO and if we have a lot of surplus funds, we can pay professors to make open source courses just for the OSSU.

**Alternatives:**

1. We can list both the paid and the free course.
2. We can stick to just the free courses, but this comes at the expense of quality of education.

**Comment by riceeatingmachine** [comment]
Some math:

Coursea pays 10% to 45% in commissions, and EdX pays 10%.

Assuming we have 100 sales a month at $50 on these websites, the DAO will get $500 per month from these commissions alone. Add to that student donations, and it seems like it will be financially viable to make it happen. $500 per month can fund 50 paid courses a month if we limit course price to $10 or 25 paid courses a month if we limit course price to $20 per month (encourage people to purchase udemy courses when they run sales, which is all the time).

Udemy itself has an affiliate program (15%ish commission) so we make some of the money back as well.

**Comment by romanbird** [comment]
> Some courses in the curriculum aren't particularly great

These courses seemed to be a kind of controversial add in the first place. When it was decided to get rid of the UBC ones, it seemed like there was significant support to actually just not replace them at all. If these replacements are ultimately low quality as well (Android development seems like a bit of a reach) maybe they should also be chucked

**Comment by romanbird** [comment]
In terms of complications that can arise, I think this funding idea would be a genuine nightmare to go through with

**Comment by riceeatingmachine** [comment]
> In terms of complications that can arise, I think this funding idea would be a genuine nightmare to go through with

It seems like an interesting idea to try. The best case scenario is that we have a functioning system and can improve the OSSU with a few higher quality paid courses where absolutely needed.

The worst case scenario is that we run out of money and need to shut the DAO down. We're sending traffic to Coursera/EdX anyway, so using affiliate commissions from them can be a no-cost way to try it out. 

> maybe they should also be chucked

They are still better than the UBC ones, but they aren't great by any means. They need to stay in the curriculum to cover those topics.

**Comment by riceeatingmachine** [comment]
Looks like most of the responses are a no, so I'm closing this issue.
