### ISSUE TITLE
RFC: Replacement of poor courses in the OSSU with NPTEL

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1080]
**Problem:**
There are unfortunately some courses in the OSSU that are not up to par and are only there because no better alternatives have been found.

**Duration:**
2 months

**Background:**
There are certain courses in the curriculum that aren't particularly great but have been kept due to lack of better courses. I've been scouring the internet and I found [NPTEL](https://nptel.ac.in/courses) (National Programme on Technology Enhanced Learning) which contains a lot of computer science courses from The Indian Institute of Technology - the highest tech universities in India. Think of it like OCW for the IITs.

They are generally though to be high quality courses in India, and this is the best university here. The downside is that there are not many practical assignments on NPTEL unlike their university counterparts.

**Proposal:**
1. Replace Object Oriented Design, Design Patterns, Software Architecture, and Software Engineering: Introduction with [Software Engineering](https://nptel.ac.in/courses/106101061) by IIT Kharagpur and [Software Conceptual Design](https://nptel.ac.in/courses/106101235) by IIT Bombay **(Update: Moved to #1082)**
2. I see #1078 and #926 and my conclusion is that our current Operating Systems course is too long because of the prerequisites. Maybe an alternative shorter/less rigorous version could be suggested like [Operating System Fundamentals](https://nptel.ac.in/courses/106105214) and [Real Time Operating Systems](https://nptel.ac.in/courses/106105172) by IIT Kharagpur. **(Update: Moved to #1083)**
3.  I see #1055 and my conclusion is that there is trouble finding a good single reasonable length course that covers security. NPTEL has a bunch of information security courses that can be found by searching for "security" on [this page](https://nptel.ac.in/courses) and selecting the computer science discipline. The courses cover both hardware and software security. We will probably be able to make do with [this](https://nptel.ac.in/courses/106106129). 
4. The current recommendation for Logic is a textbook. For people who prefer video lectures, we can list [Logic for CS](https://nptel.ac.in/courses/106102013) as an alternative.
5. The crypto course that I made was rejected under #1067 for not conforming to western social norms. [Blockchain and its Applications](https://nptel.ac.in/courses/106105235) by IIT Kharagpur seems like a good new course that covers a lot of ground. I also recommend adding [this](https://www.youtube.com/watch?v=Y6AvtjD7V78&list=PLEGCF-WLh2RJdrKZ431SidRX_T4VmAKx8) course before the NPTEL one to give context to some crypto mental models. It needs to come after the game theory course, and ideally we also add in [Game Theory 2](https://www.coursera.org/learn/game-theory-2) which covered auctions and voting if I remember correctly.

So the crypto section can look like:

- Game Theory 2 (optional)
- Incentives in Computer Science
- Blockchain and its Applications

6. Side-note: [This](https://www.youtube.com/watch?v=khyrgbiz20o&list=PLm3J0oaFux3aafQm568blS9blxtA_EWQv) seems like a very interesting course. Shame it's not in the OSSU. Maybe we can put it in the good courses list.

**Comment by waciumawanjohi** [comment]
I think that NPTEL does a great service by making so many courses available. I would be happy to have an RFC that identifies an NPTEL course as the best option for a given topic.

RFCs that propose multiple unrelated changes to the curriculum are difficult for contributors to evaluate and discuss. Such RFCs should be broken into multiple different RFCs to enable clear discussion of a single issue at a time. (It can also be helpful to stagger the introduction of such RFCs over time, just to enable contribution to each at a time)

Keep in mind the advice from the contributing guide:

> Successful critiques of the curriculum will point out ways that OSSU is failing to uphold these guidelines. Examples are:
> - OSSU lists a course as required when the course topics are elective in the curricular guide.
> - OSSU does not having a course to cover required topics from the curricular guide.
> - OSSU lists multiple courses that cover the same topics when fewer courses could suffice.
> - OSSU recommends a course to teach a topic, but there exists a higher quality course that covers the same material.

**Comment by waciumawanjohi** [comment]
Note:
> The crypto course that I made was rejected under https://github.com/ossu/computer-science/issues/1067 for not conforming to western social norms.

The RFC was closed because the proposed course did not adhere to OSSU's [Code of Conduct](https://github.com/ossu/code-of-conduct), as is made clear in the RFC.

**Comment by riceeatingmachine** [comment]
Split 2 points. Will split all of them in a staggered way as suggested.
