### ISSUE TITLE
RFC: Replacement of Poor Software Engineering courses with NPTEL

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1082]
**Problem:**
Object Oriented Design, Design Patterns, Software Architecture teach their topics in roundabout ways by forcing students to use the android development toolkit. As such, they are not great for the purposes of the OSSU. 

Software Engineering - Introduction is generally thought of as students here to be a poor course, which some people skipping it entirely.

(See [this](https://github.com/ossu/computer-science/issues/869#issuecomment-795987593), #747, [this](https://github.com/ossu/computer-science/issues/747#issuecomment-659737345), [this](https://github.com/ossu/computer-science/issues/747#issuecomment-659741867), [this](https://github.com/ossu/computer-science/issues/549#issuecomment-497976042))

**Duration:**
1 Month. 

**Background:**
Splitting #1080 

There are certain courses in the curriculum that aren't particularly great but have been kept due to lack of better courses. I've been scouring the internet and I found [NPTEL](https://nptel.ac.in/courses) (National Programme on Technology Enhanced Learning) which contains a lot of computer science courses from The Indian Institute of Technology - the highest tech universities in India. Think of it like OCW for the IITs.

They are generally though to be high quality courses in India, and this is the best university here. The downside is that there are not many practical assignments on NPTEL unlike their university counterparts.

**Proposal:**
Replace Object Oriented Design, Design Patterns, Software Architecture, and Software Engineering: Introduction with [Software Engineering](https://nptel.ac.in/courses/106101061) by IIT Kharagpur and [Software Conceptual Design](https://nptel.ac.in/courses/106101235) by IIT Bombay. 

**Alternatives:**
1. We could look for alternative resources.

**Comment by riceeatingmachine** [comment]
Alternative (I think some of you might prefer these to the NPTEL videos):

Object Oriented Design: https://www.youtube.com/watch?v=fJW65Wo7IHI&list=PLGLfVvz_LVvS5P7khyR4xDp7T9lCk9PgE
Design Patterns: https://www.youtube.com/watch?v=v9ejT8FO-7I&list=PLrhzvIcii6GNjpARdnO4ueTUAVR9eMBpc
Software Architecture: https://www.youtube.com/watch?v=3bxAm3XIFmk&list=PLdsOZAx8I5umhnn5LLTNJbFgwA3xbycar&index=146 (Should be elective)
Agile: https://www.youtube.com/watch?v=dfR6UBEBVvo&list=PLWKjhJtqVAbm0gPNunWf4pr4xV8I3Geh-

This are highly regarded youtube series.

**Comment by aayushsinha0706** [comment]
What do you think of these resources

https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.005.1x+3T2016/about
https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.005.2x+1T2017/about

**Comment by riceeatingmachine** [comment]
Just a prima facie review:

They overlap with HtC and some other courses. They don't cover design
patterns and software engineering. As such they are not suitable
replacement for the ones I proposed.

**Comment by aayushsinha0706** [comment]
my prime recommendations will be above two MIT courses with this newer Software engineering course by IIT KGP

https://nptel.ac.in/courses/106105182

**Comment by riceeatingmachine** [comment]
I had a deeper look into the MIT courses. Here is a comparison.

The topics covered by the courses we are removing:

<table>
<tbody>
<tr>
<td>&nbsp;<strong>Course</strong></td>
<td><strong>Topics</strong></td>
</tr>
<tr>
<td>&nbsp;Object-Oriented Design</td>
<td>
<p>&nbsp;Object-Oriented Design</p>
<p>Object-Oriented Analysis And Design</p>
<p>Unified Modeling Language (UML)</p>
</td>
</tr>
<tr>
<td>&nbsp;Design Patterns</td>
<td>&nbsp;Design Patterns</td>
</tr>
<tr>
<td>&nbsp;Software Architecture</td>
<td>&nbsp;Software Archetecture (subroutines, classes, functions, etc), evaluation and tradeoffs</td>
</tr>
<tr>
<td>&nbsp;Software Engineering - Introduction</td>
<td>Agile development, REST and Async programming, design, refactoring, information security</td>
</tr>
</tbody>
</table>

<p>&nbsp;</p>

The topics covered by the MIT courses are:

<table>
<tbody>
<tr>
<td><strong>Course</strong> </td>
<td><strong>Topics Covered</strong></td>
</tr>
<tr>
<td>&nbsp; 6.005.1x Software Construction in Java&nbsp;</td>
<td>Java programming<br /> Software testing<br /> Code specifications<br /> Abstract data types</td>
</tr>
<tr>
<td>&nbsp; 6.005.2x Advanced Software Construction in Java&nbsp;</td>
<td>
<p>(1) grammars, parsing, and recursive datatypes;</p>
<p>(2) concurrent programming with threads.</p>
</td>
</tr>
</tbody>
</table>

<p>&nbsp;</p>

They don't seem to be covering the same topics so it would not be productive to use them as replacements of the courses proposed to be removed.

**Comment by aayushsinha0706** [comment]
I would like to quote CS2013 requirements for software development fundamentals and software engineering.

CS2013 says following topics are tier 1 topics that needs to be covered 
SDF/Algorithms and Design 
SDF/Fundamental Programming Concepts 
 SDF/Fundamental Data Structures
 SDF/Development Methods
 
 while we already cover algorithms and data structures in core theory
 
>SDF/Fundamental Programming Concepts
[10 Core-Tier1 hours]
This knowledge unit builds the foundation for core concepts in the Programming Languages Knowledge Area, most notably in the paradigm-specific units: Object-Oriented Programming, Functional Programming, and Event-Driven & Reactive Programming.
Topics:
• Basic syntax and semantics of a higher-level language
• Variables and primitive data types (e.g., numbers, characters, Booleans)
• Expressions and assignments
• Simple I/O including file I/O
• Conditional and iterative control structures
• Functions and parameter passing
• The concept of recursion

>SDF/Development Methods
[10 Core-Tier1 hours]
This unit builds the foundation for core concepts in the Software Engineering knowledge area, most notably in the Software Processes, Software Design and Software Evolution knowledge units.
Topics:
• Program comprehension
• Program correctness
o Types of errors (syntax, logic, run-time)
o The concept of a specification
o Defensive programming (e.g. secure coding, exception handling)
o Code reviews
o Testing fundamentals and test-case generation
o The role and the use of contracts, including pre- and post-conditions o Unit testing
• Simple refactoring
• Modern programming environments
o Code search
o Programming using library components and their APIs
• Debugging strategies
• Documentation and program style

Using CS2013 guidelines we can say above two MIT courses will be best suited to cover these topics

**Comment by aayushsinha0706** [comment]
Lets talk about software engineering

cs2013 states following topics as absolute necessary
>SE/Software Processes
Topics:
[Core-Tier1]
• Systems level considerations, i.e., the interaction of software with its intended environment (cross- reference IAS/Secure Software Engineering)
• Introduction to software process models (e.g., waterfall, incremental, agile) o Activities within software lifecycles
• Programming in the large vs. individual programming

>SE/Software Design
[3 Core-Tier1 hours; 5 Core-Tier2 hours]
Topics:
[Core-Tier1]
• System design principles: levels of abstraction (architectural design and detailed design), separation of concerns, information hiding, coupling and cohesion, re-use of standard structures
• Design Paradigms such as structured design (top-down functional decomposition), object-oriented analysis and design, event driven design, component-level design, data-structured centered, aspect oriented, function oriented, service oriented
• Structural and behavioral models of software designs
• Design patterns

>SE/Requirements Engineering
[1 Core-Tier1 hour; 3 Core-Tier2 hours]
The purpose of requirements engineering is to develop a common understanding of the needs, priorities, and constraints relevant to a software system. Many software failures arise from an incomplete understanding of requirements for the software to be developed or inadequate management of those requirements.
Specifications of requirements range in formality from completely informal (e.g., spoken) to rigorously mathematical (e.g., written in a formal specification language such as Z or first-order logic). In practice, successful software engineering efforts use requirements specifications to reduce ambiguity and improve the consistency and completeness of the development team’s understanding of the vision of the intended software. Plan-driven approaches tend to produce formal documents with numbered requirements. Agile approaches tend to favor less formal specifications that include user stories, use cases, and test cases.
Topics:
[Core-Tier1]
• Describing functional requirements using, for example, use cases or users stories
• Properties of requirements including consistency, validity, completeness, and feasibility

Now for software engineering I am offering this course by IIT KGP NPTEL
https://nptel.ac.in/courses/106105182

What this course covers
Week 01 : Introduction
Week 02 : Life Cycle Models I
Week 03 : Life Cycle Models II
Week 04 : Requirements analysis and specification
Week 05 : Basics of software design
Week 06 : Procedural design methodology
Week 07 : Object-oriented concepts
Week 08 : Introduction to UML: Class and Interaction Diagrams Week 09 : Object-oriented analysis and design
Week 10 : Testing I
Week 11 : Testing II
Week 12 : Testing III

The above course already covers topics like Object oriented design,Unified Modeling Language (UML) but also Procedural design methodology with software testing and secure programming. I guess this is best course that we have now to cover software engineering.

Not that I am against courses that you recommend its just that we dont really need them. Maybe an advanced software engineering section or advanced programming can get those courses.

**Comment by aayushsinha0706** [comment]
Also sorry to mention about RFC #933 was accepted without considering CS2013 document.

**Comment by waciumawanjohi** [comment]
> Also sorry to mention about RFC https://github.com/ossu/computer-science/issues/933 was accepted without considering CS2013 document.

[???](https://github.com/ossu/computer-science/issues/933#issuecomment-900777358)

**Comment by aayushsinha0706** [comment]
> > Also sorry to mention about RFC #933 was accepted without considering CS2013 document.
> 
> [???](https://github.com/ossu/computer-science/issues/933#issuecomment-900777358)

The RFC never made a reference to CS2013 doc also I did not find any course in CS2013 which was similar to software architecture although object oriented design and design patters were justified for SE/software design (might be a misunderstanding from my side , I apologise for it). The RFC just compared courses from original software engineering courses.

**Comment by riceeatingmachine** [comment]
> Using CS2013 guidelines we can say above two MIT courses will be best suited to cover these topics

Ah it looks like I should have been clearer in the earlier messages. 

To elaborate on:

> They overlap with HtC and some other courses. They don't cover design patterns and software engineering. As such they are not suitable replacement for the ones I proposed

What I meant to say was that the MIT courses don't teach the topics that are taught by the courses we are removing, **and the topics they do teach are already covered by other courses in the curriculum.** 

I'll mark the course (in **bold**) in the curriculum that already covers the topic in the list:

    SDF/Fundamental Programming Concepts
    [10 Core-Tier1 hours]
    This knowledge unit builds the foundation for core concepts in the Programming Languages Knowledge Area, most notably in the paradigm-specific units: Object-Oriented Programming, Functional Programming, and Event-Driven & Reactive Programming.
    Topics:
    • Basic syntax and semantics of a higher-level language **PLABC**
    • Variables and primitive data types (e.g., numbers, characters, Booleans)  **PLABC**
    • Expressions and assignments  **PLABC**
    • Simple I/O including file I/O **CS50/Nand2Tetris**
    • Conditional and iterative control structures  **PLABC, Nand2Tetris, Intro to CS** 
    • Functions and parameter passing **PLABC**
    • The concept of recursion **HtC, PLABC**

    SDF/Development Methods
    [10 Core-Tier1 hours]
    This unit builds the foundation for core concepts in the Software Engineering knowledge area, most notably in the Software Processes, Software Design and Software Evolution knowledge units.
    Topics:
    • Program comprehension **PLABC**
    • Program correctness **Software Testing and Debugging**
    o Types of errors (syntax, logic, run-time) **Software Testing and Debugging**
    o The concept of a specification **Software Testing and Debugging**
    o Defensive programming (e.g. secure coding, exception handling) **Core Security**
    o Code reviews **Software Testing and Debugging**
    o Testing fundamentals and test-case generation **HtC, Software Testing and Debugging**
    o The role and the use of contracts, including pre- and post-conditions o Unit testing **Software Testing and Debugging**
    • Simple refactoring **Software Testing and Debugging** (if I remember correctly)
    • Modern programming environments **The missed Semester in CS** (???)
    o Code search **Software Engineering** (???)
    o Programming using library components and their APIs **HtC, Nand2Tetris**
    • Debugging strategies**Software Debugging**
    • Documentation and program style **HtC, Software Testing and Debugging**



As a result, by adding these two MIT courses, we are just making the curriculum redundant and longer but not covering any new topics. 

> Now for software engineering I am offering this course by IIT KGP NPTEL https://nptel.ac.in/courses/106105182

I agree with this change, it covers the same topics as the [one I proposed](https://nptel.ac.in/courses/106101061) as well. We still need to cover UML so we need to include [the other one I proposed](https://nptel.ac.in/courses/106101235) too (it's much shorter).

**Comment by riceeatingmachine** [comment]
[The one you mentioned](https://nptel.ac.in/courses/106105182) @aayushsinha0706 seems to only cover the topics covered by Software Engineering - Introduction.

[The other one](https://nptel.ac.in/courses/106101061) also covers design patterns, object oriented design, and architecture along with software engineering. 

The only thing is it doesn't cover UML, so I also included [Software Conceptual Design](https://nptel.ac.in/courses/106101235) to cover that part of the curriculum. Although my friends in the industry tell me "no one uses UML anymore" so maybe we can do without it?

**Comment by aayushsinha0706** [comment]
I support the other one because it covers SE/Software Project Management which I didn't mentioned but it is a core-tier 2 topic that one I mentioned doesn't teach. 

I guess final offering will be then:
Software Engineering IITB NPTEL
Software Testing and Debugging
in
core-application

**Comment by aayushsinha0706** [comment]
Although above software engineering course is a video only course and I would request to add some supplementary reading material with it. 
https://software-engineering-book.com

This is one of highly regarded textbooks as first course in software engineering (here is the [contents ](https://www.dropbox.com/s/9kd1skyiczis29b/Contents.pdf?dl=0) page of textbook), although author has not made textbook free but he has made slideshare presentations for each chapter of the book available for free which can be a good reading resource

https://software-engineering-book.com/slides/ and also listed some [videos](https://software-engineering-book.com/videos/) he finds useful to understand topics in book better.

**Comment by riceeatingmachine** [comment]
End of 30 days.

Conclusion: We did not receive enough comments from students and no consensus seems to have been reached, so I've closed the RFC with no commits.
