### ISSUE TITLE
How much Linear Algebra is needed for Computer Graphics?

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#1084]
I see linear algebra is a pre-requisite and Computer Graphics is in the core section. Gilbert Strang's course is in advanced, so I'm assuming it's elective.

Does computer graphics require Gilbert Strang's Linear Algebra, or does the prerequisite mean general high school level Linear algebra (think khan academy level)?

**Comment by Alaharon123** [comment]
A related question is if Computer Graphics should be in Core, or if it should be moved to Advanced. At a glance, it seems to cover primarily topics in the elective portion of the Graphics and Visualization portion of CS2013, which would mean it belongs in Advanced, but I haven't taken a closer look

**Comment by waciumawanjohi** [comment]
Relevant convo: https://github.com/ossu/computer-science/issues/841#issuecomment-751377198

I stated there that I was going to make an RFC to move our current Computer Graphics course to Advanced. Obviously I haven't done that yet. This is definitely a place in the curriculum that can be improved by someone that has time to dive into available Computer Graphics classes.

**Comment by riceeatingmachine** [comment]
I see. The @spamegg1 quote below answers the question I asked, so I am closing this thread.

>The math required here is: matrix/matrix multiplication, matrix/vector multiplication, normalizing vectors, taking cross-products of two vectors to obtain a third one in order to create an orthogonal set of vectors in 3D, and normalizing those to obtain an "orthonormal basis" as we say in linear algebra (although this is somewhat of an intersection of LA and Vector Calculus), a solid understanding of what matrices do on the 2D plane and in 3D space and some ability to visualize it (you can't solve the first Transformations assignment without this).

**Comment by riceeatingmachine** [comment]
@waciumawanjohi we can solve this confusion by changing the prerequisite from "Linear Algebra" to "Basic Linear Algebra"
