### ISSUE TITLE
Minor: Deprecated topic on the Trello board

### ISSUE THREAD

**Issue by manpagebob** [ossu/computer-science#1089]
@waciumawanjohi  - Not sure as to whether you're the maintainer of the Trello board, or if it's being maintained at all, but it contains what I presume is an old reference to CS50 - "018 - Introduction to Computer Science - CS50"

Thanks for the effort and all good work by the way. :)

**Comment by aayushsinha0706** [comment]
Computer-science as a repository receives contribution everyday. I think we should remove link of trello board as it might confuses new comers. We are already dealing with deprecated OSS Firebase app.

**Comment by pb-413** [comment]
I'm a perspective student of this curriculum and volunteer to update the Trello if I can be granted access/permission.

Else, it is a good starting point for that type of organization. I'd rather see it kept, but understand the desire to remove, especially if access/ability to keep it up to date is a worry.
