### ISSUE TITLE
Computer Programming 

### ISSUE THREAD

**Issue by emtolalaa** [ossu/computer-science#1095]
Always study

**Comment by samuelbarrionuevo** [comment]
https://www.sciencedirect.com/science/article/pii/S2468227622001478

**Comment by waciumawanjohi** [comment]
Hi @emtolalaa and @samuelbarrionuevo 
These are interesting conversation starters but are not issues that need to be addressed with the curriculum. I recommend that you share these thoughts with other OSSU students in the Discord: https://discord.gg/wuytwK5s9h
