### ISSUE TITLE
RFC: Change course for Theory of Computation to the one in openMIT

### ISSUE THREAD

**Issue by angle943** [ossu/computer-science#1096]
**Problem:**
We currently use professor Shai Simonson's series of youtube video, and his outdated website as an offering for "Theory of Computation" under [Advanced Theory](https://github.com/ossu/computer-science#advanced-theory). There are a couple issues with this:

- The videos are low quality (video-quality-wise)
- The [course website](http://aduni.org/courses/theory/index.php?view=cw) is on an insecure domain, and most of the hw problems and hw problem solution link doesn't work (at least on my computer).
- - As an example, the only problem set I can open is `Problem_Set_01`. None of the other homework set opens
- - Only solutions for hw4&5 open (keep in mind we don't have access to the problem set for these). None of the others work
- - None of the exam links work.
- There is a much higher quality alternative in the [OpenMITCourseware](https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/), taught by professor Michael Sipser, who arguably wrote the most [standard Intro to computation textbook](https://www.amazon.com/Introduction-Theory-Computation-Sipser/dp/8131525295/ref=sr_1_1?crid=1A6GV0ZW2B19N&keywords=theory+of+computation&qid=1667144813&qu=eyJxc2MiOiIzLjE5IiwicXNhIjoiMi41NCIsInFzcCI6IjIuNzMifQ%3D%3D&sprefix=theory+of+computation%2Caps%2C94&sr=8-1).
- - MIT Open Courseware is a format that many OSSUers are already comfortable with, since we have few other courses in this format. Videos are extremely high quality, Lecture notes PDF and PPT are available.
- The only wrinkle to this plan is that the "Homework" references problem from his textbook, which is not given as a free PDF. However, IF you do have his textbook, there is access to literally every solutions in this github page: https://github.com/gaurangsaini/sipser-computation-3rd-solutions (it is worth mentioning though this these are solutions to the 3rd edition, and the homework seems to be referencing the 2nd edition

**Proposal:**
As I said, the only problem with this plan is that the course work on the MIT one assumes you have a book, but the one we offer currently is no better. Most of the homework sets are not accessible (again, at least on my computer. perhaps other will have a different outcome). So I propose that since essentially we are left with two options, neither of which have homework (at least the MIT one is accessible if you buy his book, where as the other course is forever lost into the web abyss), and since the MIT one has full solutions to his textbook, I propose that we switch to the superior MIT one.

**Comment by anantav51** [comment]
Agreed, the homework sets and solutions not being accessible makes switching to the MIT Open Courseware a no-brainer, it's a much better option for learning. I don't see a reason sticking to current course.

**Comment by waciumawanjohi** [comment]
This RFC has been open for a number of months and has received only support. I encourage a contributor to open a Pull Request with these changes that will resolve this proposal.
