### ISSUE TITLE
RFC: Consider adding https://www.learncs.online/ as your intro to CS course

### ISSUE THREAD

**Issue by jdcampolargo** [ossu/computer-science#1104]
The intro course currently provided may not be as strong with fundamentals and practice, as https://www.learncs.online/. This course provides depth, fundamentals, lots of practice, and more importantly, to learn everything you need you don't need to leave the website as you can run the code, watch the videos, and do the practice inside that one URL. Highly consider it.

**Comment by waciumawanjohi** [comment]
Hi Juan David,
Glad to see that you are interested in CS education. As you can imagine, changing a course in the curriculum is a fair undertaking. Our contributing guide has [suggestions for the sort of information](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes) that contributors should share when making such a suggestion. And when you open a pull request there is a template available that can help structure a request.

From your description, the only advantage I can see in [learncs.online/](https://www.learncs.online/) is:
> you don't need to leave the website
I don't see any analysis of what topics are covered that aren't covered by our intro course, nor what the current course covers that learncs.online doesn't.

**Comment by waciumawanjohi** [comment]
Closing this issue on lack of response. Please feel free to re-open with more information. See [here](https://github.com/ossu/computer-science/issues/1111#issuecomment-1345275298) for an example of an RFC comment that substantively demonstrates strengths and weaknesses of adopting a new course.
