### ISSUE TITLE
RFC: Bridge the Discord community to Matrix

### ISSUE THREAD

**Issue by Jackdaw-Zero** [ossu/computer-science#1106]
**Problem:**
The community for the _Open Source_ Society University should not be trapped exclusively on a closed, proprietary platform like Discord. As evidenced by the controversial Twitter takeover and subsequent migration to Mastodon, access over open protocols makes online communities both more inclusive and more robust.

**Duration:**
2 months (to account for the holidays)

**Background:**
This is an update to https://github.com/ossu/computer-science/issues/903 as I think the difficulty of implementing this was either overestimated at the time or has been lowered by the introduction of the t2bot.io host service since the last request was closed.

Previously, OSSU has made use of a Gitter instance to support community chat on an open protocol at https://gitter.im/open-source-society/home. These rooms are now abandoned and all communication directs the community to the Discord server. 

Using a matrix.org host and a bot hosted by t2bot.io powered by https://github.com/matrix-org/matrix-appservice-discord, it is possible to allow participation over an open protocol without additional hosting resources or moderator effort. 

**Proposal:**

- Create Matrix rooms on the matrix.org public server for the OSSU curricula.
- Using the instructions at https://t2bot.io/discord/ bridge the Matrix rooms to the existing discord rooms.

**Alternatives:**

- Show the existing Gitter (https://gitter.im/open-source-society/home) as an alternative to the Discord server in README files
- IRC remains an option

**Comment by joshmhanson** [comment]
Maybe add [Revolt](https://revolt.chat/) to the Alternatives list? It's more similar to Discord than Matrix. I've never used it myself, though. And our community is now firmly entrenched in Discord so we might have to wait for an unstable billionaire to buy it before the community can be convinced to switch to something else... 😅

Personally I would have also preferred an open source solution from the get-go, but at the time we made the switch to Discord, none of the options were even remotely polished/usable enough.

To comment on the meat of this RFC: if we have a Matrix bridge then at minimum, we would need someone the community knows and trusts to maintain that bridge (e.g. adding/removing channels every time we change them on Discord). This seems like a pain and could potentially be a lot of management overhead.

I am also not familiar with Matrix's policies on room creation on their server. I thought they typically discouraged people from creating lots of rooms and prefer that communities host their own servers - is that not accurate anymore? Currently we have more than 60 rooms... it just doesn't seem scalable to the Matrix/IRC model.

**Comment by Jackdaw-Zero** [comment]
Revolt is certainly snazzy and I wouldn't mind including it. I originally suggest Matrix because the existence of the bridge allows a smooth opening of a path towards an open messenger without splintering the community.

As I don't have a Discord account, I haven't seen into the extant OSSU server to comment on your room creation habits, but matrix.org does support multiple rooms in a space, and I haven't seen any policy restricting their creation.

Also as an update since posting this RFC, gitter appears to be merging fully into the Matrix protocol, so that might be another point in favor of going that direction if you just want to focus on using what already exists. 

https://blog.gitter.im/2023/01/16/gitter-is-going-fully-native-matrix-in-feb-2023/

**Comment by Choubs01** [comment]
I'm a fan of open source and privacy as much as the next guy, but I don't see this happening especially at the scale of OSSU.

**Comment by Smitgan** [comment]
Unsubscribe

**Comment by bradleygrant** [comment]
Strongly disagree. The key metric here is community reach, not whether the platform code itself is available on GitHub. Much like Ariel, we want to be where the people are, and the people are not on [niche-messaging-clone-#14].

**Comment by waciumawanjohi** [comment]
The comment period has completed. Reception to this RFC has been muted. I do not see anyone that is volunteering to undertake the work to implement this RFC. While the RFC states "it is possible to allow participation over an open protocol without additional hosting resources or moderator effort.", it does not account for the work to setup and maintain the bridge.

Closing this RFC. If in the future an individual or group would like to volunteer the work needed to create a trial bridge, their efforts would be welcome.
