### ISSUE TITLE
Login with GitHub Not Working on All Web Browsers

### ISSUE THREAD

**Issue by djlaserman** [ossu/computer-science#1119]
I was so excited about this project until I found that I can't login with GitHub and it is the only login method available. So I asked myself, all this computer science overload at ossu but a simple login feature is broken?

**Comment by aayushsinha0706** [comment]
Are you talking about OSSU Firebase app https://ossu.firebaseapp.com/ , it was developed by previous OSSU students but never updated it, we have tried contacting the developers to either update the app and or to take it down as it is misguiding many students. It is mentioned in FAQs in our discord chat though 

Why is the Firebase OSSU app different or broken?
A: The OSSU curriculum and ecosystem have been collaboratively built by many individuals. The Firebase app was one such contribution. Unfortunately, the app has not been updated in many years. It does not reflect updates to the curriculum. It is our hope that the creators of the Firebase app can bring the app up to date. Until that time, the firebase app should be considered a deprecated product that is no longer supported.

**Comment by djlaserman** [comment]
> Are you talking about OSSU Firebase app https://ossu.firebaseapp.com/ , it was developed by previous OSSU students but never updated it, we have tried contacting the developers to either update the app and or to take it down as it is misguiding many students. It is mentioned in FAQs in our discord chat though
> 
> Why is the Firebase OSSU app different or broken? A: The OSSU curriculum and ecosystem have been collaboratively built by many individuals. The Firebase app was one such contribution. Unfortunately, the app has not been updated in many years. It does not reflect updates to the curriculum. It is our hope that the creators of the Firebase app can bring the app up to date. Until that time, the firebase app should be considered a deprecated product that is no longer supported.

Yes that is what I'm talking about, I suppose those students didn't learn much! Or maybe they decided to abandon the project's firebase app. There is no problem beyond that one nick however as everything is accessible inside GitHub repositories. It was a bad landing because my search led me straight to that app or website and on failure to login it was puzzling. But yeah everything is accessible if accessed directly, however I get the feeling inside GitHub it's complicated to actually keep track of what one has done and which assignments were completed without going through hoops and loops. It would be lovely if it was organized into a website that can then make all that modules planning and assignments tracking all the more palatable. But since there is no certification in any case all that is important is the knowledge content and the quality of the lessons and their coverage because certificates don't get the work done, knowledge however does gets things done if acquired in complete contexts of the subjects presented.
