### ISSUE TITLE
RFC: Add alt link for computer graphics course

### ISSUE THREAD

**Issue by Choubs01** [ossu/computer-science#1140]
**Problem:**
There are people who aren't fans of the edX format. I suggest adding an alt link for the computer graphics course in core applications.

**Duration:**
1 month perhaps

**Proposal:**
The following is a link to the same course offering in Winter 2022, so it is up to date: https://cseweb.ucsd.edu/~viscomp/classes/cse167/wi22/schedule.html. Add it after the computer graphics course as a hyperlinked (alt) link.

**Comment by Harikrishna3** [comment]
Hey, I can do this.
