### ISSUE TITLE
Error while enrolling in course

### ISSUE THREAD

**Issue by MubashirWaheed** [ossu/computer-science#1144]
The "How to code complex data" course in the core programming module is not available.
Course needs to be replaced

**Comment by aziichi** [comment]
It's available for enrollment on my end. Are you getting some kind of error message when trying to enroll? Did you enroll in it before once and the access has expired?

**Comment by aziichi** [comment]
@MubashirWaheed I see, Well, in that case I can suggest some alternatives.
1.  You can try the book <a href="https://htdp.org/2022-8-7/Book/">How to Design Programs</a> on which the courses How to Code: Simple Data and How to Code: Complex Data are based.
2. You can also try <a href="https://inst.eecs.berkeley.edu/~cs61a/su20/">CS61A: Structure and Interpretation of Computer Programs</a> course and the textbook <a href="composingprograms.com">Composing Programs</a> to go along with it. These two use Python to teach the concepts of programming.
3. Lastly, you can go for the classic <a href="https://sarabander.github.io/sicp/html/index.xhtml">SICP</a> book and these <a href="https://archive.org/details/ucberkeley-webcast-PL3E89002AA9B9879E?sort=titleSorter">lectures videos</a> to go along with it. This one will be a bit harder I suppose, as some students find it difficult to get through SICP and it's not recommended for someone without any kind of programming background. Also, the language it uses is Scheme just to keep that in mind.
