### ISSUE TITLE
ACM/IEEE CS2023 is in beta. Will this reflect an updated curriculum gradually for in-progress learners

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#1149]
I see that the ACM & IEEE education committee (in association with AAAI for the 1st time) have published (currently, a 2nd) beta of the topics to be covered in their CS2023 curriculum. https://csed.acm.org/wp-content/uploads/2023/03/Version-Beta-v2.pdf 

Does this have any implications for those who are in progress with the current OSSU curriculum. i.e. are the moderators evaluating the new CS2023 draft and already considering making substantial changes?

**Comment by waciumawanjohi** [comment]
I've updated the curriculum guideline page to explicitly point out that the CS2023 is in progress. See: https://github.com/ossu/computer-science/commit/74380ad993dadeeed9dcaff500c148fe7e9d9999

You can see an example of contributor already referencing this work [here](https://github.com/ossu/computer-science/issues/1118#issuecomment-1370477667).

There are no secret changes to the curriculum; changes are proposed, discussed and approved through the RFC process.
