### ISSUE TITLE
RFC: Cant enroll in the Calculus 1C: Coordinate Systems & Infinite Series course

### ISSUE THREAD

**Issue by zyrin0** [ossu/computer-science#1150]
The course Calculus 1C: Coordinate Systems & Infinite Series is not available anymore.

**Comment by waciumawanjohi** [comment]
The curriculum links to [Calculus 1C: Coordinate Systems & Infinite Series](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.3x+1T2020/about)

Here is an image capture from that page demonstrating that the course is available on Open Learning Library.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/18407643/232350969-90e34e66-70a5-437a-81de-8dc25169620d.png">
