### ISSUE TITLE
RFC: 

### ISSUE THREAD

**Issue by danielbyiringiro** [ossu/computer-science#1153]
**Problem:**
OSU lists courses links that are obsolete.
The course Effective thinking throug mathematics [https://www.edx.org/course/effective-thinking-through-mathematics] does not exist on edx.

**Duration:**
I checked them out today

**Proposal:**
Search for working links

**Comment by waciumawanjohi** [comment]
Thanks for pointing out this dead link.

Fixed by commit: https://github.com/ossu/computer-science/commit/d27b2dfc9a7427fcbaf5c06cd57b9988e0c72a50
