### ISSUE TITLE
RFC: Adding another optional introduction to cs harvard CS50 2023

### ISSUE THREAD

**Issue by aryankumarakj** [ossu/computer-science#1165]
**Problem:**

* OSSU in introduction to cs only introduce with python and there is no other aspectsof cs is  covered like c and html and many more.

**Duration:**
10 week

**Background:**
Righ now the intro to cs  is python  Oriented and both of them are good but we need another intro to be added as optional which will cover the whole veiw on cs in short .there is no mean to remove any intro cource just adding another short cource which covers different topics and this cource will be like quick flash card for what they will be going to learn in their core cs.

This is CS50, Harvard University’s introduction to the intellectual enterprises of computer science and the art of programming, for concentrators and non-concentrators alike, with or without prior programming experience.This course teaches you how to solve problems, both with and without code, with an emphasis on correctness, design, and style.Topics include computational thinking, abstraction, algorithms, data structures, and computer science more generally.

**Proposal:**
-just adding cs50 in cource and pull request link:-(https://github.com/ossu/computer-science/pull/1163) 
(code for pull request:-gh pr checkout 1163)

**Comment by pulkitkrishna00** [comment]
> OSSU in introduction to cs only introduce with python and there is no other aspectsof cs is covered like c and html and many more.

C and HTML are **not** "aspects" of CS. MIT 6001x is enough for a good introduction to CS.

**Comment by aryankumarakj** [comment]
@pulkitkrishna00 
I read those discussion  and sorry if i mentioned anything improper in my issue request i am saying just to add another option to indroduction which covers otside of python  and also other topics as i did both intrioduction from mit and harvard cs50 .just i felt they update the cource every year and also there content are more covering other topics so we could keep it as alternative and not mandatory .as cs50 cources professors and faculty are very intrating and does live coding and  they have good project works every weeks.

**Comment by pulkitkrishna00** [comment]
> @pulkitkrishna00 I read those discussion and sorry if i mentioned anything improper in my issue request i am saying just to add another option to indroduction which covers otside of python and also other topics as i did both intrioduction from mit and harvard cs50 .just i felt they update the cource every year and also there content are more covering other topics so we could keep it as alternative and not mandatory .as cs50 cources professors and faculty are very intrating and does live coding and they have good project works every weeks. thanks for your opinion

Python, C or HTML are not Computer Science. They are languages. Covering "other topics" is not necessarily a good thing. This curriculum is not about teaching languages.

If you want it to be added as an "optional course", it is already listed here: [https://github.com/ossu/computer-science/blob/master/extras/courses.md](https://github.com/ossu/computer-science/blob/master/extras/courses.md), which also lists other optional courses.

**Comment by aryankumarakj** [comment]
its just not language other things are there to but yeah i saw this before but i taugh it won't create more intrest for  other to do as very less people visits extra cource .i taught it would add more values to others it they do this but fine
