### ISSUE TITLE
RFC: Object-Oriented Design Course is Prerequiring basics of JAVA

### ISSUE THREAD

**Issue by AhmedKaram50** [ossu/computer-science#1167]
Hi I am an OSSU student and I found myself in this course that prerequiring JAVA Basics and none of the previous courses introduced JAVA to me 
and I am coming from a web development background so i have never seen JAVA code before 

Object-Oriented Design
[Object-Oriented Design](https://www.coursera.org/learn/object-oriented-design)

**Comment by waciumawanjohi** [comment]
> none of the previous courses introduced JAVA

This is an accurate statement. Also true is that the course immediately prior is Programming Languages Part C, whose goal is to introduce students to the class of object oriented languages (Java is a prominent object oriented language). The entry for Object Oriented Design also notes that Java is a pre-requisite and points users to a relatively short introduction to the language (<4 hours lecture).

Contributors are always encouraged to identify resources that would be better fits for the curriculum (and to explain why they are better in an RFC). And the discord has channels for each course in the curriculum.

Closing this as there is no further action to take at this moment. Feel free to open a new RFC with a recommendation for a change to the curriculum.
