### ISSUE TITLE
RFC:  problem on course Software Testing 

### ISSUE THREAD

**Issue by sayed4900** [ossu/computer-science#1179]
Course software testing isn't open and I think this the new link https://www.udacity.com/course/software-analysis-testing--ud333

**Comment by waciumawanjohi** [comment]
> Course software testing isn't open

Thank you for pointing this out!

The course that you linked is a new course, by different instructors. If we're recommending a new course (not simply finding where the current recommendation has moved), then we should go through an actual [RFC process](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes) that recommends a course and details how it is superior to the alternatives. It looks like there are a number of options for a course on software testing.

**Comment by waciumawanjohi** [comment]
I'll also note that the Software Debugging course is no longer offered and instead points to a Udacity Nanodegree on becoming a Site Reliability Engineer. Not something that must be addressed in the Testing RFC.

**Comment by spamegg1** [comment]
Do these links work? They may require a Udacity log-in first.

https://learn.udacity.com/courses/cs258

https://learn.udacity.com/courses/cs259

**Comment by pulkitkrishna00** [comment]
> Do these links work? They may require a Udacity log-in first.
> 
> https://learn.udacity.com/courses/cs258
> 
> https://learn.udacity.com/courses/cs259

No, they redirect to "My Programs" page, and do not enroll or anything.

**Comment by t-miller** [comment]
> Do these links work? They may require a Udacity log-in first.
> 
> https://learn.udacity.com/courses/cs258
> 
> https://learn.udacity.com/courses/cs259

They work for me

**Comment by zachmmeyer** [comment]
Confirming the links **do not** work for me. When I click them and I am not logged in I am asked to log in. If I click them while logged in I just see My Programs.

**Comment by sams05** [comment]
Seems like videos from the original course is still available under this [YouTube playlist](https://www.youtube.com/playlist?list=PLAwxTw4SYaPkWVHeC_8aSIbSxE_NXI76g).

**Comment by waciumawanjohi** [comment]
Thanks @sams05, I've dropped that link into the curriculum as a stop-gap.

This is still an opportune time to analyze the best course currently available. I'll leave this issue open for another 4 weeks in hopes that a contributor can compare the video playlist to the course noted above:
https://www.udacity.com/course/software-analysis-testing--ud333

**Comment by waciumawanjohi** [comment]
Closing as 4 weeks have elapsed.
