### ISSUE TITLE
RFC: Replacing edX: Software Engineering: Introduction with Coursera: Introduction to Software Engineering

### ISSUE THREAD

**Issue by BudiSalah** [ossu/computer-science#1180]
**Problem:**
The [edx - UBCx: Software Engineering: Introduction](https://www.edx.org/learn/software-engineering/university-of-british-columbia-software-engineering-introduction) is not available now. after some research, I have found an equivalent course on Coursera by [IBM: Introduction to Software Engineering](https://www.coursera.org/learn/introduction-to-software-engineering)

**Proposal:**
Replace Core applications: (Software Engineering: Introduction) course with (IBM: Introduction to Software Engineering) and fix duration and effort if needed.

**Comment by waciumawanjohi** [comment]
If the current recommendation is no longer offered, we need some replacement option. It's possible the UBC course is just temporarily unavailable. With that possibility in mind, let's make a possibly temporary fix:

1. @BudiSalah, will you open a PR to replace the UBC course with the IBM course?
2. In 6 weeks, we'll look and see if the UBC course is on offer. If it is, we'll revert back to it as the recommended course.
3. If you think that the IBM course merits permanently replacing the UBC course, a full RFC would be in order. A successful RFC would:
    1. Compare and contrast the two courses
    2. Discuss what an ideal course would contain (e.g. refer to our curricular guidelines)
    3. Mention other possible courses
    4. Be aware of the conversations in previous RFCs on Software Engineering, e.g.
    - #1082
    - #933
    - #747

The IBM course looks like a [new](https://web.archive.org/web/20230000000000*/https://www.coursera.org/learn/introduction-to-software-engineering) and very well reviewed <img width="224" alt="image" src="https://github.com/ossu/computer-science/assets/18407643/0bf9ead1-9d99-4f45-88fc-11dc97f835c4"> option for a course that has had a few searches for a better alternative. Thanks for identifying the current gap and the new resource on offer!

**Comment by waciumawanjohi** [comment]
I received an edx message that
> Software Development Capstone Project course will no longer be offered as part of the MicroMasters program as of December 30, 2023

But confirming:
> we will continue to offer the other five courses as a full MicroMasters program after we retire the Software Development Capstone Project course

Which went on to list the courses including Course 5: Software Engineering: Introduction.

**Comment by BudiSalah** [comment]
Hello @waciumawanjohi
Sorry for my late response.

Kindly, check this PR:
https://github.com/ossu/computer-science/pull/1184

**Comment by waciumawanjohi** [comment]
PR is merged. I've set a reminder to circle back to this in mid-January to see if the previous course is offered. Closing this issue in the meantime.

**Comment by waciumawanjohi** [comment]
The UBC course is still not on offer. The IBM course will remain the recommended course until an RFC is made to replace it.
