### ISSUE TITLE
How to Enroll into OSS

### ISSUE THREAD

**Issue by MikaOfMoonRock** [ossu/computer-science#1187]
I apologize if this is not the correct place to put this issue, but how do you enroll into OSS? I can't locate where the enrollment link/page is. Any help would be greatly appreciated.

**Comment by pulkitkrishna00** [comment]
There is no need to "enroll". Just start doing the courses. OSSU does not provide any certification or degree.
You can join the OSSU discord community and say "hi": https://discord.gg/wuytwK5s9h
