### ISSUE TITLE
Software Testing course link gives 404

### ISSUE THREAD

**Issue by Camilotk** [ossu/computer-science#1188]
The `Software Testing` course, this one:
![image](https://github.com/ossu/computer-science/assets/30880723/cca00ea5-aa3a-4860-a95f-cf9a3383894c)
Is giving 404 on the Udacity, maybe the course was removed ou changed the URL.

This is the link: https://www.udacity.com/course/software-testing--cs258

Edit: I think maybe they made a new version [here](https://www.udacity.com/course/software-analysis-testing--ud333) or with another name - I just searched the course name.

**Comment by dle51** [comment]
They're different courses unfortunately.

Software Testing CS258 was taught by John Regehr and Sean Bennett, but the course doesn't exist anymore on Udacity.
You can still find the video lectures on YouTube.
[https://www.youtube.com/watch?v=nzJapzxH_rE&list=PLAwxTw4SYaPkWVHeC_8aSIbSxE_NXI76g](url)

The other course is was made by a different team at Georgia Tech
[https://omscs.gatech.edu/cs-6340-software-analysis](url)

**Comment by waciumawanjohi** [comment]
Closing as a duplicate
