### ISSUE TITLE
RFC: Consider adding physics courses

### ISSUE THREAD

**Issue by IanLulu** [ossu/computer-science#1190]
**Problem:**
* OSSU does not have a course to cover required topic physics from our curricular guidelines.

**Background:**
Helps with computer hardware courses

**Proposal:**
Add courses from this source: [How To Take All The Physics Classes You Need Right From Your Computer(video)](https://youtu.be/qw3oZ3keZh4?si=uR0pXcjz9paNX4AZ), [(doc)](https://docs.google.com/document/d/1CW8sE9ywo62TN0KBZ6tZdhfpyfhgVe2CL6uUotVR1W0/edit)

**Comment by waciumawanjohi** [comment]
> physics _from our curricular guidelines_.

Where is that in the CS 2013?

**Comment by IanLulu** [comment]
> Where is that in the CS 2013?

If you're referring to ACM's CS Curricula 2013 it is mentioned on p. 82 that physics knowledge would be useful for a Graphics and Visualization course. The curricula also includes other top universities CS curricula and they include physics as required science electives for a CS education.

**Comment by IanLulu** [comment]
I see, would definitely be interested in contributing. I see that there is a separate track for math. Maybe I can model the physics one after that

**Comment by IanLulu** [comment]
Some more resources I found: 

- [list of educational YouTube channels (Reddit post/Google doc)](https://www.reddit.com/r/edtech/comments/sit1xq/i_made_a_list_of_educational_youtube_channels/?ref=share&ref_source=link)
- [Dianna's Intro Physics Class / Physics 101 / AP Physics 1 Review with Physics Girl (YouTube playlist)](https://youtube.com/playlist?list=PLGO_AWB1C4GQz6JF3-0yZHpoKfqZb7O5z&si=ttqNWImV8gd30_mj)
