### ISSUE TITLE
The advanced math section on cs.ossu.dev is broken

### ISSUE THREAD

**Issue by BagelSeasoning234** [ossu/computer-science#1191]
While the section appears correctly on github.com, it doesn't show up properly on cs.ossu.dev. The strange part is that all of the other tables load properly on the website.

Screenshot of the github page:
![image](https://github.com/ossu/computer-science/assets/70250943/8f88bc51-5e0e-47dc-9f48-03d4abcfa808)

Screenshot of cs.ossu.dev:
![image](https://github.com/ossu/computer-science/assets/70250943/08bcbe46-8d14-4ebf-a731-827b67921bb2)

**Comment by waciumawanjohi** [comment]
Thanks for catching that. Looks like it was just an issue with whitespace and how the different engines treat it.

Fixed by [8ca1e2b](https://github.com/ossu/computer-science/commit/8ca1e2b153bb0bcfd30d8fb7bd36a868cb65dd6a)
