### ISSUE TITLE
RFC: Link for Software Testing course is broken - 404 (under Advanced programming section)

### ISSUE THREAD

**Issue by svenschnydrig** [ossu/computer-science#1197]
The link for the software testing course is broken. I searched for it online, but I think the course might not be available anymore for free. 

If the course is still available could somebody fix the link, if not we would need to find a replacement. 

Thanks in advance, 
Sven

**Comment by ShivamHacker4U** [comment]
Hey

**Comment by waciumawanjohi** [comment]
Closing as a duplicate of this open issue: https://github.com/ossu/computer-science/issues/1179

Note that the curriculum was just updated with the video playlist of the previous course.
