### ISSUE TITLE
ENHANCEMENT: Can I provide a small website hosted using github pages ?

### ISSUE THREAD

**Issue by Siddhu2502** [ossu/computer-science#1199]
There is not any problem but i am very interested in providing a contribution to the community can you please approve this request if accecpted i will start on this topic immediately

**Comment by pulkitkrishna00** [comment]
We already host the curriculum using github pages: https://cs.ossu.dev. It is a simple setup which generates the page from github README. Are you proposing to make a more featured website?

In past, many alternative source for listing OSSU courses have gone unmaintained, so I don't think it is a good idea to make something that would require manual maintenance and updating whenever the curriculum is updated..
