### ISSUE TITLE
README link to Discord is outdated 

### ISSUE THREAD

**Issue by ginna-baker** [ossu/computer-science#1201]
**Problem:**
* I was not able to join the Discord, probably due to an outdated invite link in the README.md

**Duration:**
Today so far

**Proposal:**
We might need a new discord link

**Comment by waciumawanjohi** [comment]
I can't replicate the issue. Which link did you click?

**Comment by ginna-baker** [comment]
I tried both of these (the widget and the hyperlink): 

https://github.com/ossu/computer-science/blob/master/README.md?plain=1#L76

That took me here:
![Screenshot 2024-01-18 at 5 02 30 PM](https://github.com/ossu/computer-science/assets/6732956/1b99477c-6021-4295-a01b-f87f3a673b6d)

Clicking 'Accept Invite' took me here:
![Screenshot 2024-01-18 at 5 01 55 PM](https://github.com/ossu/computer-science/assets/6732956/9507d823-faa0-4f57-973f-74e1e244ef28)

**Comment by waciumawanjohi** [comment]
Hmm... I'm able to accept the invite when in an incognito window. Are you able to log into Discord and then follow the link?

**Comment by ginna-baker** [comment]
You are right.  It's because I wasn't logged into discord on this browser.  Thanks for helping me out.
