### ISSUE TITLE
google spreadsheet "OSSU CS Timeline" has small error in timeline estimate

### ISSUE THREAD

**Issue by soeren-b-c** [ossu/computer-science#1210]
The google spreadsheet located here:

https://docs.google.com/spreadsheets/d/1bkUU90y4rKYQHwY5AR2iX6iiPTrPEsYs75GkCAkrgm4

(and linked to here: https://github.com/ossu/computer-science/blob/6aea5acf571c04883234654190be468c5b56f547/README.md?plain=1#L54)

has a small error. When calculating the upper and lower bounds, at the line with the course

**Databases: Relational Databases and SQL**

the line above is skipped, so the time estimate counts backwards.

Should be simple to fix.

**Comment by waciumawanjohi** [comment]
Good eye!
Fixed.
