### ISSUE TITLE
RFC: A better theme for the OSSU CS website

### ISSUE THREAD

**Issue by pulkitkrishna00** [ossu/computer-science#1222]
**Problem:**

* OSSU CS website (https://cs.ossu.dev) currently uses a very simple light theme.

**Duration:**
1 week?

**Background:**
OSSU CS website (https://cs.ossu.dev) currently uses a very simple light theme. While it is good enough, it can be better. It is very easy to add an official github-pages theme, and it requires only 2 lines to be added to this repo. I have, after discussion with people in the discord server, created a demo with a better, dark theme. It can be seen here: https://pulkitkrishna.eu.org/computer-science.

Adding the theme provides the following benefits:

- A better looking website (IMO. I know it is a subjective thing).
- Improves accessibility of the website.
- Provides a big "View on GitHub" button on top, inviting people to look at the repo, where the RFCs are.
- Improves the syntax highlighting of code, making it more readable (for example on https://cs.ossu.dev/coursepages/intro-programming/ page)
- Maybe improve the SEO

Also, the About section of this repo, uses a custom GitHub syntax for an emoji. The syntax does not work on the website, or even in the tab title of the GitHub repo. The emoji should be removed (IMO, it is the better option), or changed to a Unicode emoji.

On a related note, PR #1192  should also be merged. The problem it fixes is very prominent on the website.

**Proposal:**
- Add the *hacker* theme. My pull request regarding this: #1223.
- Remove the emoji from the about section of GitHub.
- Merge pull request #1192.

**Alternatives:**
There can be two alternatives. First one being:
- Add the *hacker* theme. My pull request regarding this: #1223.
- Replace the custom syntax with a Unicode emoji. In that case, the website will look like this: ![](https://cdn.discordapp.com/attachments/744388736548077719/1216009405309386883/image.png?ex=65fed402&is=65ec5f02&hm=a6cbb53a21c9575ecb85e8cb825d29ea4d0d6c2d6318949a327e7e94f9b879d0&)
- Merge pull request #1192.

The second one being:
- Leave the website as it is.

<details><summary>Some additional info</summary>
<p>

I know there are probably many much better themes. I also know that there are many talented people who can probably make a very good custom OSSU website. But IMO, we should try to do something that is easily maintainable. The OSSU curriculum changes very rapidly, so manually updating the website every time the curriculum is updated is a very daunting task. Also, the curriculum should be, IMO, also easily accessible through the GitHub repo, so I think using complex static site generators is not an option.

</p>
</details>

**Comment by waciumawanjohi** [comment]
> Improves accessibility of the website.

This is a claim, but I don't see any evidence to support the claim. Accessibility is important.

I'm _very_ skeptical that the hacker theme is more accessible:
- Large firms as well as universities care about accessibility and their websites look nothing like this theme.
- Green text on black background was the default for computer text for at least a decade. The world stopped using it. That's a good sign that it's not an accessible format.
- Monospaced print is standard (and useful) in code, which is why our current codeblocks are monospaced. But for general text, variable width font is what you will find in newspapers and textbooks (again, institutions that care about the accessibility of their text).

**Comment by pulkitkrishna00** [comment]
> I'm _very_ skeptical that the hacker theme is more accessible:
> 
>     * Large firms as well as universities care about accessibility and their websites look nothing like this theme.
> 
>     * Green text on black background was the default for computer text for at least a decade. The world stopped using it. That's a good sign that it's not an accessible format.
> 
>     * Monospaced print is standard (and useful) in code, which is why our current codeblocks are monospaced. But for general text, variable width font is what you will find in newspapers and textbooks (again, institutions that care about the accessibility of their text).

When I mentioned accessibility, I did so in regard to it being a dark theme, which can help some people with vision problems. But now that you mention these issues, I agree, the theme has several issues. Closing this RFC issue.
