### ISSUE TITLE
Can you replace the course of (From Nand to Tetris)

### ISSUE THREAD

**Issue by muhammetaydin1982** [ossu/computer-science#1243]
It is given by two Israeli mentors

**Comment by waciumawanjohi** [comment]
Quoting from [OSSU's Contributing section](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md), which references our [Curricular Guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md):
> Successful critiques of the curriculum will point out ways that OSSU is failing to uphold these guidelines. Examples are:
> 
> OSSU lists a course as required when the course topics are elective in the curricular guide.
> OSSU not having a course to cover required topics from the curricular guide.
> OSSU lists multiple courses that cover the same topics when fewer courses could suffice.
> OSSU recommends a course to teach a topic, but there exists a higher quality course that covers the same material.

**Comment by ayman-soliman-1783** [comment]
I will bro, thank you very much for alerting me, god bless you.
