### ISSUE TITLE
Login with github is not working in https://ossu.firebaseapp.com/#/ 

### ISSUE THREAD

**Issue by shantanu2625** [ossu/computer-science#1261]
![Screenshot 2024-08-08 164026](https://github.com/user-attachments/assets/537c561a-ad74-4a38-b256-f3533a5ddae8)

**Comment by waciumawanjohi** [comment]
Discussed in [the FAQ](https://github.com/ossu/computer-science/blob/master/FAQ.md#why-is-the-firebase-ossu-app-different-or-broken).
