### ISSUE TITLE
RFC: Introduction to programming Discussion Link Is Broken

### ISSUE THREAD

**Issue by Mubeen-Ul-Hassan** [ossu/computer-science#1270]
**Problem:**
The discussion link to the introduction to programming is invalid.

**Duration:**
No idea

**Background:**
The link may be changed or the Discord channel is deleted. I don't know the specific reason.

**Comment by waciumawanjohi** [comment]
I'm able to follow the link to the expected channel. I suspect what is happening is that you have yet to read the welcome channel. Please do so and use the emoji to agree to abide by the code of conduct. You will then be able to see the rest of the server, including the channels for the intro to programming courses.

**Comment by Mubeen-Ul-Hassan** [comment]
> I'm able to follow the link to the expected channel. I suspect what is happening is that you have yet to read the welcome channel. Please do so and use the emoji to agree to abide by the code of conduct. You will then be able to see the rest of the server, including the channels for the intro to programming courses.

![Uploading discord.png…]()

**Comment by waciumawanjohi** [comment]
Which link are you clicking? 

> Courses | Duration | Effort | Prerequisites | Discussion
> :-- | :--: | :--: | :--: | :--:
> [Introduction to programming](coursepages/intro-programming/README.md) | 10 weeks | 10 hours/week | none | [chat](https://discord.gg/syA242Z)

https://discord.gg/syA242Z

I've verified this link.

**Comment by Mubeen-Ul-Hassan** [comment]
I have clicked on the chat in the discussion column, of Introduction to Programming but it shows me the same message **"The  invite may be expired, or you might not have permission to join."** I think you have already joined maybe that's the reason it works in your case. I have tried other links as well but they also didn't work. I have linked the articles that may help to solve this.

[Invalid Invite Links](https://support.discord.com/hc/en-us/articles/360001556852-Invalid-Invite-Links)

**Comment by waciumawanjohi** [comment]
Unclear what resolution is appropriate here. Clicking this link https://discord.gg/syA242Z in a private browser opens the following page:
<img width="499" alt="image" src="https://github.com/user-attachments/assets/8fe123c7-37a8-47c1-b875-3203cb43d946">
