### ISSUE TITLE
Computer Structure 1,2,3 can't be found

### ISSUE THREAD

**Issue by r-yin** [ossu/computer-science#1281]
**Problem:**
It looks like the link for computer structure 1, 2, 3 under [Advanced System](https://github.com/Kottans/computer-science?tab=readme-ov-file#advanced-systems) can't be opened. If possible, could you share the updated link to the course? Thank you!

**Comment by muzimuzhi** [comment]
It seems you're referring to an outdated, detached fork (https://github.com/Kottans/computer-science).

In the original "upstream" repo (https://github.com/ossu/computer-science), the links for Computation structure courses seem to work.

https://github.com/ossu/computer-science?tab=readme-ov-file#advanced-systems
> Courses | Duration | Effort | Prerequisites | Notes
> :-- | :--: | :--: | :--: | :--:
> [Computation Structures 1: Digital Circuits](https://learning.edx.org/course/course-v1:MITx+6.004.1x_3+3T2016) [alternative 1](https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/) [alternative 2](https://ocw.mit.edu/courses/6-004-computation-structures-spring-2009/) | 10 weeks | 6 hours/week | [Nand2Tetris II](https://www.coursera.org/learn/nand2tetris2) | Alternate links contain all 3 courses.
> [Computation Structures 2: Computer Architecture](https://learning.edx.org/course/course-v1:MITx+6.004.2x+3T2015) | 10 weeks | 6 hours/week | Computation Structures 1 |
> [Computation Structures 3: Computer Organization](https://learning.edx.org/course/course-v1:MITx+6.004.3x_2+1T2017) | 10 weeks | 6 hours/week | Computation Structures 2 |
>
