### ISSUE TITLE
Suggestions for OSSU improvement

### ISSUE THREAD

**Issue by ericdouglas** [ossu/computer-science#418]
Hey, friends! 

I would love to know what do you think we can do in order to improve the general experience for students. Share your thoughts with us so we can work towards a better OSSU for everyone! :tada:

Some ideas:

- Improved way to track progress - [beta](https://ossu.thinkific.com/collections)
- create a blog
- Creation of small groups to help people keep motivated
- "Hall of Fame" - some way to reward and congratulate students that finished a course
- Emphasize the importance of [PROJECTS](https://github.com/open-source-society/computer-science/blob/master/PROJECTS.md). The **true indicator** of success for us is the number of projects this file has.

All the ideas should help us to grow as a friendly and supportive community, encourage more students to join and stay with us collaborating in several ways, with projects, mentoring, writing on our blog, helping on gitter, etc.

**Comment by btke** [comment]
Dear Eric, Can you please add a section for path selection about how to choose advanced cs courses?

**Comment by lambainsaan** [comment]
I have an idea, we can add a section to every course listing, where we can see all the students who have finished that particular course and are willing to help each other, maybe as a mentor linking their email address to contact them. 

I think so in this way people who already know the stuff will have a chance to revise and fill up their missing gaps, and students who are learning will have the motivation to keep going.

**Comment by BAFurtado** [comment]
The idea (of OSSU) is fantastic! And it would work well with people (like
myseilf) who can actually finish MOOC courses, with projects and all! But,
surely a sense of community or of a class cohort, achievements and
difficulties shared would probably be very beneficial. I started off with
CS50, I am halfway and I do think that in time I wll complete many of the
courses. But, being a PhD in Economics/Geography with intermediate
experience in Python, the course is indeed tough! It is demanding all my
deepest inner self-motivation. Anyway, congrats and keep on with the
excelente work. Best,
P.S. I did make my TRELLO page as suggested. I am updating it everytime I
complete a week. Shall we have a repositor of everybody's TRELLO?

2017-07-30 3:56 GMT-03:00 Rhitik Bhatt <notifications@github.com>:

**Comment by TYRONEMICHAEL** [comment]
I am glad you mentioned CS50. Hands down one of the best MOOCS I have taken to date. Definitely tough, but wonderful you get to work with such a lower-level language like C. I found it far superior to the Intro to CS in Python.  

Anyhow I think mentoring would be hugely beneficial. I am just wondering in what capacity we could get something like that started. Any ideas?

**Comment by CamLV** [comment]
I really like the idea of adding a sense of this being a shared experience. It allows co-operative learning and adds a sense of competitiveness to the task.

**Comment by ericdouglas** [comment]
@btke yeah for sure. A good rule of thumb here IMO is that student should choose the section they like most from the previous Core sections, so if one had more fun studying `Core CS - Systems`, naturally he/she should choose to study `Advanced CS - Systems` first.

@lambainsaan excellent idea. It's a really easy but effective way to help. We can learn and study some concepts from Rust's community automation. I'll take a deep look into this topic.

Example: when a student opens an issue, s/he should put from which section/course s/he is having a problem. With this information, we will be able to respond to that issue with a bot pinging the mentors that are willing to help with such section/course.

@BAFurtado thanks for the feedback! Yeah, we definitely need help each other to succeed in this indeed hard task.

I don't think we need a repo to list Trello's board for each student. Now we have a better way to track students' progress IMO [here](https://ossu.thinkific.com/collections). Let's test it a little before update the README. The PROJECTS file is actually the right place where students can show they are progressing in the course. We need to improve README to reflect this.

@TYRONEMICHAEL maybe starting to use Medium and having a section there reflecting each section of our curriculum: `Programming` `System` etc. Mentors can write there.

**Comment by shailalias** [comment]
I want to share a Pre-Calculus course I'm finding very helpful. I started the first Calculus and quickly realized I forgot a lot of math the past few years. The course is [Arizona State University: MAT170 Precalculus](https://courses.edx.org/courses/course-v1:ASUx+MAT170x+2T2017/course/). It has an in-depth pretest to show what areas you have mastered or need to improve. Then it has short reviews for those before jumping into the Pre-Calc part. I know OSSU starts with Calculus, but I think this should be listed as a helpful extra for those needing to brush up on some math first. 

Also, the curriculum isn't clear about whether the readings have prerequisites or if they are intended to be done alongside a section. I'd appreciate some clarity.

**Comment by Selhar** [comment]
What i really miss on OSS is a sense of community. I can't see much of a reason to do projects after finishing a course, the way i see it, i'd rather move on to the next course. Currently i'm doing the "Programming languages - part A" and it's a fantastic, fantastic course, i can barely believe this is available for free, and even then i don't really feel like doing any project after finishing it up. I could put a week in doing this project, sure, but without a community, simply moving on to the haskell book is a lot more interesting to me. Maybe it's my fault for not intentionally getting involved, but maybe others feel like this too.

**Comment by mackmmiller** [comment]
Selhar,

I definitely feel the same exact way. I'm currently struggling between choosing to work on the business end and shelling out the thousands of dollars to go back to school. I'd much rather work and study this curriculum concurrently, but I can't find the motivation to stick with it on my own.

If you're interested, maybe we could work through the program together.


-Mack

**Comment by ewtwolf** [comment]
I've just started the curriculum as well. Doing CS50 and Linear Algebra at the moment, but I am also working on some webdev courses to get career ready faster. For my level, I am finding the Udacity free course, Intro to CS is a great primer. It is python based, and I like their broken up lectures with constant code challenges. Long term though I would like to complete this OSS CS work. I'm available too if anyone wants to collaborate. 

Also, I put this out there on the google group, but if anyone needs a math resource, Professor Leonard has his college lectures on [youtube](https://www.youtube.com/channel/UCoHhuummRZaIVX7bD4t2czg) and he has a great teaching style. His [google site](https://sites.google.com/site/professorleonard57/home/classes) has course syllabi.

He basically records his college lectures and posts them. He has a great teaching style and you can look up the text books he uses and follow along. He teaches through university level Calc III, however he unfortunately doesn't teach trig/precalc.

**Comment by BAFurtado** [comment]
Indeed.
I know a bit of Python. But 0 of C.

I am having a really hard time at CS50.
I was happy that 'speller' was my last C submission. But I have been on it
for more than 24 hours (in the past three weeks) without much moving ahead.

I get a segmentation fault AND pass only 5 of the 8 checks. The minimum
(for a certificate) would be 6.
Anyways,

Best,

2017-08-12 12:24 GMT-03:00 Revin <notifications@github.com>:

**Comment by coloradomountain** [comment]
I have been working on the course off an on. I stopped to learn more about Go, and Linux administration. I work on it off and on, but as others have stated the lack of social aspect is draining. 

I haven't looked at the statistics yet, but my premise a while ago was simply that the course hadn't a lot of traffic, or interest. The subreddit sees little interest, and from the time I spent on the chat in the passed it was sparse at best.

I believe I noticed a UI frontend in the works a while ago, but without a consistent userbase, what is the point?

I am more than welcome to work with others. Feel free to contact me directly, and we can talk about our progress or projects.

I love to see that there is some activity still going along in the group. I love the course, and effort behind it.

Best regards,
Ian

**Comment by ericdouglas** [comment]
What do you think about adding a section on our README suggesting students that before starting a new course they look here in our issues if someone is looking to pair in order to study along such course.

Basic example:

Before a student starts a new course:

1. Search in the issues to find a colleague and/or open an issue with the title `Looking for partner: CS50`.
1. Contact with another student to agree on how/when they will study together.
1. Create a final project together: or both implement the same idea but which one creates their one implementation, or they can both create the project together. Both approaches have pros and cons.

**Comment by Selhar** [comment]
@ericdouglas
For me, the problem with that approach is that it doesn't yet give a sense of community. For example, i don't like studying with others at all, but in freeCodeCamp i can go on the forums, ask and answer questions and engage with the community. I'm not saying a forum is the answer for OSS, but there's a contrast between a sense of community and studying in groups.

Having a place to showcase our work and help others/seek help, is what seems to be missing in OSS for me. There are many solutions for both of these problems, a forum is certainly one of them, but i can't really say which would be appropriate for OSS.

**Comment by ericdouglas** [comment]
@Selhar 

> "Having a place to showcase our work and help others"

The [PROJECTS](https://github.com/open-source-society/computer-science/blob/master/PROJECTS.md) file exists for that very reason.

You also said [here](https://github.com/open-source-society/computer-science/issues/418#issuecomment-321984331):

> "I can't see much of a reason to do projects after finishing a course, the way i see it, i'd rather move on to the next course."

So here we have a paradox. You want a place to showcase something but you don't see reasons to create a project so ... what will you show? :sweat_smile: 

About the "studying with a partner" thing, it is more related to keep both motivated and studying until they finish the course. And obviously, it won't be obligatory.

The "platform" to build/grow a community we already have IMO, a subreddit, a gitter room, to name a few.

About the "place to seek help" you said, I believe the best place to start seeking help is in the forum of the course you're taking, and "bubble up" the question to other channels as needed, sending the link to the question if possible.

The FCC is creating the content, we are aggregating content, are different approaches. For that reason, the question should "stay where it belongs" because other people besides OSSU can beneficiate of it.

**Comment by Selhar** [comment]
> So here we have a paradox. You want a place to showcase something but you don't see reasons to create a project so ... what will you show?
For me, specifically, i don't feel like doing the projects because i can't see much use to them currently. With a community, it's easier to want to showcase your work and evaluate others. Of course, this is highly subjective preference, not an imposition of "what is objectively better".

**Comment by coloradomountain** [comment]
For me it is the community aspect. OSS can list participant projects, but that seems more apt to a personal portfolio page. Perhaps a central OSS front end that displays the course information from various mood providers. Something that would unify all of the separate platforms into one interface that would display your scores, goals, etc. a platform that would allow communication between OSS participants in a more fluid manner than reddit or Slack.

As a side: I have never been fond of IRC or similar for hefty discussions. The lack of chat logging to be able to go back and forth, the lack of framework all make for poor usability in my mind.

Aggregating progress and allowing a platform to "buddy" up or become a mentor for others was my initial idea.

Communication is key, and it can be hectic when the mooc platforms often have poorly integrated discussion boards, and for me, lack of consistent detailed email notifications.

**Comment by spelga** [comment]
One of the simple things that could be done is that a platform could be given to discuss each others solutions to problems sets / projects. That way you actually get real feedback that is useful and allows you understand where you are and what needs improved. In Learning How to Learn we know that Illusions of Competence are common and being able to muddle through the first weeks of a course not uncommon until you hit something that really challenges you and you then realise that you haven't a clue. Earlier feedback would likely prevent so many dropping out of MOOCs IMHO. For me this is the bit of MOOCs that just doesn't work.

**Comment by itamargiv** [comment]
I only found this resource yesterday, and I gotta say, I am super happy to have found a repository of MOOCs that can be maintained and updated. I've been working as a web developer for a while now, but since I'm self taught, I always felt that my knowledge might not be as well rounded as my colleagues. So thank you @ericdouglas for maintaining this.

I just read through this thread and it seems like there actually is a need for some kind of UI to aggregate communications between students, and help them pair up with each other or mentors. From what I understand this UI should eventually fulfill the following criteria:

1. Enable curators to make sure everyone is seeing the latest version of the curriculum and perhaps post updates
2. Enable students to track their progress
3. Enable students to share their progress and more easily post up problem sets or projects for review
4. Provide a general forum to help students pair up and get to know the community
5. Provide a section based forum to get help in particular subjects

Granted, all of these criteria are already met in some form or another currently (via this repo, trello, reddit, google groups and gitter). But it seems like we could all benefit from a one stop shop in this respect.

I saw that there was a platform in the works at https://github.com/open-source-society/ossu-client but the repo seems to be dormant. Are there any updates on that? What was behind the decision to move to thinkific?
I might not have a lot of time, but I'd be more than happy to contribute from my XP as a web dev in order to move things along, test whatever is currently there, or come up with solutions.

On another note, I'd like to upvote the need for some resource to help students brush up on math. God knows it's been a while since I was in high school, and although I haven't started the math courses yet, I know I will need some way to dust off the cobwebs.

**Comment by coloradomountain** [comment]
Correct, consolidation. You outline concisely what I am too lazy to do.

**Comment by T-Seeker** [comment]
Hello everyone,

I am also new to OSSU and following you guys for the past couple of days. I am with itamargiv on this matter of platform.

There is one thing that I want to ask that on web UI, why there aren't any prerequisite for the courses? And some courses are missing like courses from Advanced CS.

By the way I am doing CS50 and a linear algebra, and want to collaborate with someone. Let me know if anybody wants to team up.

**Comment by LPsyCongroo** [comment]
I wouldn't say I have a ton of experience but I'd also love to help @itamargiv and anyone else make some kind of website/platform for this curriculum.

**Comment by ewtwolf** [comment]
@T-Seeker I open for teaming up. I just started CS50 and Linear Algebra too. I have a vacation coming up, from 8/26-9/12, afterwards i'll be available.

**Comment by itamargiv** [comment]
I'd still wait on a response from @ericdouglas on the decision to utilize Thinkific. Since from what I could gather from a quick peek at their platform, it just might provide use with what we need.

However, if we do decide to take the self built platform approach. I suggest that we use the outline written above as a set of progressive milestones that need to be achieved. Otherwise it could get really messy, really fast. @LPsyCongroo I'd be more than happy to get some help if that is the decision we take. The already built system is a good starting ground, so we could start opening up issues there.

@T-Seeker, @ewtwolf  I'd be happy to team up for CS50 problem set reviews, if you are interested. I only started yesterday and submitted problem set 0, but there isn't a lot to review there ;)

**Comment by ericdouglas** [comment]
Some time ago we had people contributing in order to develop such system and I realised it would be a lot of effort to create something that wouldn't be so useful, and build/maintain such system is a real effort, and all of us can quickly lose interest in the project or some crazy stuff can happen in our lives so we need to dedicate more time in other endeavors.

In that time, I said for all the contributors to stop the development of such app, and it was I real mistake on my end.

I'm more than open to invite people to our organization to build such system if they want, but personally, I don't think it'll be a big improvement over what we have now for free so I don't recommend starting such thing. But if you start, I would recommend thinking in a way that the project could be used for other communities, so it'll be an interesting open-source project for everyone interested in creating a community like ours.

I can totally be wrong in my vision, but I see alternatives to all those specs being accomplished in a much easier way:

1. *Enable curators to make sure everyone is seeing the latest version of the curriculum and perhaps post updates*. Thinkific solves this.
1. *Enable students to track their progress*. Thinkific solves this.
1. *Enable students to share their progress and more easily post up problem sets or projects for review.* For me, the PROJECTS file has this purpose, but we can improve the communication about it, create another files/repositories exclusively for it...
1. *Provide a general forum to help students pair up and get to know the community.* We can create a repository called `<course-name>-forum`, e.g. `computer-science-forum`, so people can discuss there. It'd be really helpful and it's pretty effective.
1. *Provide a section based forum to get help in particular subjects*. See solution above.

**Comment by T-Seeker** [comment]
Cool, so on which platform you guys wanna connect? I think gitter would be fine. @itamargiv, I have added you on the Trello board. @ewtwolf, could not find you on Gitter, add me when you are available there. Oh, and have a nice vacation.

**Comment by seanjun21** [comment]
@ericdouglas Actually, for your suggestion no. 2, is there any way we can track progress of OSSU through GitHub? I'm talking about those 'green-dots' on GitHub profile page when you make contribution to any repository. FreeCodeCamp has very similar setting, but theirs isn't linked to GitHub profile. Right now, I've made a README file that keep track of everything I do on CS50. It's strangely satisfying and motivating. Plus, it looks good on your GitHub profile.

If Thinkific is what you guys would like to go with, that's great. Now, if you guys would be able to connect between Thinkific and GitHub (so when you make progress, you get 'green-dots'), that would be even better. Just a minor suggestion.

**Comment by TYRONEMICHAEL** [comment]
@itamargiv I honestly found Khan Academy's linear algebra course to be much more beneficial than the edx one. I was lost by week 2, and decided to look at the Khan Academy and the concepts were covered much more clearly. 

@ericdouglas maybe we can also integrate a way of voting a program into the syllabus by people who have taken the course?

**Comment by alchermd** [comment]
May I suggest a weekly ***Ask Anything Thread*** on the [r/opensourcesociety](https://www.reddit.com/r/opensourcesociety/) subreddit? I feel like that this would help aggregate *need-help* posts and *standalone discussion threads* unto themselves.

**Comment by hanjiexi** [comment]
I think it is clear that the system we're using now (discussions spread out over many different platforms, ad hoc collaboration) has the effect of fragmenting the community. There is value (i.e. flexibility) in an ad hoc organizational style, but it just doesn't work for a whole lot of students.

Based on what I'm seeing in this thread and my experiences in MOOCs, there is also a broader problem with the current paradigm of online courses. They fail to engage with their students properly, and on some level I hope OSSU could be part of the solution rather than repeating the same mistakes.

I do think we need a more organized, centralized, formal approach. Any general-purpose solution will likely have a lot of features we don't need and lack a lot of features we want. At the same time, creating our own solution is a *big deal* and not to be taken lightly. OSSU's curriculums will always be works in progress that impose constantly changing requirements on the developers of any platform we create. (But this is our advantage — we can reinvent ourselves much faster than a real university can.)

So I think what we need right now is a **roadmap** that describes what we are focusing on improving right now for the sake of current students, and what we will work on in the future. That way, we can all agree to work on temporary solutions while knowing that something better is in the pipeline.

By the way, I think we are under-utilizing the [Wiki](https://github.com/open-source-society/computer-science/wiki). It could come in handy for some of the things we are discussing here.

**Comment by alchermd** [comment]
Google updated their [developers guide](https://techdevguide.withgoogle.com/).

**Comment by agilvarry** [comment]
I think it is worth including Kahn Academy for all Math, at least as a supplement if not a complete replacement for everything. I did think the Single Variable Calc courses were quite well done and would easily suggest them to anyone learning Calculus, but I'm getting lost in the linear algebra course like @TYRONEMICHAEL and may move over to kahn academy if the material there is better.

**Comment by T-Seeker** [comment]
@agilvarry True, linear algebra for Khan Academy is great for visualization of vectors and their concepts. I think that these lessons should be added to the curriculum along with LAFF.

**Comment by agilvarry** [comment]
The youtube series [Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) does a really good job of explaining some concepts that I felt the LAFF course didn't do a great job of. I stumbled on it at https://teachyourselfcs.com/, which recommends several of the same resources as OSSU. Notably, they also recommend [this descrete math book](http://www.cs.elte.hu/~lovasz/dmbook.ps) along with the MIT course OSSU.

**Comment by jeanleonino** [comment]
Looks like no one talked about this anywhere, so here it goes:

* Alumni - is there a group, should we do one?
* Recognition on Linkedin like FreeCodeCamp has.

**Comment by ericdouglas** [comment]
@jeanleonino thanks, it is indeed a great thing to have (alumni).

About the Linkedin, I just sent a request for it, let's wait for their response.

---

For everyone following this issue and for everyone that commented here, I have a **great news** :tada: 

We clearly have a great project here, but we all know we can do a lot better to improve the overall experience for students.

But it's something that demands a lot of time, and the solution to address all points listed here for us is to build our own platform, and that's what I'll put my energy for the next months/years.

Long story short - OSSU next steps:

- OSSU will become a nonprofit company, following a manifesto created for replicability of such endeavors, enforcing transparency, equality, and a bunch of cool points that I'll let you know soon
- We will create an open-source platform addressing all points listed here and you can now be much more rigorous on requirements
- We will invite course creators to host their content on our own platform, so no need to register in several different places
- Soon we will start a crowdfunding campaign to have resources to build the platform
- Inside the platform we will have a lot of features to help students to succeed, finishing the courses
- OSSU will always provide only complete learning paths, always **for free**
- We will educate people about micro donations, not only for us but for all open-source projects they use. It'll be addressed in the manifesto. That's how the project will have sustainability. We can also have job boards and other ways to create revenue, but obviously, the content will **always be free**.

Well, there are much more for sure.

Now, the only thing I ask for you all is to say **everything** you wish OSSU should have. Let's make a true brainstorming here so our ideas can be merged to create a great platform not only for our specific project but for the world :)

I just bought the domain **ossu.io** for us ;D

**Comment by ericdouglas** [comment]
I received the reply from Linkedin:

```
Dear Eric,
 
Thanks for the email!
 
I'm not showing that any degree is offered by Open Source Society University
at https://github.com/open-source-society
 
Due to this, we cannot change the company page into a university page.
```

```
Dear Eric,
 
Thanks for the reply!
 
My apologies but you do not offer an accredited degree that I'm able to find.
```

So we should now think in a way to have a certificate/degree for our courses.

What comes to my mind is:

- Students can request a degree after creating one _project*_ for each resource in the curriculum.

Project = program, article, book, etc.

Those projects will be evaluated and after it, the student will receive the certificate.

**Comment by alchermd** [comment]
@ericdouglas Sounds awesome. It looks like OSSU is heading to the same path as FreeCodeCamp?

> So we should now think in a way to have a certificate/degree for our courses.

I have a FreeCodeCamp certificate under my belt, and I'd suggest adding a mandatory peer-review on the project submitted by the students. As it stands with the current system on FCC, a student just needs to pass a URL of their work and they get the certificate immediately. There's not really a lot of room for feedback unless the student seeks one on his/her own. For starters, maybe projects should be submitted as issues and a "panel" of 2-3 people give their take on the project at hand. Or maybe a much cleaner system within the platform planned in the future.

Don't get me wrong: personal will to search for feedback and criticism should be a core value for anyone in this field. But integrating it within the system makes the whole thing more transparent.

**Comment by ericdouglas** [comment]
@alchermd kind of. Actually, our platform will be agnostic so in theory FCC will be able to run inside OSSU platform in different ways. 

1. They can run the platform on their servers since it'll be open source.
1. They can run on our servers, but using their own domain.
1. They can create a learning path inside our domain, e.g: `ossu.io/freecodecamp`

> I have a FreeCodeCamp certificate under my belt, and I'd suggest adding a mandatory peer-review on the project submitted by the students.

Yes! I totally agree with it. I'm thinking about a system where students earn "points/coins" by helping other students (reviewing projects, answering questions, mentoring, etc) and those points can be exchanged by educational resources or to unlock some special features. But peer review will be a must for sure. Feedback is something **really** important while learning something new.

**Comment by ericdouglas** [comment]
**We now have a [university page](https://www.linkedin.com/school/11272443/) on Linkedin** :tada: :tada: :tada: 

You can add OSSU on your profile now!

I sent another request and now they approved it!

**Comment by alwongg** [comment]
This is something really awesome. Learning computer science itself is a very difficult and long journey, especially going through the OSSU curriculum through credible institutions like Harvard and Stanford. Yet, I feel like the curriculum is not getting any recognition and employers don't really take it seriously. But as OSSU becomes more its own organization such as having its own website (ossu.io :D) and now recognized on linkedin, I believe Computer Science education will become a lot more accessible! I'll be happy to help out building the website or even create an iOS app for it, or any other tasks, let me know!

**Comment by ericdouglas** [comment]
@alwongg I really appreciate your feedback, many thanks.

Yes, it's a very challenge journey but can certainly be a very interesting one if students have the opportunity to build cool things for each step.

Other things we can think as a next step are:

- Create our own content, so it'll match exactly with our philosophy
- Provide a valid/recognized degree for students that complete the curriculum.

**Comment by ericdouglas** [comment]
Our organization's URL is now `https://github.com/ossu` so it will be the same of our domain and also with our current "brand":  *Open Source Society University*. Since we will focus on educational initiatives, it's a more consistent approach.

**Comment by jeanleonino** [comment]
@ericdouglas awesome, thanks for the LinkedIn feedback and new request. 

About the alumni, is there anything that can be started now? What else can be helped?

**Comment by ericdouglas** [comment]
@jeanleonino yes, let's discuss it [here](https://github.com/ossu/roadmap/issues/4).

Let's continue all discussion about OSSU (organization) improvement there.

I'll close this issue for now since it is not related anymore to this specific course (computer science).

But if anyone has a suggestion to improve the CS course, feel free to open an issue and start a discussion like the other we have right now.

For those interested in the future of OSSU, and interested to help on it in any way, I encourage you to watch the [roadmap](https://github.com/ossu/roadmap) repository.

Thank you so much for all you that commented here, we got a lot of good ideas that will really improve the overall experience for OSSU students. :heart:

**Comment by ericdouglas** [comment]
We're now on [Patreon](https://www.patreon.com/ossu). Help us to offer high-quality education for free to everyone! :tada:

**Comment by ericdouglas** [comment]
[OSSU newsletter](https://tinyletter.com/ossu)
