### ISSUE TITLE
Introduction to Mathematical Thinking; prereq and placement

### ISSUE THREAD

**Issue by NicholasDM** [ossu/computer-science#420]
Hi!

This issue is concerning the course _Introduction to Mathematical Thinking_, currently listed under Advanced Math. A link to the course is here: https://www.coursera.org/learn/mathematical-thinking

It's really a minor detail. The OSSU course list lists pre-calculus as a prerequisite. I'm currently enrolled in the course, and it is explicitly stated that the course has no prerequisites. Instead, it focuses on logic theory, set theory-- the foundational theories that mathematics is derived from.

This course is more a pre-college introductory course, to be taken before college algebra, for example, and to heavily improve the student's understanding of mathematics from a foundation level.

---

On that note, but this isn't something I would be sure about. The course list may benefit from moving it from Advanced Math to Core Math. As mentioned, it's intended as a pre-college course (or a remedial course, as most colleges have it listed under.) Being able to reason mathematically and understand reasonings for it, while not critical to the study of the other ones in Core Math, is highly, highly beneficial. In a university, this course would come before them-- and the completion of it then instead of later would greatly improve a student's understanding of the math that comes from other math courses, like calculus, linear algebra, those sorts of things.

Thank you for your time in reading this issue, and have a great day!

(Note: I read the 'contributing' guidelines, and believe that opening as issue for this was appropriate, as they stated. However, it also doesn't seem to be standard, as there are few open issues. I apologise if it was inappropriate for me to do so, and if it was, feel free to close the issue!)

**Comment by waciumawanjohi** [comment]
Have you read the previous discussion on this topic? I'm interested in your thoughts in relation to the current justification for its placement.
https://github.com/open-source-society/computer-science/issues/396

**Comment by NicholasDM** [comment]
I had not. Now that I've had, I'd say that-- should it not be in the Core Math, it should be in the 'extras' section. The course would be like a 'Learning How to Learn' course, but for mathematics instead of just general.

**Comment by waciumawanjohi** [comment]
Caveat, I have not taken this course yet. If it were to stay in the main curriculum, I'm wondering if it should be in Advanced Theory. In particular, you stated that it covers intro set theory and logic. The first course of Advanced Theory is _Introduction to Logic_, whose prerequisite is set theory.

That said

1. I agree with you that this course does not appear to be a pre-requisite for the other math courses.
2. _CS for Math_ covers some set theory. It's unclear to me how much farther _Introduction to Mathematical Thinking_ goes. What's your experience there?
3. @hanjiexi has argued convincingly that [OSSU should look to trim out unneeded math content from the curriculum](https://github.com/open-source-society/computer-science/issues/399#issuecomment-297397012).
4. The **Who this course is for** makes a poor case for including it in the curriculum. _First, people who want to develop or improve mathematics-based, analytic thinking for professional or general life purposes. Second, high school seniors contemplating a mathematics or math-related major at college or university, or first-year students at college or university who are thinking of majoring in mathematics or a math-dependent subject._ Perhaps someone else can make a stronger case?

**Comment by hanjiexi** [comment]
I believe there is a chance that this course could be a valuable addition to Core CS, but I wasn't sufficiently convinced in time for the release of curriculum v7.

The curriculum needs to cover the following topics:
- Logic
- Set theory
- Number theory
- Graph theory

MIT Mathematics for Computer Science [covers the basics](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/syllabus/) of the four topics above, along with a few other courses which touch on those topics. (I would *like* the curriculum to cover category theory as well, but I'm unable to find any courses for that.) It's not the easiest course for studying these topics -- I've heard it's quite challenging -- but it is the best I'm aware of.

So the question becomes: does Stanford Introduction to Mathematical Thinking, in spite of having some similar content to Math for CS, provide sufficient value to justify adding another course to Core?

I would say that it would provide sufficient value if it helps the student to create the intermediary *mental representations* that are needed for making the leap from high school math (which I called "pre-calculus" in the pre-requisites) to the challenging content of the Core Math courses. I don't have time to take the course myself anytime soon, so I have to rely on feedback from others, particularly those who have finished both Intro to Mathematical Thinking as well as Math for CS.

**Comment by waciumawanjohi** [comment]
@hanjiexi , What do you think of @NicholasDM 's proposal to move the course into **Extras**? I have to say, it's the one math course on the curriculum that I decided to skip. You've laid out why it doesn't fit into **Core Math** and Nicholas described why it doesn't fit in **Advanced Math**.

My other proposal was to place it in **Advanced Theory**. But that's really on the assumption that it's a high impact course with something to offer that the rest of the curriculum doesn't provide. That doesn't seem to be the case.

[Ratings for the course on Class Central](https://www.class-central.com/mooc/370/coursera-introduction-to-mathematical-thinking) are good. But the reviews don't suggest the class will bring value for the OSSU curriculum. Most students say that the course taught them to write proofs. Students in _Math for CS_ should already have done so.

I can't find a single comment on the Gitter about _Intro to Math Thinking_, suggesting that many people are deciding to skip it. The few conversations that discuss readiness for _Math for CS_ are students that were concerned about whether to take calculus first (before v7 of the curriculum). No one has posted with concerns about needing a slower or fuller introduction to proofs.

Based on all of this, I think _Intro to Math Thinking_ should move into **Extras**.

**Comment by hanjiexi** [comment]
As much as I'm reluctant to move such an acclaimed course to extras, you make a convincing case — if it's only covering material that's already covered elsewhere, then according to how things are structured right now, extras is where it belongs.

The next minor OSSU CS update will implement this change. However I'm leaving it under Math rather than putting it into Theory; for v8 of the curriculum I want to refine the category names and "Math" will probably end up being called "Logic and Math" or similar.
