### ISSUE TITLE
Re-organization roadmap for OSSU CS

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#422]
Continuing discussion from #421 and #418. Will add my thoughts later.

**Comment by chrisdziewa** [comment]
I just want to offer some feedback. I believe that the Software Construction courses from UBC are severely lacking in effectiveness. The first one varied between good and mediocre. The second is literally one of the worst learning experiences I've ever had. The instructors race through topics and somehow expect students to understand the advanced use cases of the patterns they barely explained. Then to make matters worse, they expect students to have an insane command over Java to complete the final project with requirements nowhere near reflecting that of the poor instruction given. As someone who has programmed for years in many different languages, I have to believe there is a better course offering available.

**Comment by hanjiexi** [comment]
I appreciate this feedback. I have mixed feelings about UBC Software
Construction.

I will start with the positive: the course exists for a good reason, which
is to expose students to the painful reality of trying to be productive in
an unfamiliar codebase written in an unfamiliar language that favors a
convoluted coding style. Feeling a little overwhelmed is part of that
experience.

What I don't like is that "making students feel overwhelmed" (on purpose)
is not really relevant to a computer science education. It's more like job
training, which should be done by companies, not by us.

What would be relevant is an in depth analysis of (1) the semantics of
object oriented programming; (2) the design process for large-scale
software, where decisions are made about the types needed by the system.

(1) is needed because traditional object-oriented programming is
complicated to describe mathematically, which in practice leads to lots of
indirection and makes it difficult to reason about. But, it is very common
and useful in some scenarios, so it needs to be understood.

(2) is needed because students of CS, regardless of whether they will go on
to be industrial programmers, should develop a robust understanding of how
to scale the systematic design process (learned in the "How to Code"
series) beyond a single module.

The Programming Languages course (mostly Part C, if I remember correctly)
goes into some greater depth on the design process, but still only on the
level of a single module (i.e. the types of functions: parametric
polymorphism vs. subtyping polymorphism). We need the same thing applied to
a system of cooperating modules, discussed explicitly and systematically.

All of this is to say that I want to replace Software Construction, and
there are many options for doing so superficially. At least one of the
alternatives I remember trying out was just as bad (I think it was the UC
San Diego Java course). But if we're just doing a superficial replacement,
it's not clear what the benefit will be.

I have so far not found what I'm looking for. That's why I want us to
design our own courses using publicly available materials (e.g. academic
papers) as sources. But this is a supermassive undertaking...

**Comment by chrisdziewa** [comment]
Thank you for your response! I really wanted to like the courses because I thought the approach was unique and because the subject matter was interesting and important. It seems that the course suffers from poor execution. Perhaps they were a bit overambitious to try to cover so much in such a short time frame. 

Having control over course content creation would be awesome. It reminds me of what free code camp has achieved. But yes, definitely a massive undertaking requiring massive support. 

Hope to see this project gain more traction because it is awesome so far.

**Comment by hanjiexi** [comment]
@andrewtcooper I'm enrolled in Software Constructio but I didn't get an email about that, and I can't find any notice within the course about a price increase to $9. Where are you getting that information?

**Comment by andrewtcooper** [comment]
@hanjiexi I should have clarified, the Data Abstraction course is still free (for now) but the Object Oriented Design course is now showing as costing $9 to audit. There are other courses in the OSSU curriculum that are also now showing as costing $9 to audit, but I can't remember which ones off the top of my head.  See screenshot: https://imgur.com/HMKVaos

**Comment by fractalbach** [comment]
@hanijiexi 

A couple ideas I think should be pursued:

* Online and offline: ... students could meet in physical study groups ...
* Formal organizational structure
* Mentor system
* More active, less passive cirriculum (always a good thing)

I also think it's important to increase communication between students on similar pathways. There could be a system designed specifically for the purpose of grouping people together, and prompting their communication.

Even in online courses for actual credit, online chatter can be low unless it's prompted.  I think some icebreakers might be needed :). Anything to rally people together would be a step in the right direction IMO.


On a side note, 
I think more programming languages is better than one.  How can you find your favorite musical instrument if you only try one?  Why force everyone to use only a Swiss army knife to build everything? 
Metaphors aside, might be more worthwhile to spend time on the other great ideas you have !

**Comment by ahmadshalabi** [comment]
Thank you all to your effort that make such thing exist.

I have two question: 
1- How can I helping you?
2- When you will to finish the v9?
