### ISSUE TITLE
Show certifications where available

### ISSUE THREAD

**Issue by alwongg** [ossu/computer-science#424]
I understand the mission of OSSU is to provide high-quality education at essentially no cost and that at the end of the day, certificates may not really do much if the person is unable to perform technically. With that in mind, I just wanted to see if we can show what the "paid" options can get you once you finish those courses. It will be great motivators and also show your achievements! Of course, these are evident once students dig into each course, but why not show it in the repo as well?

A simple example would be courses through edX that offers a certificate for $50 upon completion or a more complex one is the Software Development MicroMasters program when people are doing the "Core programming" section. You're already doing all 6 courses from that MicroMasters program, why not earn that "credential" while doing them? Showcasing these options somewhere in the repo may motivate students and let them know that "oh, while I'm completing these courses, I can still get some credit for them". Just a suggestion, let me know what you guys think?

**Comment by sonofborge** [comment]
I think this is an idea worth exploring.  There certainly can be real value for some students that pursue these "paid" offerings.  I wonder though, if OSSU started to showcase those options, at what point does the project start to become an advertisement for, to take your example, edX?

On the one hand, as a student, it might be nice to know more about the "paid" options and what sort of potential benefits have been shown to be tied to those achievements.  On the other hand, is that information easy enough to find in the marketing material for edX, Coursera, and the others that it doesn't need to exist here too?  And by highlighting the paid options, might it distract from the underlying mission of OSSU?

I very recently discovered this project and know next to nothing about where the maintainers are interested in taking it, so perhaps this is something they want to do.  Just thought I'd put in my $0.02, fwiw.  Cheers!

**Comment by ericdouglas** [comment]
@alwongg thanks for bringing this topic for discussion. I just updated our short-term goals on [patreon](https://www.patreon.com/ossu) adding these goals: 

- Certificate for students that finish a course + build a project
- Place to list all students' achievements motivating them to complete all courses

Do you think such "features" solve the point you are talking?

**Comment by alwongg** [comment]
I believe it does. As long as students are aware of certificates that are available from edX or coursera, which will provide some credibility and motivation. In addition, thoughts on career services and most importantly, a technical interview section? One that resembles this: https://github.com/jwasham/coding-interview-university#why-use-it.
After finishing the CS curriculum, students can be guided towards a section that will provide career tips and help but also have a section that provides students with what they should be doing daily to improve their technical skills to apply for the big companies like Google and Facebook (just like the coding interview university repo linked above).

Anyways, just wanted to suggest these to OSSU. I am a strong believer that OSSU will become a crucial part in obtaining a CS education in the future and if there's anything I can contribute and help out, I'll be glad to. If there is a future plan in creating an iOS app for OSSU as well, count me in!

**Comment by ericdouglas** [comment]
@alwongg great suggestions, we definitely should think about this.

We surely will need your help. You can watch [this](https://github.com/ossu/roadmap/issues) repository to see our [roadmap](https://github.com/ossu/roadmap/projects/1).
