### ISSUE TITLE
Algorithms: Design and Analysis, Part 2  on Stanford Lagunita

### ISSUE THREAD

**Issue by zlatin** [ossu/computer-science#428]
Looks like with [Algorithms: Design and Analysis, Part 2](https://lagunita.stanford.edu/courses/course-v1:Engineering+Algorithms2+SelfPaced/about) we can finish algorithms topic completly free on Lagunita and even receive a Statement of Accomplishment.

**Comment by hanjiexi** [comment]
Nice find! I'll incorporate this into the next update, which is being staged in the [dev branch](https://github.com/ossu/computer-science/tree/dev).
