### ISSUE TITLE
Final course of Advanced Systems duplicates content of reading from Core Systems

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#433]
Core Systems includes a two-part Computer Systems class (Nand2Tetris), a networking course (Stanford's Intro to Computer Networking) and reading a required textbook (Three Easy Pieces).

The textbook teaches operating systems.

- From OSS: "...Nand2Tetris does not go deep enough into operating systems..."
- From Three Easy Pieces: "The book is centered around three conceptual pieces that are fundamental to operating systems: virtualization, concurrency, and persistence. In understanding the conceptual, you will also learn the practical, including how an operating system does things like schedule the CPU, manage memory, and store files persistently."

The final course of Advanced Systems is ops-class.org. This class (Hack the Kernel) "includes everything you need to learn about operating systems online." The course introduction lists the conceptual progression as:

- Introduction to operating system abstractions and structure.

- Abstracting and multiplexing:

    - the CPU—​interrupts, context, threads, processes, processor scheduling, thread synchronization.

    - memory—​memory layout, address translation, paging and segmentation, address spaces, translation caching, page fault handling, page eviction,

    - swapping.

    - storage—​spinning disks and Flash, spinning disk scheduling, on-disk layout, files, buffer cache, crash and recovery.

- Virtualization.

- Networking (time permitting)

The course textbook is Modern Operating Systems by Andrew Tanenbaum. This is an introductory operating system textbook. It is often compared to Three Easy Pieces.

One of these should be moved to Extras. Previous discussions have affirmed OSS's commitment to resources which provide feedback. By this criteria, **_Hack the Kernel_ should stay in the required curriculum and _Three Easy Pieces_ should be made optional.**

The next question becomes, should Hack the Kernel stay in Advanced Systems or move to Core Systems? The new [ABET](https://en.wikipedia.org/wiki/ABET) program [criteria for computing programs](http://www.abet.org/wp-content/uploads/2017/08/CAC-Criteria-Version-2.0-2018-193221.pdf) specifies:

- Exposure to computer architecture and organization, information management, networking and communication, operating systems, and parallel and distributed computing

As all students must be exposed to operating systems, **Hack the Kernel should be moved to Core Systems.**

I will note that I like Three Easy Pieces (you can actually find me in one of the textbook's endnotes). I think **a note should be added to Core Systems that we recommend reading Three Easy Pieces as a textbook for Hack the Kernel rather than Modern Operating Systems**. Reasoning: Three Easy Pieces has higher ratings on Goodreads and on Amazon than Modern Operating Systems. It is available free online. Recommending it reaffirms the earlier judgement of OSS.

**Comment by hanjiexi** [comment]
Thank you for the PR, and your reasoning is solid. Now that operating systems is updated, I just need to take care of any hanging issues (#428 is the only one left if I remember correctly), and then I think we'll be ready for v8.
