### ISSUE TITLE
Algorithms: Design and Analysis Vs. Algorithm Specialization on Coursera

### ISSUE THREAD

**Issue by alwongg** [ossu/computer-science#436]
Hello, 

The curriculum previously used Coursera's Algorithm Specialization (https://www.coursera.org/specializations/algorithms) but now it uses from the Stanford website here (https://lagunita.stanford.edu/courses/course-v1:Engineering+Algorithms1+SelfPaced/about).

I know this has been mentioned about the difference but forgot and can't find it now. So my question is what is the difference between the two? They're essentially the same thing correct? Why might one take one over the other?

Thank you.

**Comment by Nixerrr** [comment]
If I understand correctly, only part 1 used to be available on the Lagunita site, which was basically courses 1 and 2 of the Coursera specialization, but recently[ they've added part 2](https://github.com/ossu/computer-science/issues/428) as well which is the equivalent of courses 3 and 4. So now you can do the whole thing on Lagunita without Coursera nagging you to pay.

**Comment by hanjiexi** [comment]
Nixerrr is correct; nothing has changed except the platform hosting the course.
