### ISSUE TITLE
in what order can i take this course 

### ISSUE THREAD

**Issue by oussamabooss** [ossu/computer-science#439]
i saw the answer here
https://github.com/ossu/computer-science/blob/master/FAQ.md#in-what-order-should-i-take-the-courses
but i didn't find the designed orders of you 
please help me 
and thank you for the great work

**Comment by amorriscode** [comment]
@oussamabooss You can take the course one of three ways.

1. Take the course in order from top to bottom
Ex. Start at *Intro To Computer Science*, take the two courses in that section, then move on to *Core CS/Core Programming*. Continue linearly down the page until you get to the end.

2. Take the courses linearly, but do multiple sections at a time.
Ex. Take one class from *Into To Computer Science*, one class from *Core CS/Core Programming*, one class from *Core CS/Core Math*, etc. Do this until you have completed every course.

3. Come up with your own progression.
Ex. If you have pre-requisites or have already taken some courses, skip them and do the courses _after_ them. This one is very open ended and totally up to you.

Hopefully that helps, if you have any questions about what I have said, let me know.

**Comment by oussamabooss** [comment]
thanks man 
that was helpful
but i thought there is like a schedule like the universities's that can guide me through the course till the end
 but never mind i will take it from top to bottom "i mean the course" ( lol)
thanks again
