### ISSUE TITLE
Discrete Mathematics alternatives

### ISSUE THREAD

**Issue by raialok** [ossu/computer-science#441]
I have found this free, interactive textbook on Discrete Mathematics (http://discrete.openmathbooks.org/home.php) with 363 exercises, including 233 with answers or full solutions very useful. 

It could be used as a replacement for MIT course or at least added as an alternative resource.

**Comment by hanjiexi** [comment]
Thank you! I haven't had a chance to review this resource yet but I'm sure we'll be able to utilize it somehow.

**Comment by kishvanchee** [comment]
How does this book, and/or the MIT course (and their book) compare to the book by Rosen?

**Comment by hanjiexi** [comment]
@raialok I added this to extras/readings since we already have an alternative resource for discrete math. Thanks again!
