### ISSUE TITLE
Merge with https://github.com/learn-anything/

### ISSUE THREAD

**Issue by lulucca12** [ossu/computer-science#444]
This project could be easily merged with learn-anything.

**Comment by hanjiexi** [comment]
I'm not familiar with this but I looked at their website and found it a bit confusing. Can you explain what it would mean to merge with them?

**Comment by xindekai** [comment]
I have just joined github because of the program outlined here as OSSU computer science. For me I either would not have found it in learn-anything, nor found it anywhere as appealing as it currently stands. Just the opinion of someone actually attracted to and starting the program. OSSU is cool. Thanks.

**Comment by lulucca12** [comment]
I would like the project continue as own, but part of it's content now merged with the learn-anything database, as their project is about concentrating knowledge and finding the easiest path to learning something, in this case CS.

**Comment by xindekai** [comment]
humans, tv-series, youtube, reddit and so on... this "learn-anything" is choked with everything and anything. OSSU cs should not be in anyway associated with that project in my opinion.

**Comment by hanjiexi** [comment]
I'm going to close this for now as I think it will add management overhead to keep our content in sync with that other project. Although our material is pretty stable for now, there could be big changes coming in the future and it could get really annoying to have other websites/organizations depending on us for a stable curriculum.

Of course, there is nothing stopping learn-anything from simply adding content from our list into their own website independent of us.
