### ISSUE TITLE
Algorithmic Design and Techniques MicroMasters

### ISSUE THREAD

**Issue by Nixerrr** [ossu/computer-science#451]
So here's a game changer. UC San Diego is launching a new edX MicroMasters program titled Algorithmic Design and Techniques: https://www.edx.org/course/algorithmic-design-techniques-uc-san-diegox-algs200x 

Looks promising - might be worth adding to the extras.

**Comment by hanjiexi** [comment]
This does look really neat! Thanks for pointing it out. I wonder if it would even be appropriate as a replacement for our current algorithms course... will have to look into it.

**Comment by netship02** [comment]
https://www.coursera.org/specializations/data-structures-algorithms 
This seems same as edx

**Comment by xindekai** [comment]
great catch netship02. the Coursera pricing is much nicer than EdX if someone wanted to pay for verification...

**Comment by shailalias** [comment]
Does the Coursera offer a free version though? I'm only see a free 7 day trial.

**Comment by waciumawanjohi** [comment]
OSS currently has an Algorithms recommendation. It's a free 2 course series from Stanford. (It used to be a 4 course series on Coursera) If cost is the rubric, the curriculum is better as it is now.

I'd be interested to hear if there are deficiencies in the Stanford series that the UCSD series addresses.

**Comment by xindekai** [comment]
That's a good and fair point waciumawanjohi. I am only just starting my OSSU program and still a long way from tackling those courses.

The thing I wanted to emphasise is that Coursera pricing for validated certificates, and hence the packaged courses or "specialisations", is way more cost effective and less of a barrier to many, including myself. This is true in comparison to both EdX and Udacity for example. Only people who want some validated certificates as part of their study would care about this and obviously it means "not free".

**Comment by hanjiexi** [comment]
Closing since we already have the Coursera version in extras/courses; can be re-opened later if Stanford Algorithms is found to have severe deficiencies.
