### ISSUE TITLE
What does OBS mean?

### ISSUE THREAD

**Issue by FlorianHoornaar** [ossu/computer-science#453]
Under the section Core Programming I read the following:
> OBS: probably the best resource to learn Haskell: Haskell Programming from First Principles 

I could be me (wouldn't be the first time, and I'm not from the US)... what does OBS stand for? I guess it's an abbreviation?

**Comment by mappuji** [comment]
I think it is Open Build Service http://openbuildservice.org/help/

**Comment by FlorianHoornaar** [comment]
Open Build Service and Haskell don't seem related. At least not in the context of the reading recommendation. Right?

**Comment by hanjiexi** [comment]
I haven't seen the abbreviation used much but I believe it means *observa*, which means "take note / observe".

**Comment by rkma** [comment]
@hanjiexi is right. It could be changed to "Note:" or something else. "OBS:" is common em portuguese which is the author's native language. It means _observation_, something to take note of.
