### ISSUE TITLE
no data structures course?

### ISSUE THREAD

**Issue by DavidScales** [ossu/computer-science#458]
Sorry if this is a FAQ, but I didn't see any recent bugs about it. 

I've been researching online CS curriculums and came across this one (which is awesome).

I've seen consistently that CS curriculums usually have the first few courses in the program as:
* Intro to programming (often multiple courses)
* Discrete structures/math
* Data structures 
* Algorithms

I noticed that there is no explicit Data Structures course in this program. I see that the suggested Algorithms course briefly touches on data structures, but doesn't seem like an entire course worth of material. 

I also see that the Core Programming stuff has some content on data abstraction but I'm not sure if thats the same idea as data structures (I'm actually not really sure what the Core Programming content maps to in a University curriculum?). 

I'm sure you all have considered the content for this program a lot so apologies if I'm being critical! Is there something I'm missing or is this just a design decision? (I program but don't have a CS background). Thanks!

**Comment by waciumawanjohi** [comment]
You can see here the ["About the Course" video](https://youtu.be/F-WS73Y_RU4?t=11s) from the Algorithms course recommended by OSS. As you can see, **use and implementation of data structures** is one of the explicit learning goals.

Of course, students are welcome to supplement the curriculum with extra study. I enjoyed the [Princeton Algorithms course](https://www.coursera.org/learn/algorithms-part1) which focuses more on programming your own version of many basic data structures.

As to whether the Stanford course meets the reqs of a university CS degree, you can see the [course requirements for Stanford's CS degree](https://cs.stanford.edu/degrees/ug/Requirements.shtml). One course, CS161, addresses the expectations for Data Structure and Algorithm study. This is the course that Roughgarden's MOOC (the course we recommend) grew out of.

**Comment by DavidScales** [comment]
Okay SGTM, I just wanted to confirm because it wasn't obvious to me based on my (limited) knowledge of the scope of CS topics. 

If I could pester you with a follow up (I can move this to another bug if that's best), what do the [OSS core programming](https://github.com/ossu/computer-science#core-cs) courses map to in a University program like the [Standford one](https://cs.stanford.edu/degrees/ug/Requirements.shtml) that you've mentioned? 

It looks like core programming involves nearly 9 months of study, which would map to multiple courses - maybe something like "software engineering I & II" and/or a "programming languages" course? 

The core programming section is a bit of a mental barrier for me because its such a large time commitment and I can't yet see where it fits.

Thanks for your time

**Comment by waciumawanjohi** [comment]
David,
I think you're right that this belongs in its own issue. You've hit on a genuine curricular question, to what extent should OSS recommend programming in different paradigms? It's a discussion worth having.

**Comment by DavidScales** [comment]
Cool, I've moved this thread to #462. Thanks!
