### ISSUE TITLE
The Place of Reliable Distributed Systems

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#459]
These courses are currently in Advanced Theory. While they do address "theory and practice of distributed algorithms for designing scalable, reliable services" they seem to be the most practical and applied of all the courses in the theory track. It's not clear that any theory learned in these courses could apply outside of their topic area (as opposed to a theory course like Logic, which has broad connections to a variety of disciplines within and without computer science).

This course seems more appropriate for Advanced Systems.

1. It's unquestionably a systems course
2. A student who completes OSS in Advanced Systems today would never move beyond studying systems on a single computer, a serious problem in an era of distributed computing and server farms.

We should also note that Reliable Distributed Systems I is currently not available (not even as an archived course). Reliable Distributed Systems II is still available, so perhaps another run of the course is coming.

I propose that Reliable Distributed Systems I and II be moved to Advanced Systems and that we revisit them in the summer. If no new session is planned, a replacement course should be determined.

**Comment by hanjiexi** [comment]
We should look at that Java course I mentioned in #449 since part 1 of this course might not be coming back. If part 2 were unavailable, it wouldn't matter as much, but it's a problem if part 1 isn't available.

**Comment by hanjiexi** [comment]
Sorry I should have been more clear. I was referring to the [third course](https://www.coursera.org/learn/distributed-programming-in-java) in the "Parallel, Concurrent, and Distributed Programming in Java" specialization:
- Distributed map-reduce programming in Java using the Hadoop and Spark frameworks
- Client-server programming using Java's Socket and Remote Method Invocation (RMI) interfaces
- Message-passing programming in Java using the Message Passing Interface (MPI)
- Approaches to combine distribution with multithreading, including processes and threads, distributed actors, and reactive programming

That description makes it sound like a lot of "here's how you use APIs for distributed computing in Java" stuff, whereas my preference for a course is "here's the *essence* of the theory of distributed computation, now let's demonstrate it in the real world using Java". But that's just an impression.

**Comment by waciumawanjohi** [comment]
Ah, that makes more sense.
This also looks like a candidate course: [Cloud Computing Concepts](https://www.coursera.org/learn/cloud-computing)
The course description emphasizes its theoretical angle. Similar course rating on Coursera to the Java course, though this course has been taken by 5 times as many students. It looks like it's part of part of  University of Illinois at Urbana-Champaign's Master of Computer Science in Data Science.

**Comment by hanjiexi** [comment]
Interesting. The course name makes it sound really shallow so I probably never even looked at the course description before. It's not ideal that C++ would have to be a prerequisite, but other than that it sounds closer to what I would be looking for.

On the other hand, if those Java courses do cover the concepts sufficiently well, we could require all three of them to get Concurrency, Distributed, and Parallel covered very cleanly, and we wouldn't have to worry about the prerequisite since students should have already completed Software Construction.

**Comment by waciumawanjohi** [comment]
I've created an RFC to move Distributed Systems to Extras/Courses, since the topic is labeled an elective in CS2013. See here: https://github.com/ossu/computer-science/issues/640
