### ISSUE TITLE
Books teaching web technology

### ISSUE THREAD

**Issue by ycpei** [ossu/computer-science#468]
Could someone add some books that teach basics of e.g. web frameworks in `reading.md`?

**Comment by Otumian-empire** [comment]
Hello, on the issue of using books. I could learn more if i could use a book as compared to the video. I started with the introduction to cs but the course hasn't started as i speak. so i found a book by John Zelle, Python programming: An introduction to computer science. When i got to the GUI part i used another book, A Practical Introduction to Python Programming, by Brian Heinold. I thought, perhaps i could have a start with the core maths. Any any suggestion on a book. Thanks

**Comment by Alaharon123** [comment]
If you take a look at the wiki, @hanjiexi put up a draft of v9 of the curriculum and there's a text alternative to every course. The intro cs part isn't filled in yet (see #540), but there's a text version of the current intro cs course too https://www.amazon.com/gp/aw/d/0262529629

**Comment by Otumian-empire** [comment]
thanks
