### ISSUE TITLE
Haskell course

### ISSUE THREAD

**Issue by zlatin** [ossu/computer-science#472]
University of Glasgow launches [Functional Programming in Haskell: Supercharge Your Coding](https://www.futurelearn.com/courses/functional-programming-haskell). Looks promising. Course on Haskell from university that created Haskell sounds good =)

**Comment by waciumawanjohi** [comment]
@zlatin , I hope you'll excuse me from quoting myself verbatim, but something I recently wrote to another OSSUer applies directly here:

An interesting find. There's currently an Intro to Haskell course in extras/courses:
https://www.seas.upenn.edu/~cis194/fall16/

Are you planning to take one of these courses? If you do, could you also do a survey of the other course for comparison's sake?

Once you've done that, will you share with us which you think is the better course for OSSU? Feel free to ping other students that would be interested (try reaching out to people in the gitter chat room) in joining you in that!

(See https://github.com/ossu/computer-science/issues/471)

**Comment by Nixerrr** [comment]
I'd love to do this course. I'm very interested in Haskell and this seems like a good intro. What do you say @zlatin ?

**Comment by arcanemutterings** [comment]
@waciumawanjohi Sadly, I haven't. It's on my to-do-list, but I don't if and when I'll get to it.

**Comment by hanjiexi** [comment]
For both #471 and this issue: here is some guidance on what I would be looking for in a resource on Haskell.

I want any course on Haskell we recommend to go far enough to explain how and why computational effects are encoded in the type system. Simply teaching the same things students would have already learned in Dan Grossman's utterly excellent course "Programming Languages" wouldn't be enough to justify its inclusion in the curriculum. At the most rudimentary level, SML and Haskell are very similar.

I'm not looking for a course that emphasizes Haskell's decision to be lazy by default on all expressions. This was the wrong decision, as admitted by both Haskell's original author and by PL theorists. Of course laziness will get mentioned, and needs to be, but I don't want students to think it's the right way to do things.

I'm also not looking for a full-blown course on category theory, which is way too advanced for students at that stage. It's not as hard as people think, but it belongs somewhere in Advanced CS.

I am broadly in favor of a resource emphasizing Haskell's typeclasses, which are widely loved and imitated by the newest languages. (See Rust and Swift.)

**Comment by waciumawanjohi** [comment]
Lacking any new feedback, closing this issue. If there's new information about these offerings, please open a new issue and update us all!
