### ISSUE TITLE
An OSSU version for Computer Engineering?

### ISSUE THREAD

**Issue by lixsee** [ossu/computer-science#481]
Hi. I'd like to know if there is a free and complete curriculum for Computer Engineering?  Is there a course that allows you to work on electronics and create circuit boards and stuff?  Thanks.

**Comment by waciumawanjohi** [comment]
@lixsee OSSU does not currently have a curriculum for Electrical Engineering. Your request lets us know that there is interest in such a curriculum.

**Comment by fractalbach** [comment]
The ACM has put together some cirricula reccomendations.  One of those is computer engineering, which may be helpful to design a version for OSSU.

https://www.acm.org/education/curricula-recommendations

**Comment by vapeurs** [comment]
@waciumawanjohi  I think he asked for computer engineering, not electrical engineering. From my understanding their is a wide difference between the two disciplines.
