### ISSUE TITLE
ACM curricula reccomendations

### ISSUE THREAD

**Issue by fractalbach** [ossu/computer-science#482]
I thought it would be worth mentioning the existence of the ACM curricula reccomendations, which seem relevent to OSSU.  These could be used as a reference, or a link to them could be included.

Specifically, I found the concept of "Knowledge Areas" to particularly useful.  The computer science 2013 cirriculum is a good one to look at first.

https://www.acm.org/education/curricula-recommendations

**Comment by amorriscode** [comment]
This is a very cool resource, thanks for sharing.

**Comment by hanjiexi** [comment]
Thanks @fractalbach, I'm closing this now because #517 (once it gets merged) will be adding these and other resources to our curriculum.
