### ISSUE TITLE
Regarding Natural Science, Logic, Ethics, Humanities, Social Science and Writing

### ISSUE THREAD

**Issue by vapeurs** [ossu/computer-science#483]
How broad is the OSSU curriculum? would it be appopriate to include classes from the disciplines listed above?

Is OSSU's course bare bones for a reason? Does it fullfill the same requirments a 4 year university course would?

**Comment by Zer0evil** [comment]
I would think you could augment it with whatever subjects you wanted.

**Comment by mattboler** [comment]
I don't think OSSU's purpose is to replace the 4-year collegiate _experience_, more so to curate a major-course curriculum similar to that of a 4-year computer science degree (and then some). Nothing says you can't add on some gen eds, but it seems out of the scope of the project.

**Comment by robbrit** [comment]
Definitely agreed, we're not replacing a 4-year degree. In particular, replacing the social atmosphere and corresponding soft skill development is something very difficult (if not impossible) to do in a MOOC setting.

**Comment by hanjiexi** [comment]
I'm closing this as @mattboler and @robbrit have given good answers!
