### ISSUE TITLE
SICP link on extras/readings.md is broken

### ISSUE THREAD

**Issue by mattboler** [ossu/computer-science#484]
The SICP link in the Great Readings page is broken. I propose replacing it with https://github.com/sarabander/sicp-pdf, which is a version of the book redone in modern typesetting for quality of life improvements.

**Comment by amorriscode** [comment]
There is also an [HTML version of the book](http://sarabander.github.io/sicp/) that we might consider.

**Comment by amorriscode** [comment]
@GustavBertram got us with an updated version of the URL and it has been fixed.
