### ISSUE TITLE
"Introduction to Computer Science and Programming using Python" unavailable

### ISSUE THREAD

**Issue by pillboxer** [ossu/computer-science#487]
Not sure if this is recent, but is there an alternative to this anyone could recommend?

**Comment by hanjiexi** [comment]
You're right. Very strange!

The MIT OCW version is here: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/

I don't know how it compares to the edX version. If edX doesn't restore their version quickly, we will need to add an alternate link into the curriculum.

**Comment by Sanius** [comment]
The professors have blocked the old course and may reopen it in late august.

**Comment by vapeurs** [comment]
If you signed up prior to the course being blocked, you will still have access. 

https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-11  

Is the most recent revision of the course, but is currently inaccessible to new students.


https://courses.edx.org/courses/course-v1:MITx+6.00.1x_7+3T2015

Is the 2015 version of the course. I am not sure how out to date the content is. It should be accessible to anyone.

**Comment by robert-kn** [comment]
MIT's Introduction to Computer Science and Programming using Python runs on an yearly basis instead of the semester format that was offered previously. 

Students who have completed the course between august 2017 and august 2018 will be able to view the final exam answers (if i recall correctly) due for release late august. 

The course will then be opened again end august/early september for another year.

**Comment by john9631** [comment]
Its back to the 9 week instructor paced version starting with this new iteration.  The next 6.00.2x will start as 6.00.1x finishes.

Sign up for the new iteration of 6.00.1x [is available here.](https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python)

Anyone waiting now, who's Python isn't strong, could start by doing the first part of [sololearn's course](https://www.sololearn.com/Course/Python/), which will make the first few 6.00.1x PSETs much more approachable.

**Comment by hanjiexi** [comment]
I'm closing this as the course has been back up for some time now.

**Comment by buve** [comment]
@hanjiexi It seems to be down again.

**Comment by hanjiexi** [comment]
@buve Although it says not available when you open the course page, I clicked on the "Not Currently Available" button and it enrolled me in the course. I'm able to access the course materials. Perhaps this is just an edX bug?

**Comment by hanjiexi** [comment]
@buve Although it says not available when you open the course page, I clicked on the "Not Currently Available" button and it enrolled me in the course. I'm able to access the course materials. Perhaps this is just an edX bug?

**Comment by buve** [comment]
@hanjiexi It just bring me to the home page when I click on it. I'm guessing this is because you've already enrolled in the course before?

**Comment by Alaharon123** [comment]
It's going to open again in January. I was reading the forum in the course before it finished.

**Comment by buve** [comment]
I've created a new Firefox profile and it now lets me see the archived version. I think this is because of some privacy configurations and extensions. Thanks people.

**Comment by john9631** [comment]
Course just completed (end October 2018) and 6.00.2x is now running.

The next iteration of 6.00.1x will start in late January 2019.
