### ISSUE TITLE
"Reliable Distributed Systems, Part 1" Not disponible

### ISSUE THREAD

**Issue by RaphaelPennacchi** [ossu/computer-science#488]
Does it have an alternative?
I have classes of distributed systems next semester (in 10 days here) and i'd like to start studying 
Thanks guys!

**Comment by hanjiexi** [comment]
Thanks for letting me know. Looks like part 2 is still available. I don't know why another edX course is suddenly unavailable...

A quick Google search yielded this MIT OCW course, which has lecture notes available: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-852j-distributed-algorithms-fall-2009/

The rapidly declining reliability of MOOC platforms to keep their course materials online and accessible is very disturbing.

**Comment by amadeann** [comment]
@hanjiexi Have you 'enrolled' in the course before it was 'switched off'. If so, do you still have access to it?

If this was the case, then the solution could be just enrolling to every single course when starting OSSU curriculum.

I think EdX will keep switching off courses after a couple of years, as they seem to make money only from selling 'verified certificates'. If the university which originally published the course does not support those 'verified paths' anymore, there is no (profit-oriented) reason to keep the course open. 

Even though they are a nonprofit, someone still has to pay for the salaries (~ $24mln / year in 2015/16), and keeping the site running. I may be reading their [tax returns](https://projects.propublica.org/nonprofits/organizations/460807740/201711329349300911/IRS990) wrong, but it looks like selling services make up roughly a third of their income (so not having that part doesn't enable them to keep the site going).

**Comment by vapeurs** [comment]
@amadeann  Do not forget that after EdX's initial fees that it charges the institute, the institute receives 70 percent of any revenue generated by the course. The university has benefit to create pay walls, and from my understanding it has been the University's that have been causing most of the issues.

This is understandable, though. Universities exist to teach, but also to make money. They have to pay the salaries of there employees (as you mentioned).

In regards to your proposed solution: I do not think it is the best method. Some courses (like MIT 6.00, for example) change fairly regularly, and you would want the most recent version of the course obtainable. 

Please correct me if you see any error in the information presented.

**Comment by EndAroundCarry** [comment]
There seems to be a youtube channel for that course.
https://www.youtube.com/playlist?list=PLx3mQFFeHPjndmQ0iP9j6C58b90hqGa0X

**Comment by vapeurs** [comment]
Because the first portion earned from a course goes directly to Edx, unless they have a high enough turn out, they  ultimately lose.

**Comment by phac27** [comment]
@amadeann 

"If this was the case, then the solution could be just enrolling to every single course when starting OSSU curriculum."

I think suggesting books as an alternative to courses would be better, since they don't disappear from the internet, but that's just me.

**Comment by phac27** [comment]
@thesohelshaikh 
I agree, some courses are very unique, you would need at least 4 books to cover every topic in some course's syllabus, but for breadth of content they usually sacrifice deepness, and so sometimes working through a book can be better than completing moocs

Even so, I come from an academic background where every course had it's bibliography, and studying through books would mean you'd know everything being teached in the course and more.

Is it illegal to share lecture notes/transcripts from courses that weren't paywalled when you saved them? 

Suggesting paid books doesn't mean you support piracy, even there aren't free alternatives

**Comment by thesohelshaikh** [comment]
Totally agree with you @phac27. Only thing i want is if we mention a paid book then we should also take time and list similar available free resources.

**Comment by hanjiexi** [comment]
Reliable Distributed Systems is being dropped from the curriculum due to not being available. The only actively maintained course I've found to take its place is this one: https://www.coursera.org/learn/distributed-programming-in-java

The content of Distributed Programming in Java is certainly practical but appears to lack the same theoretical rigor as Reliable Distributed Systems. The readings will have to make up for this deficiency.

**Comment by waciumawanjohi** [comment]
In the short term, I've added a link to the course lectures as an alternative.
In the longer term, there is a Request for Comment to remove Reliable Distributed Systems. https://github.com/ossu/computer-science/issues/640
