### ISSUE TITLE
Pull Request template

### ISSUE THREAD

**Issue by sTiKyt** [ossu/computer-science#492]
Please add Pull Request template
Just make this project more compatible with recommended community standards.

 Thank you.

**Comment by samuelcarlosjr** [comment]
How do I do this? I am new to GitHub I just saw this repo and wanted to refer back eventually.
Thank you.

Samuel Carlos Jr, BS
(505)918-2744
samuelcarloss.jr@outlook.com


________________________________

**Comment by sTiKyt** [comment]
I recommend learning how GitHub works before it, thanks for the answer.

**Comment by hanjiexi** [comment]
Hi @sTiKyt, thanks for your suggestion. Unlike most GitHub repositories, ours doesn't host source code (not yet at least), so certain practices may not be as relevant to us as to others. That said, PR templates could still come in handy if we ever got to the point of having dozens and dozens of PRs to deal with and needed a system to streamline processing them. But for right now our volume is low and manageable so I don't see the benefit.
