### ISSUE TITLE
If I do all the ossu computer science courses, will I get some kind of certificate?

### ISSUE THREAD

**Issue by FloatingInteger** [ossu/computer-science#493]
I think that here https://github.com/ossu/computer-science doesn't explain it, so I would like to know from you if we get a certificate after completing all the curriculum. Thank you!

**Comment by vapeurs** [comment]
OSSU's policy is to ensure that all courses linked from this course are free to access for everyone. Although OSSU itself does not offer a certificate some of the courses it has you take do. You can gain  individual certificates for your completion in the course, but you are in no way obligated to pay for a certificate.

**Comment by hanjiexi** [comment]
I would love if we offered certificates but we're not at that point yet... much infrastructure is needed for that to be possible. For one thing we currently have no way of knowing if someone has gone through the curriculum.

**Comment by hanjiexi** [comment]
@FloatingInteger I'm going to close this for now. OSSU certificates are something to consider a long time from now but it's not relevant at our current stage of development. Good luck with the curriculum!

**Comment by JulioBorbon** [comment]
Let me help you little friend, you may be wrong but you are also right hahaha :) greetings happy xmas

**Comment by FloatingInteger** [comment]
Now let me give u an advice, let's go and study Calculus, you'll need it for Quantum Physics!
