### ISSUE TITLE
Repeated Content in Digital Design

### ISSUE THREAD

**Issue by MohamedMandouh** [ossu/computer-science#494]
Hi all :) 
I have a suggestion 
In Core systems ,
Content provided by the two-course series "From NAND to tetris" of Coursera
is repeated in the Edx's three-course series of MIT "Computation Structure"

the two series teach the same content though MIT's is more comprehensive 
(i.e teaches how to build a computer from transistors bottom up and then introduce advanced topics in parallelism , intercommunication and Operating Systems 

I think this course should be listed in Core Systems instead of Advanced Systems 

it has no prerequisites other than ability to write a for-loop and if condition in C  no wonder it's one of beginner's courses at MIT or "Survey level courses " that provide an introduction to a wide range of topics related to systems and programming .

**Comment by vapeurs** [comment]
I do believe having _Computation Structure_ later on in the course is better. It allows the student to take the time and learn some of the physics  behind everything that  _NAND to tetris_ doesn't exactly cover. 

Building a processor is difficult, and having an underlying understanding of physics prior helps a great deal in understanding everything.


Just my 2 cents.

**Comment by hanjiexi** [comment]
The MIT Computation Structures course is an elective. It's no different from taking a survey course in your first year and then taking a more advanced course in your junior year.

Naturally, much gets repeated in the advanced course, but there's also a lot of breadth and depth in the advanced course that most people aren't going to be interested in.
