### ISSUE TITLE
Discourse forum

### ISSUE THREAD

**Issue by amadeann** [ossu/computer-science#495]
I know this issue has been raised a few times in the past, but since it's a 'university', we have new cohorts all the time, so maybe something changed.

Would there be any interest in the community in having a [Discourse](https://www.discourse.org/) app behind OSSU? My personal opinion is that Github + Gitter is not really a good way to organize discussions. Github is for issues - have a problem/bug, post it, get a solution, close. We can't even (self) organize issues by topic (I'm referring to labels).

What do you think?

:+1: If you'd use such forum (Discourse)
:-1: If you'd rather stick to what we have now (Github issues)

 If enough people are interested (20 :+1: at least), I can set up a forum, and pay for hosting.

**Comment by vapeurs** [comment]
https://reddit.com/r/opensourcesociety/

**Comment by thesohelshaikh** [comment]
Rather than making another website we can utilize social media platforms where users already have accounts.

**Comment by thesohelshaikh** [comment]
I suggest making accounts for Twitter, Instagram, Quora, Discord too @vapeurs @amadeann. Other than facebook group. I also recommend adding a Facebook page.

**Comment by vapeurs** [comment]
I don't see any need for a Facebook Page. If you do, feel free to make one. 

My response was mostly to say I don't feel OSSU has enough of a responsive user base to warrant a chat.  That said, most of the courses recommended have existing Facebook groups to assist students with psets, etc. I found them quite helpful. Being able to have a group on Facebook allows easier communication with those interested.

**Comment by vapeurs** [comment]
I also took the liberty to start an IRC channel, though I doubt it will gain much use.

irc://irc.oftc.net/#OSSU

**Comment by amadeann** [comment]
@thesohelshaikh Do you feel like social media platforms give you a good way to organize topics, and have longer form discussions which can be referred to over the years? 

I pictured something like this:

1. General Questions Forum
2. Core CS Section
2.1. Core programming subsection
2.2. Core math subsection
2.....
3. Advanced CS Section
3.1. Advanced programming subsection

Chats like Gitter, Slack, Discord, IRC are ways to get an 'instant' help. But if someone has the same question on the next day, they will have to ask it again. Facebook, Twitter, Instagram are the same. 

Quora/Github issues are slightly better, but let's say you are taking Linear Algebra course, and want to find out what other people are struggling with/have struggled with years ago while taking the same course. How can you intelligently browse topics from the specific subject via Social Media platform.

I may have the different perspective on this, since I grew up in the age of phpBB, Simple Machines Forum, etc. I feel like online communities were more organized with such tools in the late 90s, early 2000s. Discourse is a 'modern' version of such forums, that's why I suggested that.

For those who don't know what Discourse is, here's an example how Vue.js community utilizes it:

https://forum.vuejs.org/

**Comment by daengx** [comment]
what's the discord invite?

**Comment by vapeurs** [comment]
Reference issue: https://github.com/ossu/forum/issues/2

**Comment by amadeann** [comment]
I think it's a good idea to show interest/disinterest by doing thumbs up/down in the original post.

**Comment by vapeurs** [comment]
Have you taken the effort to build a  forum yet?

**Comment by amadeann** [comment]
No, first I want to see if there is any interest in it.

**Comment by w96k** [comment]
I was topic starter in prev issue asking for a real forum engine. Using forum engine like discourge (any engine actually) will be much better than using tons of social networks (twitter, reddit, fb & so on). In my experience its much harder to get help using those resources especially when you need only to find some piece of information (several sources make this task pretty hard). Github Issues & other media doesn't provide categories for proper topic organization.

**Comment by vapeurs** [comment]
I agree, having a central location everyone can go, and  have there questions is key,  but I do not feel in this day and age a Forum will act as this hub.

I spent many of my years frequenting, and administering web forums. Most of these communities have dwindled, or dissipated completely.  

While I agree a Forum will offer a boon for those that need it, but don't think that the information will ever fully be decentralized. 

I know people that prefer IRC over forums simply because of the interactive aspect of it. I know people that prefer Facebook out of convenience.   A web forum is a great idea, but how active will it really be?

Will it be this amazing social hub, or will it sit by the side unused?

How many people visit, or even know about the already existing OSSU forum?

It is linked directly from the README, but it seems none of you know about it. If you did, why not raise this issue there?

Github Issues is a wonderful place to share, and source information. It reminds me a bit of mailing lists.  It also gives the prospective student a place to practice the Github skills. 

Good example of helping someone: https://github.com/ossu/forum/issues/5

**Comment by amadeann** [comment]
True, the existing forum is not very active. I assumed it's because people wanted better tools (better forum engine). But maybe the sad truth is that despite the number of stars on this repository (it's 80th most starred one on GitHub) only a handful of people follow the curriculum?

**Comment by DavidScales** [comment]
@amadeann I'm pretty ambivalent about a forum, but I wanted to address your comment.

I'm not super active on this project, but I think it's the coolest thing ever. I think that the nature of the project doesn't really lend itself to clear and active participation. At the core it's an entire university curriculum, and a lot of people are probably working through it in between jobs & life. I'm trying to work through the curriculum myself, but one class will take me months, and I'm mostly just focused on the class when I'm doing it (which usually have thier own forums/groups etc.). And I only actually look at OSSU itself a few times a year after I've finished a class, so I probably wouldn't use any forums and don't really have any confusions to discuss about OSSU itself that aren't addressed by GitHub issues. 

That could be different for other people (especially if people are actually working together in cohorts), but what I'm really getting at is that I'd be willing to bet that a lot of people (like me) value this project a lot even if it's not obvious in the metrics that we're discussing here, and I don't want contributors to be discouraged.

**Comment by amadeann** [comment]
Even if we don't actually get the forum project going, it's still very good to know how other people approach OSSU :) Thanks for your comment!

**Comment by BatmanPriddy** [comment]
Sad to hear that the forum is not very active.  Seems like it would be a great platform for students to assist each other with issues, questions, support, etc.  I'm going to start the curriculum in the near future, and having a forum or some sort of online space to discuss the courses would be fantastic and very helpful!

**Comment by spelga** [comment]
Jason I don't think anyone is saying you can't get those things it's just
that if you are following a particular course then that course will have
it's own platforms for students to discuss the course and seek help. If
that already exists and you have people following the course on the same
schedule as yourself then there is little incentive to go elsewhere to seek
that help.

Having said that the great failing of these courses is that you are very
often prevented from discussing your solutions and as such valuable
feedback which will help you understand what you are doing well and what
you are not so good at is missed. If something could be done to resolve
that I feel these online courses would be greatly improved. it's something
that is absolutely vital in brick and mortar universities in helping
students get the most out of the material.

**Comment by vapeurs** [comment]
They did a survey on 6.00 asking where they gained the most help: the majority said the forum. 

This was posted a little over a half hour ago. I agree that having a central place to ask questions is important, but what is the likelyhood someone like kiwitrader, or even Thomas Ballatore will frequent them?

Not to say the participants of OSSU will be of some help, i just do not believe there will be much of a user base. 

I could be wrong.

![screenshot_20180823_173344](https://user-images.githubusercontent.com/29875414/44557209-c6137980-a6fa-11e8-8e94-23156a6b7a81.png)

**Comment by BatmanPriddy** [comment]
@spelga thanks so much for your response, and you make some very valid points!

**Comment by hanjiexi** [comment]
I am often puzzled when I see 20 different split up communities all associated with one thing. For example, if I remember correctly, Harvard CS50 seemed to have a presence on every social media platform in this galaxy and I had no idea which one I should have used. I didn't have a good experience trying to get help on one of them, perhaps because the community is so scattered.

The reason Eric ended up deleting our various social media presences was to prevent this fragmentation. I think, though, that the actual OSSU forum repo isn't really working well. At some point we'll need a better — but still centralized — solution, like one integrated with an official website that everyone knows to go to.

**Comment by waciumawanjohi** [comment]
I also think that learners should consider the level of conversation they want. When you go to college, you may be assigned an advisor or dean. They are student focused, they are there to help. If you want to ask whether a class fits your learning plan, go to those people. But they are not the person that you go to when you have a question about your chemistry homework. There's a thoroughly qualified chemistry teacher, TAs and fellow students in the class to ask those questions.

OSSU conversation channels should stay at the dean level. Learners should use the individual course forums to address course specific questions.

While the forum repo hasn't caught on, the gitter channel sees regular posts and has a few regulars that respond. I agree with @hanjiexi , better than spreading over a dozen platforms is to concentrate on one solution.

**Comment by hanjiexi** [comment]
@waciumawanjohi makes a good point. I would generalize his point to say that we should ensure that each of the communication channels that we do have is serving a specific need that isn't better served elsewhere.

**Curriculum implementation level**: GitHub issues should be about the specific repository associated with it. Specific choices about the materials we selected, formatting and organization, etc. If we continue to host curriculum *requirements* in this repo, then conversations about those requirements should take place here as well. (Eventually, we may grow to the point of needing a separate repo for managing academic requirements for all OSSU curriculua.)

**Advising level**: Gitter is suitable for ad hoc, semi-real time, ephemeral conversations. Good place for talking to our "deans" in a semi-public way, or for private advising.

**Subject level**: This would be useful for any resources we recommend that don't have forums available, or where the course does have forums but they're inactive and useless, as some course forums sometimes are. This is where a Discourse forum might fit in best — but I don't see us acquiring a full website in time for v9.

**Course level**: Use the forums for that course, if active and available.
