### ISSUE TITLE
Book equivalents 

### ISSUE THREAD

**Issue by ahmdaeyz** [ossu/computer-science#498]
are there any book equivalents to these courses for people who tend to like reading articles and studying from books ?

**Comment by amadeann** [comment]
Yes, check out the list here:

https://github.com/ossu/computer-science/blob/dev/extras/readings.md

**Comment by phac27** [comment]
I don't think any book can really substitute CS50 for example, you can just read the lectures notes if you also prefer studying from books

**Comment by ryaholm** [comment]
I am organizing a CS curriculum using open source OER books over at [https://github.com/HolmSchool/curriculum](https://github.com/HolmSchool/curriculum). Might I also recommend [free-programming-books](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md) for finding free programming books.
