### ISSUE TITLE
Core Math

### ISSUE THREAD

**Issue by jhubler99** [ossu/computer-science#502]
Hi 

I'm a student whose taking the OSSU Computer Science curriculum. I like the fact that it is free! I have a suggestion for a replacement course in the Core Math section. For me, the student, I feel the Mathematics for Computer Science is not the best fit. There is no key for neither the assignments nor the exams. You do not know if you are right on a question. The course on coursera: Discrete Mathematics by Dominik Scheder. It is 11 weeks long and 3-5hrs\week. It is a graded course. 

- https://www.coursera.org/learn/discrete-mathematics
    
I do not know if the course material will help with later courses. Personally, I do not like not knowing if my answer are correct. Would this new course work? 

Thank you 
John

**Comment by jhubler99** [comment]
I was wondering if anyone checked this new course?  

Thanks 
John

**Comment by illucent** [comment]
I'm planning to.

**Comment by jhubler99** [comment]
Hi

Thank you for looking into this new course @illucent. I realize in this course, they don't teach modular arithmetic. If the student takes CS50 from the Introduction to Computer Science section, we have to learn about the modulo operator (%) to do a problem set. 

I look forward to what you say about this new course. 
John

**Comment by hanjiexi** [comment]
Hi @jhubler99, I had started to take that course to evaluate it as a replacement for MIT Mathematics for Computer Science. I can't remember exactly what the reason was, but I found it to be a very poor substitute.

Also, MIT Math for CS does have some interactive assessments that tell you whether you got an answer right. Here's one for example: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/proofs/tp3-1/vertical-1131e84e1185/

**Comment by jhubler99** [comment]
Hi @hanjiexi,  

Thank you for the information. I only checked the Exams section,  but did not realize there was interactive assessments. 

John

**Comment by hanjiexi** [comment]
Closing this issue for now as the issue appears to have been resolved.

**Comment by illucent** [comment]
Hi @jhubler99! Sorry being late after closing an issue. As a free listener I found [discrete-mathematics](https://www.coursera.org/learn/discrete-mathematics) very advanced, teaching more on techniques and intuition.

**Comment by jhubler99** [comment]
Hi @illucent 
Thank you for taking the time to look into this course. 
John
