### ISSUE TITLE
Lots of courses are not available anymore

### ISSUE THREAD

**Issue by iripu** [ossu/computer-science#503]
1. Math (Calculus)
2. Algorithms
3. Theory
4. Computer Networks
5. Operating Systems
6. Cloud Computing
7. Compilers
8. Parallel Computing
9. Natural Language Processing
10. Big Data
11. Program Design (Systematic Program Design)

Please add alternatives to the above.

**Comment by owususamuel** [comment]
That website hasn't been updated in a very long time. Don't follow the curriculum on that site.
Use the one [here ](https://github.com/ossu/computer-science) on github, it's very active and up to date.
