### ISSUE TITLE
Mention Cohorts under README

### ISSUE THREAD

**Issue by calvinlin1992** [ossu/computer-science#512]
It would be nice if the README mentions / links to the [OSSU Cohorts Page](https://github.com/ossu/cohorts) as that page doesn't seem like there is a lot of activity.

**Comment by hanjiexi** [comment]
Good catch — I was surprised to find that it didn't already mention cohorts. As you can see, I just merged an update that includes this information.

**Comment by calvinlin1992** [comment]
Awesome!
