### ISSUE TITLE
Algorithms: Princeton vs. Stanford Courses

### ISSUE THREAD

**Issue by ceik** [ossu/computer-science#519]
Firstly: Thanks for all the work you guys put into this project. It helps me a lot and is greatly appreciated!

I was about to start the Algorithms course on Langunita and saw that there is a course that there is a similar course (at least in terms of name) by Princeton on Coursea. I understand that the Princeton one was replaced by the Stanford one only because the second part of the former was offline for a long time. This is no longer the case (I just enrolled in Princeton's Algorithm's Part II to test it out: https://www.coursera.org/learn/algorithms-part2).

Given that both are available again, are there any reasons to chose one over the other purely from a content and didactical point of view? I went throught the topics covered by each, but frankly most of that stuff doesn't mean anything to me, so any insight from someone further ahead or someone who knows both of them would be great.

**Comment by andresziemecki** [comment]
Did you find the answer? I've the same question

**Comment by waciumawanjohi** [comment]
Apologies for the short response: The Princeton course emphasizes writing your own implementation of the algorithms. The Stanford course emphasizes analyzing algorithms to understand their complexity. Both are well regarded.

**Comment by OmarShawky1** [comment]
> Apologies for the short response: The Princeton course emphasizes writing your own implementation of the algorithms. The Stanford course emphasizes analyzing algorithms to understand their complexity. Both are well regarded.


Don't you need both? and to what extent that Stanford helps in analyzing the complexity better than Princeton?

I didn't take Stanford but I finished Princeton I & II.
