### ISSUE TITLE
Parallel, concurrent, and distributed computing

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#523]
For v9 of the curriculum I am hoping to come to a solution that can close #459, #449, and #488.

The easiest way to solve this problem for right now would be to use Coursera's [Parallel, Concurrent, and Distributed Programming in Java Specialization](https://www.coursera.org/specializations/pcdp). It costs money to access assignments, but video lectures can be audited for free, which is (in effect) the same as posting some other kind of non-interactive content, like a random course website, YouTube series, or a book. But unlike many such other resources, this would be more consistent (all in one language) and it wouldn't require any additional prerequisites on top of needing to know Java.

Does anyone have any major objections to this plan?

**Comment by waciumawanjohi** [comment]
It looks like this change didn't end up being made. Looking at the proposal again, I think there are some very good reasons not to add these 3 courses.

1) I've just created [an RFC to address Distributed Systems](https://github.com/ossu/computer-science/issues/640).

2) Our current recommendation for parallel programming, [Intro to Parallel Programming](https://classroom.udacity.com/courses/cs344), is available. It is free of charge and includes programming assignments. As you noted, that is not the case for Coursera's Parallel Programming in Java.

3) Even if we were to remove the current recommendation, I think we should replace it with Carnegie Mellon's course on parallel programming. The recommendation would look something like:
- Take the final quarter of CMU's Introduction to Computer Systems (which is cross listed under many different numbers). On the [schedule](https://www.cs.cmu.edu/afs/cs/academic/class/15213-f19/www/schedule.html), start with [Lecture 24: Concurrent Programming](https://ini.mediasite.com/mediasite/Catalog/catalogs/mediasiteadmin-14-513-intro-to-computer-systems-kesden). Complete the rest of the semester's lectures.
- Complete the final lab of the course, [ProxyLab](http://www.cs.cmu.edu/afs/cs/academic/class/15213-f10/www/assignments.html). You can find a repository with the necessary files by searching github for `15-213 proxy`.
- Complete CMU's [Parallel Computer Architecture and Programming](http://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15418-f19/www/index.html).
_The challenge of the CMU's parallel programming course is that there is no autograder for the assignments. Students are expected to implement algorithms, test them on hardware and analyze the results. These are assignments with high expectations, but students won't have mentors who can give them feedback if they are on the wrong track._

With free alternatives, I don't think we should add the paid Coursera courses.

**Comment by waciumawanjohi** [comment]
@hanjiexi I've just closed Issue #640, which was a Request for Comment on the Distributed Computing courses that had been recommended but were no longer available. I believe that also closes this issue. Please reopen if you do not think that is the case.
