### ISSUE TITLE
Split "Theory" into "Theory" and "Structures"?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#525]
Currently we have one big super-topic called "Theory" that mixes a lot of different... theories into it. I want to add more courses and it will get even more bloated, so I propose splitting theory in 2.

Theory would be used for what is called theoretical computer science, a topic of which we currently have poor coverage.

Structures would be used for material covering concrete data structures (e.g. arrays), abstract data structures (e.g. stacks), purely abstract structures like categories and abstract machines, and theory-focused applications of those structures to the real world, e.g. (theory of) databases, (theory of) networks.

Additions:
- I want to add category theory material to "Advanced Structures".
- I want to add material on persistent data structures to "Advanced Structures".

**Comment by waciumawanjohi** [comment]
This sounds unobjectionable. It sounds like Theory would then be Advanced Theory without a corresponding Core Theory. Is that what you envision?

**Comment by hanjiexi** [comment]
No, not at all. The "Theory" part is very important; it's what makes us a real CS curriculum.

But what I think should go in Core Theory was still in flux when I wrote this issue, and still is to an extent, because I want to keep each subject conceptually narrow enough to have a small grouping of closely related courses, while also not creating too many subjects.

So it comes down to: what do we mean when we say 'programming', 'structures', and 'theory'? My vision is, broadly, to prefer a more academic interpretation of these terms:
- **Programming** is the "languages" part of the "[Holy Trinity](https://existentialtype.wordpress.com/2011/03/27/the-holy-trinity/)" (see [here](https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence#Curry%E2%80%93Howard%E2%80%93Lambek_correspondence), or this [amazing video](https://www.youtube.com/watch?v=IOiZatlZtGU) for way more more down-to-earth treatment), and thus, a synonym for type theory.
- **Structures** refers both to concrete structures (implementations) and abstract structures (signatures). In the end, category theory wraps everything up in a purely abstract framework.
- **Theory** refers, at the simpler level, to the fundamental problems Godel, Church, Turing, and others were solving in the early- to mid-20th century, before there were any actual machine-based computers. What is computation? What can be computed, how (i.e. models of computation), and within what limits?

We don't currently have any major section devoted *by name* to logic, the remaining member of the "Holy Trinity". For the curriculum as it is right now, this isn't a big deal since advanced logic isn't being used anywhere. But it would be a big deal if we add more advanced material like formal methods. I think Math is the best place for logic — they're basically synonyms after all — and having sub-sections devoted to Discrete Math, Algebra (linear in Core and abstract in Advanced), and Logic.
