### ISSUE TITLE
Make "Applications" a top-level section?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#527]
I want to move "Applications" to its own top-level section separate from Core and Advanced for the following reasons:
- "Applications" aren't inherently foundational or advanced by themselves; they each have their own specific learning curve.
- "Applications" often also have their own specific and unique prerequisites. For example, multivariable calculus and intro to probability (under Advanced Math) aren't used as prerequisites for anything else unless you are focusing on specific domain areas.
- By moving out "Applications", we keep Core/Advanced CS just focused on CS.

We might be wise to change the name from "Applications" (which is often used as a synonym for "computer programs") to "Domains", "Sub-domains", or "Domains of Computer Science".

**Comment by hanjiexi** [comment]
Example domains:
- Artificial intelligence
- Game development
- Graphics
- Cryptography
- Machine learning
- Robotics
- Frontend development
- Backend development
- Computer vision

**Comment by waciumawanjohi** [comment]
Yes, taking the applications out of core CS is a very good idea. And making clear what pre-reqs are tied to what application domains will be helpful.

We may also consider if domains should be the exit point for OSSU. Machine Learning, Robotics, Computer Vision are all graduate level degrees. Along with recommending the best resources available for study, we should let students know when they have finished the equivalent of an undergraduate series of study, when they are prepared for graduate level work.
