### ISSUE TITLE
Create an "Engineering" section under Core and Advanced?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#528]
If we move forward with #527, we'll have some courses that are too general and universal to really get their own "Domain".

Therefore, I want to create a new(ish) section under both "Core" and "Advanced" called "Engineering". It would be focused just on processes, good practices, etc. for building larger systems. This is relevant to almost every other domain.

Less important: I am considering moving Software Testing and Software Debugging to "Core Engineering" as they are simpler and more fundamental, and moving the UBC "Software Engineering" courses to "Advanced Engineering" as they are much more involved.

**Comment by waciumawanjohi** [comment]
From what you've written here, I assume you mean Software Engineering. We should label it such, otherwise some non-zero number of students will confuse it with Computer Engineering.

I agree that we should split out the software engineering classes. I think that most of the programming courses should go into engineering.

What is your vision for "where" engineering should exist in the curriculum? It seems to me that it would be an optional sidecar. [Illustration](https://www.lucidchart.com/invitations/accept/572d5468-3c8a-4e6f-b3ee-ad0171b5feff)

**Comment by hanjiexi** [comment]
I was originally going to write this in #525, but it's more relevant here.

Engineering is tricky because when you say "software engineering" many people interpret this as meaning "[move fast and break things](https://xkcd.com/1428/)", "agile", "write good commit messages", and other such mundane things. A slightly more rigorous definition means things like knowing what kind of database or algorithm to use for what purpose — which is still trivial enough to learn just from reading a few books.

For some reason, engineering standards are ridiculously low in most software fields, *[even when people's lives depend on them](http://www.safetyresearch.net/blog/articles/toyota-unintended-acceleration-and-big-bowl-%E2%80%9Cspaghetti%E2%80%9D-code)!*. (I believe aviation is an exception.) But engineering outside of software circles involves a much higher degree of rigor; they have the same level of professional expectation as doctors and lawyers.

After thinking about this more, I personally do not want OSSU to contribute to the shallower, narrower definition of "engineering". Practical engineering certainly includes processes and good practices but these are trivial to learn compared to the academic aspect of engineering, which I think should focus on formal methods: the techniques used to prove that a program is correct, especially in the context of designing large and complex programs. TLA+ for example has been used very successfully to design correct, elegant, distributed systems. And there is even some [course material](https://www.edx.org/micromasters/software-testing-verification) we can use.

[LAFF - Programming for Correctness](https://www.edx.org/course/laff-programming-correctness-utaustinx-ut-p4c-14-01x) belongs there for sure, but I do not agree that most of our existing programming courses should go in engineering. Our programming courses teach type theory (albeit implicitly) and are more of a prereq to engineering.

I do agree that there needs to be some place somewhere for learning practical skills — like a place for recommending the best course on Git, etc. — but I feel this is a problem better discussed when we start tackling the projects side of OSSU.

Also agree that "Software Engineering" is better than just "Engineering".

**Comment by waciumawanjohi** [comment]
I certainly endorse rigor in the curriculum. Does that answer where Software Engineering belongs? Are you envisioning it as a domain alongside others such as Machine Learning?

Where IS the place for the programming courses? Prolog is interesting, but a CS major can finish a degree without interacting with it. Programming Languages compares and contrasts many languages, but it's not clear that exploration is necessary for all students.

**Comment by hanjiexi** [comment]
I don't have a rock-solid answer yet, sorry. My thoughts in #531 should shed more light on what I'm thinking with regard to how all this should be organized. The key point is that everything should point to some Domain. If we have material that doesn't lead to a Domain, we would either remove it or create a new Domain that justifies its inclusion. There should be a logical progression from:
1. section(s) of Foundations to
2. all of Core CS to
3. section(s) of Advanced CS to
4. one Domain
