### ISSUE TITLE
Split each section to its own page?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#529]
A minor shortcoming of the structure of the OSSU CS crepository is that we are basically using one big page for the entire curriculum, and all secondary resources have to go in extras. This means that valuable secondary materials are kept separate from the primary resources that we recommend unless we add a footnote. It also discourages us from adding more narrative to the curriculum to explain why certain materials were chosen and what students should be focusing on, as adding such descriptions would make the page really long and burdensome to scroll through.

I want to give each major section its own page so that the resources can be discussed in greater detail without making the page really long. The main page would just be a guide to the overall curriculum and a table of contents for the remaining pages.

**Comment by Bukowsky** [comment]
Totally agree with the split. It will make the main page more readable and give extra space for greater detail on each section.

**Comment by amorriscode** [comment]
I would like to see this as well; it would be nice to have extras related to primary resources.

**Comment by KathrynN** [comment]
I agree as long as there is some automated way to link them all together - something like a git book maybe, where the student can navigate easily in between pages.
