### ISSUE TITLE
Follow ABET CAC criteria more closely?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#532]
@waciumawanjohi 

You've previously raised an issue (#433) about placement of the "Hack the Kernel" class due to ABET's published standard. Here are the latest requirements from v2 of their [CAC criteria](http://www.abet.org/accreditation/accreditation-criteria/cac-criteria/):

> 1. Substantial coverage of algorithms and complexity, computer science theory, concepts of programming languages, and software development.
> 2. Substantial coverage of at least one general-purpose programming language.
> 3. Exposure to computer architecture and organization, information management, networking and communication, operating systems, and parallel and distributed computing.
> 4. The study of computing-based systems at varying levels of abstraction.
> 5. A major project that requires integration and application of knowledge and skills acquired in earlier course work.

We have plenty of 1, 2, and 4. A better projects infrastructure is needed for 5, but I think we should improve the curriculum content first before tackling such a major challenge.

**We currently don't require any major coursework on parallel and distributed computing in Core CS.** The subjects are probably mentioned here and there throughout the existing Core CS curriculum, but it's probably not enough to qualify as "exposure".

On the other hand, you recently mentioned to me on Gitter that CS undergrads at Georgia Tech only have *four* courses required of all of them. I think it's pretty common to require a very small number of core courses, and impose taking a minimum number of credit hours among a wide variety of elective courses.

But I wonder, how exactly are schools fulfilling these ABET requirements? Or is "exposure" truly much softer than it sounds? Like if distributed computing is an elective that not everyone takes, does that count as "exposure" for purposes of fulfilling ABET's requirement?

**Comment by hanjiexi** [comment]
The reason I'm bringing this up is because, Core CS is already really heavy, and if we follow a more literal interpretation of the ABET standards, it would get even heavier by adding parallel and distributed computing. (As super-important as these concepts are, I haven't found much in the way of more lightweight coursework on them.)

So I'm kind of thinking that, if other schools are able to have a more liberal interpretation of "exposure", then so can we? In that case, we could consider substantially slimming down Core CS.

**Comment by waciumawanjohi** [comment]
The primary thing that jumps out at me from the ABET standards at the moment is #2. Substantial coverage of at least one general-purpose programming language. At the moment Core Programming recommends 8 months of study (>8 hours/week) mainly learning programming patterns. I read the ABET standards as arguing that we reduce these recs in favor of other material (as you pointed out, parallel computing, etc)

**Comment by hanjiexi** [comment]
Apologies, I made a mistake. I originally intended to copy *all* of the standards, but I neglected two major sections! I will respond to you later about your comments on point 2, but for right now I want to put up the full standards:

> ## Curriculum
> The  curriculum  requirements  specify  topics,  but  do  not prescribe  specific  courses. These requirements are:
> 
> ### Computer science
> At least 40 semester credit hours (or equivalent) that must include:
> 1. Substantial coverage of algorithms and complexity, computer science theory, concepts of programming languages, and software development.
> 2. Substantial coverage of at least one general-purpose programming language.
> 3. Exposure to computer architecture and organization, information management, networking and communication, operating systems, and parallel and distributed computing.
> 4. The study of computing-based systems at varying levels of abstraction.
> 5. A major project that requires integration and application of knowledge and skills acquired in earlier course work.
> 
> ### Mathematics
> 
> At least 15 semester credit hours (or equivalent) that must include discrete mathematics and must have mathematical rigor at least equivalent to introductory calculus.
> 
> The additional mathematics might include course work in 
> areas such as calculus, linear algebra, numerical methods, probability, statistics, or number theory.
> 
> ### Natural sciences
> 
> At least six semester credit hours (or equivalent) in natural science course work intended for science and engineering majors. This course work must develop an understanding of the scientific method and must include laboratory work.

**Comment by hanjiexi** [comment]
> The primary thing that jumps out at me from the ABET standards at the moment is #2. Substantial coverage of at least one general-purpose programming language. At the moment Core Programming recommends 8 months of study (>8 hours/week) mainly learning programming patterns. I read the ABET standards as arguing that we reduce these recs in favor of other material (as you pointed out, parallel computing, etc)

Regarding no. 2, ensuring that students become very strong in at least one general-purpose programming language is a goal I do have, but not an easy task and it could radically transform the curriculum. I've gotten mixed feedback about this idea in the past. It also invites arguments about "which language is best", etc., about which everyone has their own ideas.

The two basic options are:
1. We choose one language that everyone has to learn. This means we need to find super high-quality *and free* material for learning it, but if we can find this material, it's easier to integrate into the curriculum and easier to do community project grading (since everyone will know the language).
2. We let students choose what language they wish to master. The material for learning it would have to be separate from the main curriculum, but in some cases students would be able to fulfill curriculum requirements through language-specific materials (e.g. [Functional Programming in Scala](https://www.coursera.org/specializations/scala) could replace the Java coursework on parallel computing). There also might need to be separate project evaluation committees for each language.

Academically, I strongly prefer option 1. As a student, I strongly prefer option 2. As a curriculum maintainer, option 2 is also convenient since I don't have to rip apart half the existing curriculum.

**Comment by waciumawanjohi** [comment]
Closing this discussion as there have been no comments in 2 years.

Note: While the ABET standards are still in the curricular guidelines, the [CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf) standards have been driving a growing number of Issues.
