### ISSUE TITLE
The first course in the curriculum (Introduction to Computer Science and Programming in Python) is not currently available on edx

### ISSUE THREAD

**Issue by aabdehamid** [ossu/computer-science#536]

**Comment by brlot** [comment]
ok Thank u

**Comment by hanjiexi** [comment]
Hi @aabdehamid, this is indeed pretty annoying, but we are aware of it. If you look in #530 you'll see that there are ongoing discussions about the introduction-level coursework.

**Comment by callistusndemo** [comment]
@aabdehamid, there is a [version of this course](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/index.htm) on MIT Open Courseware that covers the same content. It's a recording of the video lectures offered in Fall 2016 and contains all the materials. Most importantly, uses Python 3.5.

**Comment by saikatdas0790** [comment]
This is available again now. Believe this issue can get closed.
![image](https://user-images.githubusercontent.com/7412443/49857630-108b4400-fe19-11e8-8a6e-26ecef03448c.png)
