### ISSUE TITLE
Software Development MicroMasters is no longer free

### ISSUE THREAD

**Issue by cinephile85** [ossu/computer-science#558]
The courses in the edX Software Development MicroMasters program now only offer free access for about a month and a half. People who can't keep up with the pace, or in some cases exceed it, will not be able to finish the courses before losing access.

**Comment by Alaharon123** [comment]
Can you not just sign up again and skip to where you were up to the first time?

**Comment by cinephile85** [comment]
I'm honestly not sure. Though in the case of this series of courses, I think I'm going to skip it anyway. I'm reading some pretty bad reviews of the later courses.

**Comment by Alaharon123** [comment]
Software Construction isn't going to be in v9 (in the current draft it's replaced by the MIT equivalent) and it doesn't look like the last two courses will be either. 

How to Code is worth taking though from the looks of it. It's kind of hard to get through (I'm on my second break rn at the end of week 3 myself), but if you google OSSU How to Code, you'll find more than one example of it being heavily praised. I wouldn't skip that.

**Comment by cinephile85** [comment]
Good to know, thanks. I'll look into whether you can stop and restart courses without paying and keep the first couple on my radar.

**Comment by cinephile85** [comment]
Through corresponding with edX, after some confusion, what it looks like to me is that you can re-enroll in the same session without paying only before the deadline, at which point you lose access and all your progress, unless you pay for verified. Then you have to wait for the next session to audit again, with the same restrictions, and no previous progress.

**Comment by Alaharon123** [comment]
So basically, they're getting rid of self-paced courses. Your official progress doesn't matter, just your knowledge.

**Comment by cinephile85** [comment]
I think I'm gonna be using Berkeley's archived materials for the most part. Still some stuff here I wanna do, like Nand2Tetris, though that's also in Teach Yourself CS, and Hack the Kernel sounds cool.

**Comment by waciumawanjohi** [comment]
It looks like this discussion has run its course. I'm going to close the issue.
