### ISSUE TITLE
Can't Log In - Firebase Update Required

### ISSUE THREAD

**Issue by R3dGuN** [ossu/computer-science#562]
Greetings,

I tried to log in to OSSU with my GitHub account and received the following message:

{"code":"SERVICE_UNAVAILABLE","statusCode":410,"message":"SDK Update Required: See https://goo.gl/2cKQWm.","details":"SDK Update Required: https://goo.gl/2cKQWm. "}

Based on this information we need to update the Firebase. Pay special attention to the instructions in the following URL:

https://goo.gl/2cKQWm

I'm a GCP certified architect so if you need help let me know.

Thanks for all of the great content!

R3dGuN

**Comment by amorriscode** [comment]
@R3dGuN the Firebase app isn't actually valid. You can read about the discussion here: #466. Sorry for the confusion!

**Comment by Alaharon123** [comment]
@R3dGuN if you want a way to keep track check out #518 but really just use this github. Maybe fork it and cross things out. This is consistently updated and shows prerequisites and organization etc
