### ISSUE TITLE
Ry's Git Tutorial not currently available for purchase

### ISSUE THREAD

**Issue by ahmadshalabi** [ossu/computer-science#564]
It seems Ry's Git Tutorial book not available on kindle. Also it is very old to include it as resources in Tools of Computer Science.

**Comment by Alaharon123** [comment]
I just clicked the link in the wiki and it was free so I got it. Maybe try again and/or refresh the page?

**Comment by ahmadshalabi** [comment]
Maybe it is not available for non-US.

**Comment by muddassirnazir** [comment]
Hey, if anyone is using amazon in India, the Ry's Git Tutorial(Kindle Edition) is available for free: https://www.amazon.in/Rys-Git-Tutorial-Ryan-Hodson-ebook/dp/B00QFIA5OC

You can read the book using https://read.amazon.com or using your iOS, Android or MacOS Apps.

**Comment by Ri2parna** [comment]
I think this issue has been addressed now.  Closes #564
