### ISSUE TITLE
Replacing robotics specialization with NwU's "Modern Robotics" from UPenn's "Robotics"

### ISSUE THREAD

**Issue by ccstr** [ossu/computer-science#565]
I was reading Hackers News yesterday. A link to a [free textbook](http://hades.mech.northwestern.edu/index.php/Modern_Robotics) called Modern Robotics was posted. Someone in the comments mentioned a corresponding [Coursera specialization](https://www.coursera.org/specializations/modernrobotics) from Northwestern University. The [currently suggested specialization](https://www.coursera.org/specializations/robotics) is from the University of Pennsylvania. It seems to me that the specialization from Northwestern University contains courses that are more contemporary and higher rated than the specialization from the University of Pennsylvania. I propose that the specialization from Northwestern University be recommended instead of the one from the University of Pennsylvania.

I haven't completed either specialization and I haven't read the textbook. I can provide a more informed suggestion once I have.

OSSU is the best source I've found for self-studying CS. Thanks to everyone who has contributed.

**Comment by slink007** [comment]
Looking forward to the answer on this.  I'm still working my way through the Core CS section but when I do get to the Advanced Applications robotics is likely to be the one (or one of the ones) that I go with.

**Comment by waciumawanjohi** [comment]
As both specializations are on the Coursera platform, it is much more straightforward to make an apples to apples comparison of the course ratings. You are correct that the Northwestern course has better ratings. Putting that in for the robotics specialization rec.
