### ISSUE TITLE
Suggestion: Udacity new courses

### ISSUE THREAD

**Issue by TheGeekiestOne** [ossu/computer-science#566]
Hi there, just wondering if new courses from Udacity will be a benefit to this list?

such courses:

Intro to Self-Driving Cars Nanodegree
AI Programming with Python Nanodegree
Become a Computer Vision Expert Nanodegree
Natural Language Processing Nanodegree

**Comment by jstnmchl** [comment]
My understanding of the Udacity Nanodegree programs is that they are paid content. Unless there are specific, non-paid components then I would refer back to the [FAQ](https://github.com/ossu/computer-science/blob/dev/FAQ.md):

> ### Does every resource in the main curriculum have to be free?
> Yes, because we have to draw a line. As soon as we require paid resources in the main curriculum, we might as well tell people to pay half a million dollars to attend a university. We are an Internet-based community of learners, not a business, so free is the most sensible price and ensures that the only price you need pay is the price of Internet access.

**Comment by waciumawanjohi** [comment]
Thank you for pointing out these resources. If they fit into v9 or a future version of OSSU, we will certainly include them!

I'll also include a link to [a course recommendation made by another student](https://github.com/ossu/computer-science/issues/530#issuecomment-436443065). This is an excellent example of the sort of analysis that can help everyone judge the place of a course in the curriculum.
