### ISSUE TITLE
Login with Github doesn't work

### ISSUE THREAD

**Issue by Turil** [ossu/computer-science#573]
The "Login with Github" Button on ossu.firebaseapp.com doesn't work, I get the following error (with Firefox 66.0.5):
```
{
        "error": {
                "code":"SERVICE_UNAVAILABLE",
                "statusCode":410,
                "message":"SDK Update Required: See https://goo.gl/2cKQWm.",
                "details":"SDK Update Required: See https://goo.gl/2cKQWm."
        }
}
```

**Comment by doct0rX** [comment]
Don't use firebase website it's no longer maintained! Just follow the GitHub repo and that's it.

**Comment by waciumawanjohi** [comment]
I share your frustration about this. I would suggest creating/adding to the issues page of the github repo for that project.

https://github.com/ossu/ossu-client/issues

Also note, the app reflects an old version of the curriculum recommendations. @doct0rX is right that the current curriculum can be found here: https://github.com/ossu/computer-science
