### ISSUE TITLE
How to Code: Simple Data Questions Nonexistent

### ISSUE THREAD

**Issue by cececvy1** [ossu/computer-science#576]
Hello!
In How to Code: Simple Data, some of the post video instruction questions are blank. Is it meant to have questions or are they only visible if you pay for the course?
Thanks in advance

**Comment by snowleo208** [comment]
Yes, it is only visible after you purchased the course. You can still view all the coding questions in the problem bank, which is at the top menu.

You can check out #569 for more details.

**Comment by cececvy1** [comment]
Alright, thanks
