### ISSUE TITLE
Why CS50 is not suggested as an introductory course given the popularity that it has?

### ISSUE THREAD

**Issue by carjuan** [ossu/computer-science#579]

**Comment by waciumawanjohi** [comment]
If you search for CS50 in the issues, you'll see many conversations about the appropriate place for the class in the curriculum.

This one in particular is relevant for the current recommendations for Intro to CS.
https://github.com/ossu/computer-science/issues/540

If you have feedback on your favorite Intro to CS Course, you can include it here:
https://github.com/ossu/computer-science/issues/548
In depth reviews which explain a course's strengths and weaknesses are always appreciated!
