### ISSUE TITLE
How to Code series, audit course will be no longer existing!

### ISSUE THREAD

**Issue by ceso** [ossu/computer-science#581]
Hi, how are you?

I just started with the serie of "How to Code" recommended on the Core CS and...once I started, I got this message on edX:

"Audit Access Expires Aug 26, 2019
You lose all access to this course, including your progress, on Aug 26, 2019.
Upgrade by Jul 29, 2019 to get unlimited access to the course as long as it exists on the site. Upgrade now"

tl;dr: from Aug 26 it looks like is not going to be free anymore (even just watch the videos).

Should be needed to look for some alternative?

**Comment by ruoshui-git** [comment]
I think EdX is doing that for many other courses now. When I tried taking
MIT's Intro CS with Python it was like this as well. However one year ago I
took the same course, but it had a different archive policy.

**Comment by marrets** [comment]
When the access will expire, just do another account of edx (even just for that course) and re-enroll. I completed the first and the second course in time, but not Sotware Construction: Data Abstraction, so I made a new account and re-enrolled.

**Comment by ceso** [comment]
> When the access will expire, just do another account of edx (even just for that course) and re-enroll. I completed the first and the second course in time, but not Sotware Construction: Data Abstraction, so I made a new account and re-enrolled.

uhmmm but the message sounds like the entire course is going to be closed for audit access, I mean I just enrolled yesterday and immediately that message appeared (is not like if I was already doing the course and that notification pop up).

**Comment by marrets** [comment]
> 
> 
> > When the access will expire, just do another account of edx (even just for that course) and re-enroll. I completed the first and the second course in time, but not Sotware Construction: Data Abstraction, so I made a new account and re-enrolled.
> 
> uhmmm but the message sounds like the entire course is going to be closed for audit access, I mean I just enrolled yesterday and immediately that message appeared (is not like if I was already doing the course and that notification pop up).

I know, that message appeared to me everytime that I enrolled for the first three courses. For example, when I enrolled (months ago) for How to Code: Simple Data, that message said that the audit access would have expired for me in March 20, 2019(or something like that), but after that date, the audit access for the course is not expired for everyone (in fact, you enrolled yesterday). That message says that the audit access expires for your account, and if you want unlimited access you have to pay. But you can just make another account to get around this restriction. Or at least, that's what I did.

**Comment by ceso** [comment]
@marrets ohh I got it know, thanks!

From what I read the course is based on the "How to Design Programs" book (https://htdp.org/2018-01-06/Book/), being that you did the courses, all the three courses are based on that book? or just the first 2? 
I'm asking because now, being that the course has that workaround, but that is based on that book, I started to doubt if I'll keep with just the book or the course/book.

**Comment by pachecohjr** [comment]
I have been lurking on this conversation and I must say, even though these courses are propietary, is there a way we can archive some of the lectures or lessons on these edX classes? I'd like to know which ones are being taken away, because I definitely enjoy some of them.

**Comment by Alaharon123** [comment]
The two How to Code courses are the two courses based on How to Design Programs.

The videos for How to Code are all on YouTube, but the projects are not

**Comment by pachecohjr** [comment]
Like commented earlier, it appears there will be a mass expiration of courses by the end of the month.

**Comment by pachecohjr** [comment]
"Audit Access Expires Aug 23, 2019
You lose all access to this course, including your progress, on Aug 23, 2019.
Upgrade by Aug 2, 2019 to get unlimited access to the course as long as it exists on the site."
 
That means the course could be completely removed from the page entirely.

**Comment by SleimiKhalil** [comment]
If in doubt, know that the course exists on Youtube as @Alaharon123 said. [https://www.youtube.com/channel/UC7dEjIUwSxSNcW4PqNRQW8w](url) I started this course about two months ago and my access audit has expired already!

**Comment by ceso** [comment]
Interesting!
THANKS a lot for the Youtube link, my only doubt now about it is, one in youtube is called "Systematic Program Design", meanwhile the one in edX is divided between Simple and Complex data, so basically, until what module in the youtube one will be the simple data, and in which one will start the complex?

**Comment by DevJ5** [comment]
Does anyone know if there are any answers available to the problems in the problem bank?

**Comment by kenuxi** [comment]
We could just map all problem questions to the problems in the book on https://htdp.org which always has a link to its solution. I suspect they are the same problems supplied in the edx courses that are now behind paywalls.

**Comment by waciumawanjohi** [comment]
This discussion is quite valuable. It's also replicated in a number of issues. To bring all of the issues and possible solutions together in one place, I've opened an RFC on the How to Code classes. Your input would be valuable! Comment here: #588

**Comment by timeneverdie** [comment]
Now nearly all the edx course has two important changes:

1. If you don't pay it, you will lose data and cannot access to it.
2. Some parts of course will be locked, like exercises and exams.

But these two now are not annoying for learning, except some greedy courses, they will cut off some good parts of course to let you pay.

And also, I found How to Code: Simple Data only has one chance to learn, or you need to register more edx accounts to enroll the course. I don't know why UBC do this. The whole How to Code courses are paid as you go.

**Comment by timeneverdie** [comment]
> Interesting!
> THANKS a lot for the Youtube link, I think I just will keep with the one on youtube + the book + download just in case all the things in "Problem Bank" in case they are referenced later in the course.
> 
> Btw, if someone has the same doubt I had (in edX is divided in 2 coureses Simple and Complex data, meanwhile in youtube just "Systematic Program Design"), the mapping between those I think is:
> 
> edX Simple data <--> module 01a BSL to 06a BSTs on Youtube
> edX Complex data <--> module 06b Mutual Reference to 11 Graphs on Youtube

Yeah, if you enroll these two courses, you will find you can only watch videos, why not watch them directly on Youtube?
