### ISSUE TITLE
Contribuiting To Open Source 

### ISSUE THREAD

**Issue by ganesh003** [ossu/computer-science#585]
At what point of ossu will the student be able to take part in open-source societies, like contribute to open source projects and other things?

**Comment by waciumawanjohi** [comment]
This can be a difficult question to answer. Contributions can happen at all sorts of levels. If you walked into a woodshop today, there would be _something_ you could do to help out. But it would pale in comparison to what you could do as a journeyman carpenter.

Once you've finished Core Programming, check out https://www.firsttimersonly.com/ It has resources to get people contributing to open source software. You may find a task that fits your skills.

Similar to https://github.com/ossu/computer-science/issues/585 I'm going to leave this open for a week to get a variety of voice.
