### ISSUE TITLE
Machine Learning course: opportunity for improvement

### ISSUE THREAD

**Issue by xxylem** [ossu/computer-science#592]
I recently completed the [Machine Learning course](https://www.coursera.org/learn/machine-learning) and I have a few comments about it:

1. The format is a little dry: many long videos (a few hours) with instructor followed by a quiz and assignment and the end.

2. The quizzes are infrequent and too simple. There is typically one or two quizzes per week, each of five questions. The questions are mostly multiple choice and just direct recall of information from the videos. They rarely require further thinking/extrapolation.

3. The assignments are shallow. They mostly require inserting one or two lines into a few files and then running to watch the helper code do the bulk of the work. The code to be added is just a direct translation from the given formulas to matrix operations, which has already been covered in greater detail in the LAFF course.

4. There is no additional/further reading/textbook/notes. The only extra info written down are the lecture slides, which are hard to interpret outside of the videos. I don't think it's enough to watch some videos. Further reading is essential.

Possible solutions:

- I read some reviews for the course on Coursera and one mentioned "Geoff Hinton's Neural Networks course". I couldn't find this course, only [these lecture videos](https://www.cs.toronto.edu/~hinton/coursera_lectures.html), but they are not much use on their own.

- I notice that there is a [specialisation](https://www.coursera.org/specializations/deep-learning) by the same instructor, Andrew Ng, on Coursera. Do you have experience with this? Maybe we could make students aware of the full set of courses.
 
- Perhaps we could provide further readings ourselves: relevant papers/textbooks etc.

My concern is that if we just have a course called "Machine Learning", students may get the impression that this is enough. If we are to compete with traditional university education, we should encourage students to go much deeper, which, at least near the start, requires a bit of a push.

**Comment by waciumawanjohi** [comment]
@xxylem 
We are aiming to recommend the equivalent of an undergraduate education in CS. And something to note is that the Ng's ML course is likely overkill for undergraduate requirements. This is not to say that an undergrad that wanted to pursue a career in machine learning should stop at this course, but just that the ML expectation of ALL CS students is not multiple courses (and indeed, is not a full course on machine learning).

The The Joint Task Force on Computing Curricula put out its CS curriculum recommendations in 2013. (A new edition is published roughly every decade)
https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf
Page 124 gives a chart and explanation of what undergraduate students should learn about Intelligent Systems. Reading through these, my concern is that OSSU's curriculum currently overweights ML and underweights other areas of AI.

If you are interested in evaluating courses against the requirements in this doc, I'd be very interested in your assessments and recommendations. One thing that we agree on, OSSU should iterate on its current course recommendation and ensure that students are being pointed in the right direction!

**Comment by xxylem** [comment]
Yes I see based on that doc that you are right, it probably is sufficient for an undergrad curriculum. Thanks for your help!
