### ISSUE TITLE
Login error on https://ossu.firebaseapp.com

### ISSUE THREAD

**Issue by Knouch** [ossu/computer-science#594]
Hello, it seems that you can't login with github on the website. The error message displayed in a new window when I am trying to login is as follows:
{
        "error": {
                "code":"SERVICE_UNAVAILABLE",
                "statusCode":410,
                "message":"SDK Update Required: See https://goo.gl/2cKQWm.",
                "details":"SDK Update Required: See https://goo.gl/2cKQWm."
        }
}

I just want to give a heads up, if this issue is already known, I'm sorry for wasting your time.

Kind regards,
Simon

**Comment by waciumawanjohi** [comment]
Simon,
Thanks for the heads up. Pointing out bugs is always helpful. Searching open issues can let you know if an error has already been raised and if there are efforts to address it. In this case, https://github.com/ossu/computer-science/issues/466 is aimed at issues with the Firebase app.
