### ISSUE TITLE
Provide course-specific advice.

### ISSUE THREAD

**Issue by xxylem** [ossu/computer-science#595]
I propose having a section accompanying each course to provide any good advice that previous takers of the course might have for future takers.

For example, I am currently taking the Computer Networking course and it has multiple issues with the quizzes/exams. E.g. the midterm exam asks a question about a topic covered in a lecture situated AFTER the exam (this out-of-order problem happens multiple times). Also, the provided answers to some questions are incorrect. Some quick advice to flag up the issue for future students to the effect of _"Warning: Known issues with quizzes/exams. If in doubt, search the course forum ("Piazza") for guidance."_ would save them time.

As a second example, all courses on the EDx platform could carry a warning regarding the current timeout/access issues. 

If we have a dedicated section for this, current students may be more inclined to add advice. This would save future students from asking the same questions and getting stuck repeatedly on the same issue.

What do you think?

**Comment by waciumawanjohi** [comment]
This sounds like a good idea. An advice google doc/wiki for each course could be simple and effective. It sounds like you already have content ideas for Computer Networking. Could you start one for that course and make sure it's publicly editable? We can link it on the main page. Point out in the Gitter that it's there for students to use. And we can ask learners to give us feedback on how helpful they found the page.

Thoughts?

**Comment by xxylem** [comment]
I have added this to the pull request #596. If you have any questions or comments, please add them there.

Thanks,

Josh
