### ISSUE TITLE
OS course website is down

### ISSUE THREAD

**Issue by MohammedAttya2** [ossu/computer-science#602]
ops-class.org - Hack the Kernel course website is down
> https://www.ops-class.org/ is unreachable.
> ERR_ADDRESS_UNREACHABLE

**Comment by keltor** [comment]
Doesn't solve the issue, but the source is all here: https://github.com/ops-class

**Comment by waciumawanjohi** [comment]
@pachecojr pointed out that some amount of the class is available at archive.org: https://web.archive.org/web/*/https://www.ops-class.org/

**Comment by ahmdsolmn** [comment]
The website is up again.
