### ISSUE TITLE
Hack the kernel is down

### ISSUE THREAD

**Issue by DevJ5** [ossu/computer-science#604]
Apparantly hack the kernel, i.e. [https://ops-class.org](url) is down.

Any substitute we can take is much appreciated.

**Comment by pachecohjr** [comment]
https://web.archive.org/web/*/https://www.ops-class.org/

Plenty of snapshots for the site. Anything missing here?

**Comment by waciumawanjohi** [comment]
This is a duplicate of https://github.com/ossu/computer-science/issues/602

Closing to keep conversation about this issue in one place.
