### ISSUE TITLE
Trello board update needed.

### ISSUE THREAD

**Issue by Ola-Sok** [ossu/computer-science#605]
In 038 - Reliable Distributed Systems, Part 1
The hyperlink's text is "Electricity and Magnetism, Part 1", Which links to Edx page with the "Reliable Distributed Algorithms, Part 1" course.

Just a typo, but still...
Thank you!

**Comment by manan2501** [comment]
Hey, It seems like the problem is solved. Can you please close the issue?

**Comment by Ola-Sok** [comment]
Still, the text of a link is 'Electricity and Magnetism, Part 1', which may need to be corrected.

**Comment by manan2501** [comment]
Yes, but url has been changed. And now it lands you on Edx page of  'Electricity and Magnetism, Part 1'.

**Comment by Ola-Sok** [comment]
Okay. Why would I care. Closing.

**Comment by Ola-Sok** [comment]
I confirm that the card for "Electricity and Magnetism, Part 1" links perfectly fine, but...
The issue is about a card with a current no. 038 which is titled "Reliable Distributed Systems, Part 1".
Links fine, though the text of a link says "Electricity and Magnetism, Part 1". 
It'd look more professional w/o mistakes like this, that's why I opened an issue. If you guys think it's irrelevant though—It's okay.
