### ISSUE TITLE
intro to CS Python for Everybody no longer free?

### ISSUE THREAD

**Issue by kacyian** [ossu/computer-science#612]
Perhaps I am mistaken, but from my understanding courses listed by OSSU should be freely available for all to use, without the need to pay. Is this no longer the case? 

https://www.coursera.org/specializations/python

**Comment by shawkyelshazly1** [comment]
I believe it is for free if you scroll at the end of the link there is a button on the left saying "Enroll For Free"

**Comment by MohammedBakr44** [comment]
You can apply for a financial aid if you cannot afford to pay for the specialization.

**Comment by kacyian** [comment]
Apparently you can still audit the course if you select each one individually. I thought it part of OSSU pollicy to ensure all courses are freely available to all. has this changed?

**Comment by waciumawanjohi** [comment]
@kacyian I believe that reading the FAQ will answer your questions:
https://github.com/ossu/computer-science/blob/dev/FAQ.md
