### ISSUE TITLE
Is 6.00.2x needed?

### ISSUE THREAD

**Issue by timeneverdie** [ossu/computer-science#620]
6.00.2x link is below:
https://www.edx.org/course/6-00-2x-introduction-to-computational-thinking-and-data-science-3

Since http://catalog.mit.edu/degree-charts/computer-science-engineering-course-6-3/ doesn't say 6.00.2 is required to graduate, so should I take part in?

Since 6.00.2x covers probability, should I learn it? Or which course listed covers probability?

**Comment by waciumawanjohi** [comment]
6.00.1x is recommended. Students are welcome to choose courses that they feel will benefit them. I personally tried out 6.00.2x. But you should feel free to proceed to the next recommended course of the OSSU curricula.

It is worth noting that OSSU recommendations add up to quite a large number of course hours. (Something that we intend to address) I would recommend forgoing 6.00.2x.
