### ISSUE TITLE
CS 50's link should be replaced by Official website

### ISSUE THREAD

**Issue by timeneverdie** [ossu/computer-science#622]
Here is CS 50's official website:
https://cs50.harvard.edu/college/weeks/0/

The experience on edx is not good. Official website is better and offers materials more than edx.

The only advantage for edx version is offering some shorts.

And I find a strange thing: even edx version says it's 2019 new course but the video is still 2016 old. Go to CS 50 official website, that's real 2019 new on Youtube. The contents of 2016 and 2019 may be the same, I don't know if anything changed or improved.

**Comment by waciumawanjohi** [comment]
@timeneverdie 
Is the link that you shared the page for students enrolled at Harvard? When I followed the link for submitting the first assignment, I was taken to a page to log in with Harvard credentials.

**Comment by timeneverdie** [comment]
> @timeneverdie
> Is the link that you shared the page for students enrolled at Harvard? When I followed the link for submitting the first assignment, I was taken to a page to log in with Harvard credentials.

But I don't see any assignment supported on edx. And most of all, the course version is different. I don't which one is mainly supported and maintained by Harvard. The number of weeks are different too.

**Comment by timeneverdie** [comment]
> @timeneverdie
> Is the link that you shared the page for students enrolled at Harvard? When I followed the link for submitting the first assignment, I was taken to a page to log in with Harvard credentials.

This is the test link: https://cs50.harvard.edu/college/test/, which allows the students write and submit codes directly on CS 50' web IDE.

**Comment by kishvanchee** [comment]
I asked [CS50 on reddit](https://www.reddit.com/r/cs50/comments/dtyhff/what_is_the_difference_between_contentproblem/) regarding this. Quoting a staff's reply

> CS50x 2019 (the current version) is based on the Fall 2018 Harvard CS50 course. The Fall 2019 Harvard CS50 course that you've linked is the currently running in person class. It will become the 2020 CS50x course on edX in January.

**Comment by botul** [comment]
niedz., 10 lis 2019, 03:57 użytkownik Kishore Vancheeshwaran <
notifications@github.com> napisał:

**Comment by thephong45** [comment]
Vào 17:37, Th 6, 15 thg 11, 2019 Paweł <notifications@github.com> đã viết:
