### ISSUE TITLE
Problem with Firebase curricum login 

### ISSUE THREAD

**Issue by daksh-goyal** [ossu/computer-science#623]
The login with Github option doesn't work; instead throws an error :-

code | "SERVICE_UNAVAILABLE"
statusCode | 410
message | "SDK Update Required: See https://goo.gl/2cKQWm."
details | "SDK Update Required: See https://goo.gl/2cKQWm."
Please help me out

**Comment by waciumawanjohi** [comment]
Unfortunately, the Firebase app is an unmaintained web site that reflects the curriculum from many years ago. You can try reaching out to the original developer. He comments in this thread: https://github.com/ossu/computer-science/issues/466
