### ISSUE TITLE
"Introduction to Computer Science and Programming Using Python (alt)" This course starts from 23/01/2020. Doesn't it break the criteria of the OSSU curriculum, 'Run regularly (ideally in self-paced format, otherwise running at least once a month or so)'?

### ISSUE THREAD

**Issue by daffyDuck0333** [ossu/computer-science#624]

**Comment by riceeatingmachine** [comment]
This might help https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/

**Comment by lctfwyt** [comment]
This may also help: https://courses.edx.org/courses/course-v1:MITx+6.00.1x+2T2019/course/  
Try altering the term and the year number to get the latest available course content.

**Comment by waciumawanjohi** [comment]
Good suggestions above. Historically, students have been able to access MIT's Introduction to Computer Science and Programming Using Python in a timely fashion. We'll pay attention if this is no longer the case and look for an alternative recommendation.
