### ISSUE TITLE
Intro CS

### ISSUE THREAD

**Issue by Alaharon123** [ossu/computer-science#626]
So Intro CS is a bit of a mess right now. MIT 6.0001 is followed by How to Code, which is beginner-friendly, but 6.0001 is not so there's a course before 6.0001 to teach you Python so that 6.0001 doesn't feel so overwhelming so fast. So you've got 3 intro courses right there because none of them seem to really do their job properly. There's also the problem of How to Code being on edX and 6.0001 being primarily on edX although that does have an ocw version.

I propose switching all of those out for [Berkeley 61AS](https://berkeley-cs61as.github.io/textbook.html). In the past this hasn't really been considered because it's based off of SICP (pretty much is SICP tbh), however, this self-paced version includes a Unit 0 that starts from the basics to make it suitable as a true intro class and Calculus is a corequisite rather than a prerequisite. Unfortunately I have not actually read through it, but right now the curriculum is enough of a mess that I felt it worth making this post anyway

**Comment by riceeatingmachine** [comment]
6.0001 is available here: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/

I hear there's a book even better than SICP called  Concepts, Techniques, and Models of Computer Programming although I haven't used either.

CS61A also has videos here: https://archive.org/details/ucberkeley-webcast-PL3E89002AA9B9879E?sort=titleSorter

It's actually the recommendation for programming on teachyourselfcs.com

**Comment by Alaharon123** [comment]
61A has newer videos than that even. I'm suggesting 61AS rather than 61A because 61AS is designed for self-study unlike 61A and because it includes a Unit 0 for people who have no experience with programming unlike 61A. This videos are from before 61A switched to Python though so they would be a good resource for anyone doing 61AS

**Comment by waciumawanjohi** [comment]
The intro courses just went through a major comment/revision process regarding the intro sequence. You can read those [here](https://github.com/ossu/computer-science/issues/589) and [here](https://github.com/ossu/computer-science/issues/588) as well as the conversations that they reference.

The suggestion of 61AS is an interesting one! The next time we are looking to overhaul the intro courses, we should take some time to explore the course (including feedback from students who have completed the class).
