### ISSUE TITLE
Best Computer Science Path

### ISSUE THREAD

**Issue by Al-Mansoori** [ossu/computer-science#627]
The **OSSU** computer science **path** is constrained by **Free** computer science course to satisfy people with certain conditions: 1) people that do not have money to pay for online courses and 2) people who try to avoid investing money in their self-learning.  _I urge you to make the **best** computer science path which does not have this free course limitation. As a result, the new path should bring the best courses from **free** online courses and **none-free** online courses._

Kind Regards

**Comment by xxylem** [comment]
If money is not an issue, perhaps doing a CS degree at a university would be the appropriate option? 
What would a none-free curriculum look like to you?

**Comment by ola-sk** [comment]
Or getting certified for the final courses for your path—the advanced and throughout ones can also nicely present your knowledge and skill w/o spending on courses layers below that lead to those.

**Comment by waciumawanjohi** [comment]
Valuable feedback. OSSU may develop a second curriculum listing that is not concerned with the cost of resources. If you are interested in contributing, please let us know!
