### ISSUE TITLE
Answer key to the exercises in Stanford's "Introduction to computer networking"

### ISSUE THREAD

**Issue by MRensen** [ossu/computer-science#628]
Is it possible to get or make an answer key to the exercises for above mentioned course? 

I repeatedly find myself unable to answer some of these exercises. The course has a button "show answer", but this only appears after you've answered the question. Now, when I'm unable to answer the question, there's no way to get an explanation or even correspondence with an instructor or aid to ask about it.

I'd suggest we create an answer key for this course on OSSU that OSSU students can consult when they find themselves stuck on an exercise. This would help greatly in that you don't have to simply skip these these exercises anymore, but you can figure out the answer, why that's the answer and where and how you've lapsed in your understanding of the subject and fix it.

Of course we can't give an answer key for the midterm and final, this would only apply to the unit exercises. The question remains however, does this violate the honor code?

**Comment by ola-sk** [comment]
I personally think that there should be a forum for everyone who is a participant in the OSSU curriculum so that all members that eg. take the OCW versions of some of MIT courses or don't know the answer and don't know where to get to know the stuff that is taught in the course more deeply, could have the opportunity to connect with other students and this way possibly get to know how to improve their understanding or get to know about some useful material to cover the topic of which they lack understanding. 
We should take into consideration that this curriculum can sometimes be the only point that connects learners, so there should be an effort taken to develop ways for making such interaction possible.
Hoping to contribute towards that in the future.

**Comment by xxylem** [comment]
Regarding the course "Introduction to computer networking" specifically, I did the course a little while ago. I remember some of the questions not making much sense and some of the given answers being incorrect. I wouldn't feel too disheartened if you can't get some of them.

The best place to ask for help would be on the course forum (they call it Piazza). When I couldn't answer a question, I searched on there and sometimes previous students had already discussed the question (and confirmed it was a dud, for example). You could also ask a question on there too, but it may take a while to get a response.

I highly recommend the optional reading (I think they list a few textbooks, I just chose one and read it cover to cover). The videos are OK but there's not enough in the course by itself, I think. This is a trend with quite a lot of courses though; if you find yourself struggling you probably need an additional text, the course videos tend not to go into enough depth (they take a lot of effort to make) and/or assume a lot of prior knowledge.

**Comment by waciumawanjohi** [comment]
I second xxylem's suggestion of using the discussion forums of the various courses. And also of searching out secondary sources of information.

> The course has a button "show answer", but this only appears after you've answered the question. Now, when I'm unable to answer the question, there's no way to get an explanation or even correspondence with an instructor or aid to ask about it.

If the question is not assessed, then I would encourage you to give your best answer and then check the feedback on that answer. This is often what we do with live teachers talking with us 1-1. So an answer key shouldn't be necessary.

If the question is assessed, then maintaining an answer key for future students would violate the Honor Code. https://lagunita.stanford.edu/tos_and_honor
