### ISSUE TITLE
Calculus 1A "Not currently available"

### ISSUE THREAD

**Issue by Pacteria** [ossu/computer-science#629]
Calculus 1A has been archived according to information given on [corresponding OCW course page](https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/).

**Comment by FinchYang** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sean Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 下午4:18
收件人:&nbsp;"ossu/computer-science"<computer-science@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ossu/computer-science] Calculus 1A "Not available" (#629)




Closed #629.

**Comment by xxylem** [comment]
Have you tried following the link and clicking "Enroll now"?

It says "This course is archived, which means you can review course content but it is no longer active." I believe you should still be able to access the course content.
