### ISSUE TITLE
PPA: test161 does not support for Bionic(Ubuntu 18.04) in osp-class.org

### ISSUE THREAD

**Issue by Artlist-creator** [ossu/computer-science#630]
I think you should update the operating system course in the curriculum.
 It is not possible to follow the whole course with the outdated toolkit.
Could you show me other courses to alter this OS course? Thank you!

Here the link to the source:
https://www.ops-class.org/asst/setup/#ppa

**Comment by xxylem** [comment]
I am just about to start that course. Would running an older version of Ubuntu as a VM be an option? It also says using Windows Subsystem for Linux is an option, have you tried that?

**Comment by Artlist-creator** [comment]
Yup.
The PPA is working on wsl2 on Ubuntu 16.04. 
I think I should stick with it for now.

**Comment by spamegg1** [comment]
I installed Ubuntu 16.04 Xenial in VirtualBox and it works there.
