### ISSUE TITLE
Software Construction: Data Abstraction "Not available"

### ISSUE THREAD

**Issue by Mughees605** [ossu/computer-science#634]
This course is not available, page says access expired on 27 November 2019

https://www.edx.org/course/software-construction-data-abstraction

**Comment by riceeatingmachine** [comment]
It's a terrible course, I recommend skipping the software construction and the other two courses altogether. The micromasters really goes to hell after the first two courses.

**Comment by TheSovIndividual** [comment]
Any viable alternative?

**Comment by ivicts** [comment]
https://www.edx.org/course/software-construction-data-abstraction
It says starts on 23rd Jan. Maybe a new term?

**Comment by AhmedGamal1496** [comment]
The only benefit of the course that it introduces you to the real world of programming. You take multiple files connected to each other through OOP, and you modify the code to suit your needs. But the instructor is not that good and the materials are not satisfying. 
You have two options: do it at a faster pace, then jump to other courses in the curriculum or search for any other Java OOP course on the web.

**Comment by TheSovIndividual** [comment]
I think I will stick with the course; real-world programming and debugging with JUnit sounds good to me. I will substitute the shortcomings in the material with the book [Think Java](https://www.amazon.com/Think-Java-Like-Computer-Scientist/dp/1491929561/ref=sr_1_1?keywords=think+java&qid=1579790932&sr=8-1) which is basically the same curriculum like the recommended alternative in the extras: [University of Helsinki Java MOOC](https://moocfi.github.io/courses/2013/programming-part-1/).
This way i'll also get the "micro masters" in case someone cares haha

**Comment by Alaharon123** [comment]
Can I recommend checking out https://web.cs.wpi.edu/~cs2102/b16/ and letting me know how it goes? The two resources you mention are for beginners whereas this is intended for people who have gone through HtDP. The only question is how friendly it is to self-learners. You'd likely find the resources you mentioned to be too slow. This might be a better route. Alternatively you can learn Software Construction with all the real world stuff via 6.005 on ocw

**Comment by waciumawanjohi** [comment]
Closing this issue because:
1)  A number of good suggestions have been made.
2) There is currently an RFC open to remove Software Construction from the curriculum. https://github.com/ossu/computer-science/issues/636
3) There are older discussions of alternatives to Software Construction. https://github.com/ossu/computer-science/issues/553
