### ISSUE TITLE
Change default branch to master.

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#638]
The default branch is currently `dev`. However, most projects use `master` as the default branch. This naming convention is baked into git. "the git init command creates [the master branch] by default" [Pro Git](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)

Following wide spread convention makes it easier for newcomers to contribute.

Any objections to fast-forwarding the `master` branch to the current state of the repo and making it the default? Objections to deleting the `dev` branch? (Dev could be resurrected for a grand rewrite, for example setting v9 in markdown)

Keeping this issue open for a week.

**Comment by xxylem** [comment]
This seems a reasonable change that would aid new students. There have been no objections in the past month. I think we can go ahead with it.

**Comment by codeisbeauty-m** [comment]
unsubscribe





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Josh Taylor"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午2:56
收件人:&nbsp;"ossu/computer-science"<computer-science@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ossu/computer-science] Change default branch to master. (#638)




This seems a reasonable change that would aid new students. There have been no objections in the past month. I think we can go ahead with it.

**Comment by waciumawanjohi** [comment]
Done
