### ISSUE TITLE
RFC: Remove Reliable Distributed Systems and put replacement in Extras

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#640]
**Problem**:
Reliable Distributed Systems is an elective level course that is only partially available.

**Duration**:
Feb 29, 2020

**Background**:
OSSU promises the equivalent of an undergraduate degree in Computer Science. In order to evaluate our recommended courses, we use the Curriculum Guidelines for Undergraduate Programs in Computer Science (CS2013). More information can be found [here](https://github.com/ossu/computer-science/blob/dev/extras/curriculum_guidelines.md).

CS2013 details Parallel and Distributed Computing as an essential knowledge area. But within this knowledge area, the topic of distributed computing is labeled an elective.

Separately, the current recommendations for distributed systems are Reliable Distributed Algorithms 1 & 2. Unfortunately, the assignments are unavailable. The first course has been offline for 2 years. The second course is still listed, but the virtual machine image used to distribute the programming environment is no longer available. The specification for the assignments in the second course are still available, it is possible that the programming environment could be created from scratch. Fortunately the lectures for both classes are available as a Youtube playlist.

There are two other courses that cover similar material. Both are free to audit (watch lectures) but require payment to view assignments:
_Cloud Computing Concepts, Part 1_ is the first of a 6 course specialization on Cloud Computing.
_Distributed Programming in Java_ is the last of three courses in a specialization. Being the last in the specialization, the class may require students to take the earlier courses to follow the material.

**Proposal**:
1) Remove Reliable Distributed Systems from the main curriculum.
2) Add Cloud Computing to Extras/Courses.

**Alternatives**:
a) Simply move Reliable Distributed Algorithms to Extras/Courses.

b) Place _Distributed Programming in Java_ in Extras/Courses. This choice would require some study to determine if this third course in the specialization can be completed without the previous two courses (Parallel Programming in Java, Concurrent Programming in Java). Students would be welcome to take these two other courses. Note that there is currently a free Udacity course with C++ assignments that covers the same topics as Parallel Programming in Java.

**Comment by spamegg1** [comment]
I think replacing RDS with the free Udacity course, but keeping it in the main curriculum is a good idea. 

I was very much interested in RDS (it's distributed computing in Scala, I am planning on taking the Functional Programming in Scala Specialization eventually, maybe go into a career in parallel/distributed programming) so it would be sad if this topic is removed from the main curriculum. Of course I can just do my own thing and stray from the main curriculum, but that will diminish the feeling of accomplishment, and as someone who just started Advanced CS, I can say that the motivation comes from finishing the main curriculum courses one by one and making progress. 

I did not even know that Extras existed; I don't think people will pay too much attention to things that are in Extras. It looks like a dumping ground of way too many courses; students would likely be confused as to which ones are worth doing. Of course if there is no good solution currently, then dumping things into Extras can be a temporary solution.

If the main curriculum is too bloated and needs to be trimmed then removing things (like the Software Construction courses) or moving things to Extras might be OK, but removing RDS from the main curriculum with no replacement feels like throwing out that particular topic altogether (there doesn't seem to be anything else that explicitly covers distributed/parallel programming).

**Comment by waciumawanjohi** [comment]
### Close of the Comment Period

**Findings**:
1) The topic of distributed programming is valued.
2) The extras section is not a clear resource for students.

**Response**:
1) I certainly appreciate student enthusiasm for a topic, but don’t think that alone can justify a course’s place in the core curriculum. One can imagine that at many universities there are well loved electives that students cherish, yet these courses remain elective. Our curricular guidelines state this is the proper place for Distributed Programming. Students should note that the related topic of parallel computing will remain in the core curriculum.
2) The Extras page can use some attention. I welcome suggestions or efforts to better organize the page.

**Conclusion**
Reliable Distributed Algorithms 1 & 2 will be removed from the curriculum. Cloud Computing Concepts, Part 1 will be added to the Extras page. The Udacity course Intro to Parallel Computing will remain in the required curriculum.

**Comment by waciumawanjohi** [comment]
@spamegg1 It sounds like you have the beginning of an RFC to replace _Hack the Kernel_ with _Three Easy Pieces_. I'd be very interested in such an RFC!
