### ISSUE TITLE
Stanford is retiring their platform

### ISSUE THREAD

**Issue by nickbeaird** [ossu/computer-science#642]
I received an email from the Stanford platform noting that they are deprecating their learning platform at the end of March. It would be nice to have an algorithms alternative.

**Comment by waciumawanjohi** [comment]
Yes, Stanford is retiring their free platform Lagunita. There are several courses on the platform that OSSU recommends.

[Stanford's FAQ](https://online.stanford.edu/lagunita-Platform-FAQs) points out that some courses have already been ported to other platforms. [Algorithms I is here](https://www.edx.org/course/algorithms-design-and-analysis).

There are still a number of Lagunita courses that have not been confirmed for future offerings. The courses currently in the OSSU curriculum are:
Algorithms II
Databases
Compilers
Automata Theory
Introduction to Networking

We will need to come up with alternatives for any courses that are not offered elsewhere.

**Comment by nickbeaird** [comment]
Great, thanks for writing me back. I am fine with closing this. It sounds like you are in the know!
