### ISSUE TITLE
Compilers course is going to be closed

### ISSUE THREAD

**Issue by diofeher** [ossu/computer-science#644]
Hello!

I just went to Stanford's website and it seems you cannot enroll anymore and the course is going to be closed.

https://lagunita.stanford.edu/courses/Engineering/Compilers/Fall2014/about

"This course ends at 12 noon Pacific Time on March 26, 2020. If a Statement of Accomplishment is available for this course, it will be available for download until March 31, 2020."

Do you know any other course that can replace this one?

**Comment by riceeatingmachine** [comment]
It's on archive.org: https://archive.org/details/academictorrents_e31e54905c7b2669c81fe164de2859be4697013a

**Comment by diofeher** [comment]
Thanks @riceeatingmachine !
