### ISSUE TITLE
I created a Discord server.

### ISSUE THREAD

**Issue by xxylem** [ossu/computer-science#662]
I created an OSSU Discord server. The link is [https://discord.gg/4PDbvp9](https://discord.gg/4PDbvp9) 

The idea is students can help each other/work together/discuss problems. This is the aspect that we're missing compared to traditional education, so maybe it will fill the gap!

**Comment by waciumawanjohi** [comment]
Always happy to see contributors jumping in with solutions to problems!

At the same time, it would be great to ensure that we don't replicate old problems. One issue that OSSU has had in the past is to have a multiple lightly populated pages on many different platforms. You can read some of the later posts in this issue for some examples:
https://github.com/ossu/computer-science/issues/495

What can OSSU do to ensure that a Discord server is improving the experience over the current tools?

**Comment by xxylem** [comment]
I understand that it's been discussed. We can do it as an experiment. If it works and lots of people use it, great, we keep it and maintain it. If it's not used, we shut it down.

I think it does fill a gap though, GitHub has an issues section, but lots of discussion points don't fit into that.

**Comment by xxylem** [comment]
In terms of improving the experience for students, it'll only be useful if it gets a large population. We could advertise it on the curriculum page. Something along the lines of:

"We are trying to improve student community engagement, so we've trialing a Discord at [https://discord.gg/4PDbvp9](https://discord.gg/4PDbvp9). Join the conversation!"

**Comment by Alaharon123** [comment]
You're not aware of the Gitter are you

**Comment by xxylem** [comment]
I wasn't, no. It's not listed anywhere except in closed issues. I'm happy to close up the Discord. But we should promote the Gitter on the front page with a direct link and explanation. New students shouldn't have to search in closed issues to find it.

**Comment by xxylem** [comment]
Oh sorry, CTRL-F didn't find it. There is a small link at the bottom. I think it should be much though! And near the top!

**Comment by waciumawanjohi** [comment]
Outcome of the issue is [PR 663](https://github.com/ossu/computer-science/pull/663)

Hopefully this will mean more students connect with the OSSU community!
