### ISSUE TITLE
Math for CS, no solutions

### ISSUE THREAD

**Issue by ChrisTsou** [ossu/computer-science#672]
As the title says, the Mathematics for Computer Science course doesn't have solutions for its problems.
Anyone knows a resource to practice the material covered there?

**Comment by Alaharon123** [comment]
The 2005 version has psets with solutions

**Comment by waciumawanjohi** [comment]
This commit adds that information to the curriculum: https://github.com/ossu/computer-science/commit/6f97c7b9d7afe01ae66691e82988324f4c543a23
