### ISSUE TITLE
RFC: Deprecate the changelog, remove comments about semver

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#674]
**Problem**:
The changelog is out of date and provides limited value.

**Duration**: 2020, April 15

**Background**:
OSSU historically maintained a changelog. In this log, OSSU stated that "This project adheres in spirit to Semantic Versioning." (Semver) Before today, the most recent change in the log was from 2017.

Today, OSSU does not attempt to adhere to Semver. The top commitment is to our mission, a path to a complete CS education using freely available online materials. In order to achieve that mission, OSSU has been evaluating the curriculum against [CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf). This has included proposals to de-emphasize some study and to elevate other topics.

Further, the changelog provides limited value. Individuals who wish to see what the curriculum looked like at any point in the past can simply use the git history. Any commit should have a comment explaining the change. This should include reference to an issue where contributors discussed the proposal. Maintaining the changelog simply creates a new document that must be updated and maintained with information that's already captured elsewhere.

**Proposal**:
Remove the changelog and the commitment to semver.

**Alternatives**:
1) Rededicate ourselves to semver. Require that all commits update the changelog as well. Here is [an article](https://www.elegantthemes.com/blog/wordpress/semantic-versioning) that is a proponent of semver. This option would require that OSSU determine what version the curriculum is currently at. The major version would likely change a number of times during the current evaluation of OSSU against the CS2013.

2) Commit to simply tracking major completed revisions. This would mean that after the current review is complete, the major version would be bumped to v9.

**Comment by nainardev** [comment]
was about create a issue abiut this... Thanks :+1:

**Comment by spamegg1** [comment]
Some people in Gitter chat were asking about the Changelog and were confused about the curriculum's update status. So I support the deprecation.

**Comment by SuiiCheung** [comment]
Hi,
Could you tell me whether I can get certification for this 2-year study
from OSSU?
I am a bit confused about how to begin this process.

Thanks for your help.

Shuyi

**Comment by nainardev** [comment]
Is a certificate is really needed?
https://github.com/ossu/computer-science/blob/master/README.md#congratulations

**Comment by aaronhooper** [comment]
If tracking only the major versions also includes keeping the changelog around for those, I would strongly support that alternative. I think having something that publicly documents these major revisions adds value to learners. Recording changes for anything lesser seems redundant for OSSU and, as mentioned, anyone who is interested in that can just review past commits.

**Comment by waciumawanjohi** [comment]
The comment period has closed.

Findings
Comments reflect broad agreement that the changelog need not be as detailed as it currently is.
Within this, there was support for the 2nd alternative. This would update the changelog only when the revisions for v9 are complete. This should be when the curriculum has completed being reviewed against our curricular guideline, the CS2013. I will put a note to this effect in the changelog.
