### ISSUE TITLE
Question about graphics programming languages.

### ISSUE THREAD

**Issue by DevJ5** [ossu/computer-science#675]
I was wondering about the c++ or java language requirement for the computer graphics course in Core applications. Thusfar these languages have not been covered yet, correct? I am unsure how to dive into c++.  I have found the MOOC from the university of Helsinki very helpful in learning Java but would like to learn c++ for this graphics course.

**Comment by aryzach** [comment]
I haven't taken the graphics course, but I think if you've taken all the classes up to that point, you shouldn't have a problem picking it up. Learning languages informally is also an important skill to have. I think a combination of the PL classes and learning C in CS50, and having some experience working with classes, interfaces, etc like in java, you'll be prepared.

**Comment by spamegg1** [comment]
If you took CS50 and got familiar with C, you don't need to worry about C++ in the Computer Graphics course.

**Comment by mutasimahmed** [comment]
you can do that too

**Comment by waciumawanjohi** [comment]
If  you decide that you would like a dedicated learning resource for C++, hackr.io is a good resource for finding learning materials related to a particular language.
Also check out old.reddit.com/r/cpp/ The sidebar includes learning resources.

**Comment by DevJ5** [comment]
Thanks for being so helpful, much appreciated @waciumawanjohi
