### ISSUE TITLE
Differences between git page and README

### ISSUE THREAD

**Issue by bazylhorsey** [ossu/computer-science#680]
OSSU on firebase has a completely different curriculum set than the README page on this repository. A bit of explanation would be helpful.

**Comment by waciumawanjohi** [comment]
Near the bottom of the README you can find this:
> There is an unmaintained and deprecated firebase app that you might find when searching OSSU. You can safely ignore it. Read more in the [FAQ](https://github.com/ossu/computer-science/blob/master/FAQ.md#why-is-the-firebase-ossu-app-different-or-broken).

**Comment by bazylhorsey** [comment]
Searched faq, missed it. Thanks for your time.

**Comment by waciumawanjohi** [comment]
Not at all! If you have a suggestion that would have made that information easier to find, let me know.

**Comment by Alaharon123** [comment]
It's been 7 months since @SergeyKhval was pinged and nothing has happened. That note is on this github, but not on the actual firebase site that Google links to. What would it take to just take the site down?
