### ISSUE TITLE
Remove Pro CS

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#681]
**Problem**:
Pro CS is arbitrary and not the appropriate tone.

**Duration**:
2020-April-01

**Background**:
Pro CS starts out by stating:
> After completing the requirements of the curriculum above, you will have completed the equivalent of a full bachelor's degree in Computer Science

This should be followed by, CONGRATULATIONS. And some quotes from Oh the Places You'll Go. At the end of the curriculum, hopefully students will know enough about CS and themselves to choose a path going forward. It's not clear that this is the place to include yet more courses.  But that's what Pro CS does.

It's not clear why the particular courses listed in Pro CS were chosen. Some may be graduate level work. But at the very least the Android Developer Nanodegree certainly is not.

The next section, "Where to go next" seems much more appropriate for the end of the curriculum. It gives some general advice (like a commencement address would). And is light in tone.

Proposal:
Delete Pro CS (while keeping Where to go next).

**Comment by aryzach** [comment]
I'd agree with this. Maybe a section of 'pro CS' resources in extras, where it's clear that these are some options after finishing everything. People should know what interests them after taking everything

**Comment by jasonsbarr** [comment]
That makes sense to me. Have an additional set of resources that's not listed with the main curriculum, maybe call it "next steps" or "after you complete the program" or something like that.
