### ISSUE TITLE
Add Game Dev Specialization to Advanced Applications?

### ISSUE THREAD

**Issue by spamegg1** [ossu/computer-science#685]
[https://www.coursera.org/specializations/game-development](https://www.coursera.org/specializations/game-development)

There are 8 advanced applications listed, and 3 of them are data related and very similar; I think the variety is a bit low. Also game development is a HUGE area of software these days. Multi-billion dollar business, bigger than Hollywood at this point. I think a lot of self-learners would be excited about it.

**Comment by waciumawanjohi** [comment]
As long as we have the Advanced Applications section, this specialization seems like a reasonable addition. (As we rework the curriculum, I would not be surprised to see that section redone in a serious way).
Can you make a pull request to add this? There's a [link in contributing](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md) that walks through how to do so.

@spamegg1 have you logged into Gitter recently? I've sent a message to you there, would like to talk about some other suggestions you've made before. I think you've got good ideas!

**Comment by spamegg1** [comment]
@waciumawanjohi Oh sorry, I logged into Gitter a few weeks ago but not since then. I'll check your messages, thanks for paying attention! 

OK I'll follow the guide to add it. (The one under "Non-substantive changes" right?) So I should close this now.
