### ISSUE TITLE
Trello board is out of date

### ISSUE THREAD

**Issue by sunn-e** [ossu/computer-science#687]
I was using the trello copy. The "022 - Algorithms: Design and Analysis, Part I" has link for course on langunita. The platform closed on 31/march/2020.
It would be great if you could update it on trello. 
Thanks

**Comment by waciumawanjohi** [comment]
There is a branch titled `JSON`. In that branch there is a file called curriculum.json
That file has the curriculum encoded as it currently stands.
Trello has an API.
It would be possible for someone to program an interpreter that takes the curriculum state from the JSON and uses it to update a Trello board using the API.

A good opportunity for an OSSUnian looking for a real world project!

**Comment by aislingdailey** [comment]
@waciumawanjohi I wrote a Python script to create new boards from the JSON you mentioned. 

There's an active pull request here: #699

**Comment by waciumawanjohi** [comment]
Thanks to @aislingdailey this issue can be closed!
