### ISSUE TITLE
Request for Comment: Replace Linear Algebra

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#693]
**Problem**:
The current Linear Algebra course focuses on efficient computer computation of matrices, rather than teaching students the theory and practice of linear algebra.

**Proposers**:
Alaharon123 and waciumawanjohi

**Duration**:
2020 May 4

**Background**:
Linear Algebra from Foundations to Frontiers (LAFF) has long been the recommended course for linear algebra. In 2017, we added the Essence of Linear Algebra because those videos so gracefully demonstrate the concepts within linear algebra. But even with this addition, LAFF remains a course focused intently on computation, slicing and dicing matrices as the professor would say. A good deal of time is spent reviewing how to get efficient computation of matrix operations out of an automated program. Rather than teaching efficient programming, OSSU is counting on the linear algebra course to teach concepts that students will leverage when studying machine learning or computer graphics.

An alternative comes from MIT. Gilbert Strang’s OCW Scholar course is put together with lectures, lecture notes, recitation videos, problem sets with solutions, and even optional references to a textbook. Strang teaches the material well, getting into the mindset of someone who doesn’t know the material and building up the student’s understanding. (Here is [an interview](https://www.youtube.com/watch?v=7UJ4CFRGd-U) where he discusses exactly this approach).

Strang is well known in the math world. He wrote two of the three most read textbooks on Linear Algebra (using [number of goodreads reviews](https://www.goodreads.com/search?q=linear+algebra&qid=) as a proxy for number of individuals reading). He has [recorded multiple math courses](https://ocw.mit.edu/faculty/gilbert-strang/), including 4 on Linear Algebra. There was a recent [HackerNews discussion](https://news.ycombinator.com/item?id=22382337) of Strang’s lectures and textbooks, the thread features a number of testimonials.

**Proposal**:
Replace LAFF with MIT’s [Open Courseware Scholar Linear Algebra course](https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/).

**Alternatives**:
- Keep LAFF. LAFF has been a long feature of OSSU. Our endorsement was even mentioned by the professor in a letter to the course’s students. The course [still posts to social media](https://www.facebook.com/pg/LAFFutX/posts/), indicating that there is someone to hear feedback.
- Replace LAFF with an applied linear algebra class. There are three such courses:
  - Davidson's [Applications of Linear Algebra](https://www.edx.org/course/applications-of-linear-algebra-part-1)
  - Imperial College of London's [Mathematics for Machine Learning](https://www.coursera.org/learn/linear-algebra-machine-learning)
  - Harvard's [Introduction to Linear Models and Matrix Algebra](https://www.edx.org/course/introduction-to-linear-models-and-matrix-algebra)
- There is a new (2019) [Linear Algebra](https://www.edx.org/course/linear-algebra-part-1-2) course from Rice. The lectures explain the material from the perspective of someone who already knows the material. It might be fine for a refresher, but is a poor match for OSSU students. More concerning, homework is behind a paywall, so there’s no way to actually practice it for free.

**Comment by spamegg1** [comment]
This may be a bit off-topic but right now I'm taking LAFF: Programming for Correctness (I'm on Week 5 right now), and it also suffers from the same issue. 

The 6-week course abandons the correctness proofs after Week 3, and becomes all about high performance algorithms of matrix multiplication after that. Has nothing to do with correctness in Weeks 4-6. We don't even write code; they have a code generator website called Spark, which, with some parameters, generates the MATLAB code for the homeworks. The "proofs" are also automatically generated as LaTeX files by the same system.

Also it doesn't teach at all how to obtain correctness proofs for literally any other algorithm in the world except very simple arithmetic or matrix algorithms. They mention Microsoft Research's programming language DAFNY in passing but that's it.

This is despite the fact that they have [yet a THIRD course](http://ulaff.net/) purely dedicated to high performance computing. This means that ALL THREE courses are focused on high performance algorithms.

All of this tells me that professor Robert van de Geijn is either unable or unwilling to separate his research focus from his courses. Correctness proofs + linear algebra + fast matrix algorithms are all bundled into one thing in his mind.

Don't get me wrong, I really like this guy and he is a pretty good teacher. Also it was super cool to see Hoare (inventor of Quicksort) as a guest, and to learn about Kazushige Goto and his handwritten high performance algorithms etc.

We might think about removing LAFF:PfC from Advanced Programming too. The first 3 weeks would fit more under Advanced Theory anyway. I think it would be much more useful if there was a course on Dafny programming or something like that.

**Comment by waciumawanjohi** [comment]
@spamegg1 
Good context about LAFF!

This issue won't propose any changes to Advanced CS. But you should feel free to open another issue that looks at the CS2013 standards and discusses whether Programming for Correctness is doing an adequate job meeting those for OSSU.

**Comment by spamegg1** [comment]
A great LA textbook from back in my days has just become freely available: [Sheldon Axler's "Linear Algebra Done Right"](https://link.springer.com/book/10.1007/978-3-319-11080-6)
This is the best book ever on Linear Algebra (from a math major's perspective).

**Comment by ola-sk** [comment]
I've taken and like Imperial College London's [Mathematics for Machine Learning](https://www.coursera.org/learn/linear-algebra-machine-learning).

**Comment by waciumawanjohi** [comment]
@spamegg1 Great find! When I mentioned Strang wrote 2 out of the 3 most read linear algebra textbooks, the 3rd textbook is Linear Algebra Done Right. Clearly a well loved text.

I've added it to Extras/Readings in this commit: https://github.com/ossu/computer-science/commit/1a8722d31736f06f24eb5094aa6d27cb7e3caa25

**Comment by Alaharon123** [comment]
I should say before this closes, I think the advice should be to watch Essence of Linear Algebra *alongside* whichever primary resource rather than before. It works much better for each to reinforce the other than to just get a whole bunch of theory with no practice followed by a whole bunch of practice with no theory. I'm oversimplifying/exaggerating, but I think the point stands

**Comment by waciumawanjohi** [comment]
Closing comment period a day early.

Findings:
There are a number of resources that students have used and liked. There are no objections to Strang's course. Other students have noticed the shortcomings of the current Linear Algebra recommendation.

Based on these findings, the current course will be replaced with Strang's _Open Courseware Scholar_ course.

**Comment by waciumawanjohi** [comment]
@Alaharon123 If you have an idea for how to represent the concurrent suggestion, I'd be interested in seeing a pull request for it. One thing to be aware of is the work to represent the curriculum in JSON that can then be translated to a trello board (or other format). See https://github.com/ossu/computer-science/issues/687 .
