### ISSUE TITLE
Stanford Databases is coming back in April 2020

### ISSUE THREAD

**Issue by gshaikov** [ossu/computer-science#695]
Should be on the lookout for when the content becomes available again. This course is the best one out there and nothing has come close so far.

The full statement:
"The Lagunita platform hosting Stanford's Databases MOOC was switched off in late March 2020, sadly coinciding with a time when free online courses couldn't be more helpful for the world. On the good side, all of the mini-courses are being ported to the EdX platform, and we hope to have initial no-cost availability starting in April 2020. Stay tuned."
Source: https://cs.stanford.edu/people/widom/DB-mooc.html

**Comment by waciumawanjohi** [comment]
Good to know! Closing this as there's no action to be taken now, but feel free to reopen the issue when the course is offered on edX.
