### ISSUE TITLE
Add link to pre requisites of some courses

### ISSUE THREAD

**Issue by manoloesparta** [ossu/computer-science#697]
I found the course on differential equitations (and partial differential equations) really makes shine in what is useful integrals and derivatives which are essential to many physics courses especially fro simulations and graphics.

**Comment by robbrit** [comment]
Differential equations are not generally included in a university computer science program. You're right that they are useful for physics simulations, but that's just one application of computer science techniques.

A top-tier school may include them as electives for a computer graphics or simulations track, so if we decide to have specializations like that we could throw DE in there.

**Comment by manoloesparta** [comment]
It is also necessary into digital circuits and in robotics, we have there three courses that need differential equations. 

I can do the research and find some differential equations courses for adding to the curriculum if people are interested.

**Comment by robbrit** [comment]
Sure, that'd be great, thanks! Yep it is very useful for the robotics course, I think this is a good example of an interdisciplinary specialization.

A concern I'd have here about branching too much into applications is that computer science touches _everything_. There's a very real risk of scope creep. Instead what you'd want in a curriculum are the core pieces of computer science that are either applicable to deeper computer science research, or used in the majority of applications. Programming and databases definitely fall into these categories; ODEs not so much. A good place for that is as a link in the prereqs for courses that benefit from material outside the core curriculum.

**Comment by manoloesparta** [comment]
I totally agree with that idea, we should add in the prereq sections links to the recommended courses you should take for that specific topic.

I was thinking about that since they removed the course about multi variable calculus and it's a prereq to probability and machine learning.

If you agree, I would like to change the title of this issue to "Add links to prerequisites courses" or do you think is more appropriate to open another issue and close this one?

**Comment by robbrit** [comment]
Nah just keep this one open, change the title to say "Add links to differential equations prereq" or something like that.

**Comment by manoloesparta** [comment]
I put some courses in the title because I can check also for the probability pre requisites (multi variable calculus)

**Comment by waciumawanjohi** [comment]
If I understand the issue, it is:
For courses that name a prerequisite, make that prerequisite listing a link.

If that is the case, I give it a thumbs up and would accept a pull request making that change.

**Comment by manoloesparta** [comment]
That's right, that is our intention if you agree feel free to react to this comment

**Comment by spamegg1** [comment]
A bit of a digression from this issue:

@robbrit Very nice comment about scope creep. I think this discussion shows the need to have more specialized curricula for separate paths in CS. There is already OSSU/data-science and OSSU/bioinformatics, there could be others too. 

Considering the fact that Specializations in Advanced Applications usually require "one year programming experience" or some equivalent, and the fact that Intro + Core is supposed to take two years, a more focused curriculum can help someone reach the Specialization faster, while avoiding topics not relevant to them (e.g. avoiding Diff Eq if they are not going to use physics simulations, etc.)

Back to the issue: yes please go ahead and make a pull request with the links to prereqs. You'll get a nice "Contributor" badge next to your name!

**Comment by waciumawanjohi** [comment]
I believe this commit closes the Issue. If that is not the case, feel free to reopen and provide more information on further needs.

https://github.com/ossu/computer-science/commit/9452a2001c1cd548b0b9d7a908c453d5a1fce28d
