### ISSUE TITLE
RFC: Change Prereq for Programming Languages Part A

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#716]
**Problem:**
The curriculum lists incorrect prerequisites for Programming Languages Part A.

**Duration:**
May 31, 2020

**Background:**
Programming Languages Part A currently lists as its pre-reqs: `recommended: Java, C`

However, this doesn't align with the instructor's recommendations. The course says that students should have some previous background coding and that 1-2 prior university courses should be fine. You can watch a video here where the instructor discusses expectations of prior student experience: https://www.coursera.org/lecture/programming-languages/recommended-background-k1yuh

**Proposal:**
Make _How to Code_ the prerequisite for Programming Languages Part A.

**Alternatives:**
Specify _1-2 previous college level courses_ as the prerequisite.

**Comment by waciumawanjohi** [comment]
Also, this is one of the rare courses where the prerequisite could be a link to the professor themselves explaining what students should know and be able to do.

**Comment by aryzach** [comment]
I support this change. I think this is a good place to just link directly.

**Comment by waciumawanjohi** [comment]
Putting this into action.

This commit resolves the issue: https://github.com/ossu/computer-science/commit/9edea7f7121428540efb1fd272315146260b6753
