### ISSUE TITLE
Lack of Academic Writing

### ISSUE THREAD

**Issue by navidalvee** [ossu/computer-science#720]
I took OSSU courses and I am currently a doctoral student
but the current curriculum has solved most of the knowledge except one academic writing though these classes are awesome. Many ppl here are brilliant and the community would have even greater contribution if there is a healthy emphasis on reading and writing research work. 
Below I found free courses in coursera for academic writing. Though I hope to get even better recommendations from the higher-ups

1. Grammar and Punctuation
https://www.coursera.org/learn/grammar-punctuation?specialization=academic-english

2. Getting Started with Essay Writing 
https://www.coursera.org/learn/getting-started-with-essay-writing?specialization=academic-english

3. Advanced Writing
https://www.coursera.org/learn/advanced-writing?specialization=academic-english

4. Introduction to Research for Essay writing 
https://www.coursera.org/learn/introduction-to-research-for-essay-writing?specialization=academic-english

5. Project; Writing a Research Paper
https://www.coursera.org/learn/academic-writing-capstone

Happy Learning

**Comment by waciumawanjohi** [comment]
These look like interesting courses. And I certainly value the written word. But these courses fall outside of the scope of OSSU. Our [curricular guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md) recommend that students are introduced to professional communication. But the expectation is that the equivalent of 1 lecture hour per week for a semester would be devoted to this learning. You can read more [here](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=202).

If after looking through the CS2013 you have a suggestion for how to best meet this curricular expectation, please do open a new issue.
