### ISSUE TITLE
Introduction courses appear to no longer have an audit option.

### ISSUE THREAD

**Issue by twangman** [ossu/computer-science#724]
Just started looking into this curriculum as a way to teach myself CS... this is awesome thanks so much for putting this together!

However the 2 coursera courses listed as the introduction, no longer seem to have an option to audit the class. Is there another place you would recommend to start?

**Comment by aaronhooper** [comment]
In the alt link there is one to [the edX version](https://www.edx.org/course/programming-for-everybody-getting-started-with-pyt) of Python For Everyone which looks like it's still free to take, but FoC is a Coursera exclusive I think, since I can't seem to find any alternative.

**Comment by Alaharon123** [comment]
They're both available, you just need to audit the individual courses rather than the specialization. Perhaps there should be a note there?

**Comment by aaronhooper** [comment]
Damn, I missed that. It looks like the "Try For Free" messaage appears on some courses but not others. The audit link does appear down below the ad if you click Enroll... just some aggressive advertising for the trial/subscription I guess.
