### ISSUE TITLE
RFC: LAFF On Programming for Correctness

### ISSUE THREAD

**Issue by spamegg1** [ossu/computer-science#734]
Problem: This course in Advanced Programming is too irrelevant, too specific, too research-heavy, full of repetition and tedium, extremely light on actual programming, and of somewhat low quality in its materials.

Duration:

July 20, 2020

Background: 

I wrote a lengthy review of LAFF [here](https://github.com/spamegg1/reviews/#laff).  I have read through all the electives of the Knowledge Areas in the CS 2013 document and this course does not really cover any of them in my opinion (except for Logic, which is covered elsewhere in the curriculum).

Proposal:

Remove it from the curriculum.

**Comment by waciumawanjohi** [comment]
I don't see any clear connection to the topics in CS 2013 either.

As an aside, I think there is an open question as to what exactly should be in "Advanced". Should Core be all topics in Tier 1, with Advanced covering topics in Tier 2 and Extras covering electives?

Either way, this course does not seem to target our curricular goals. I support removing it.

@spamegg1 can you set the duration to July 20, 2020? That will leave a month long comment period.

**Comment by hanjiexi** [comment]
I agree with removing it 👍️

**Comment by spamegg1** [comment]
@waciumawanjohi Updated the date, it was a typo.
> I think there is an open question as to what exactly should be in "Advanced". 
I have some ideas, stay tuned for my next proposal!

**Comment by spamegg1** [comment]
Making a pull request

**Comment by krishnakumarg1984** [comment]
@spamegg1 @waciumawanjohi  In the LAFF series (see [http://www.ulaff.net/](http://www.ulaff.net/)), there are __four__ courses. The first one is the foundational course. 

I read spamegg1's review of the 2nd course, _On Programming for Correctness_ , and their recommendation is __NOT__ to take it, and this was removed from OSSU. However, this is __intended__ as a course for research students (i.e. 6000 level graduate class), and is meant to be intentionally hand-wavy, and the instructor explicitly says so in the accompanying textbook and notes (see the ULAFF website).

On the other hand, the first course has some good reviews. This course is meant as a show-piece course, and is funded by the US National Science Foundation (grant ACI-1148125). The authors are world-famous researchers in the field, working at [TACC](https://www.tacc.utexas.edu/).  I work in the HPC area, and have met the TACC researchers and course leaders a few times at major conferences.  Linear Algebra is their research area, and they have written several major libraries in the field. 

I suggest a review/examination to include the 1st course in the series.

**Comment by waciumawanjohi** [comment]
_Linear Algebra: Foundations to Frontiers (LAFF)_ used to be the recommended Linear Algebra course. It was removed about a year ago. You can read more in the RFC here: https://github.com/ossu/computer-science/issues/693

**Comment by waciumawanjohi** [comment]
@krishnakumarg1984 , you note that you work in the HPC area. While I don't think that LAFF is appropriate for our Linear Algebra course, I could see a plausible place for it in an advanced section on High Performance Computing. Part of the challenge would be to determine what courses are appropriate for an undergraduate introduction to HPC. The ACM and IEEE wrote in their _[Computing Curricula 2020](https://www.acm.org/binaries/content/assets/education/curricula-recommendations/cc2020.pdf)_:

> High-performance computing (HPC) refers to processing data and performing complex calculations at quadrillions of calculations per second, orders of magnitude faster than ordinary high-speed computers [Raj1 p2]. HPC is essential for today’s popular computing areas such as artificial intelligence (AI), cyber analytics (CA), data science and engineering (DSE), and the internet of things (IoT). The diversity of HPC domains makes teaching HPC difficult. HPC education is commonly needed from undergraduate to post-graduate levels because of HPC’s importance, from computing to non-computing disciplines. A variety of practice based HPC teaching and talent training methods have been widely recognized and implemented in recent years [Che1,Che2,Che3]. But there are still many challenges for incorporating HPC into computing and engineering curricula [Che3 p2,Raj1 p5]. Creating competencies that incorporate the wide range of HPC knowledge, skills, and dispositions may further serve as a useful guide to curriculum development [Raj1 p7].


I could imagine an RFC for 3-5 courses that would make up a section on HPC in [Advanced CS](https://github.com/ossu/computer-science#advanced-cs). If that RFC quoted relevant sections from the papers cited in the CC2020, it would enable many OSSUnians to participate in the discussion in an informed way. Does that sound like something you would like to take on?

**Comment by krishnakumarg1984** [comment]
> _Linear Algebra: Foundations to Frontiers (LAFF)_ used to be the recommended Linear Algebra course. It was removed about a year ago. You can read more in the RFC here: #693

Precisely my issue here. #693 deals with removing the __2nd__ course in the series _On Programming for Correctness_ based on spamegg1's detailed review.  I am wondering if the first course in the 4-part series should be the Linear Algebra course here?

**Comment by waciumawanjohi** [comment]
> #693 deals with removing the 2nd course in the series On Programming for Correctness based on spamegg1's detailed review.

That's not the case.

You can read [the commit](https://www.edx.org/course/linear-algebra-foundations-to-frontiers-0) that resolved #693.
