### ISSUE TITLE
First course (How to Code: Simple Data) is inactive on edX

### ISSUE THREAD

**Issue by jamwil** [ossu/computer-science#739]
The enroll screen states that the course starts on the current day (June 26 in this case), however the course dashboard indicates that course access is expired:

> How to Code: Simple Data
> UBCx - HtC1x
> Access expired on Apr 25, 2019 for How to Code: Simple Data

I don't believe I have ever signed up for this course before. Is anyone else seeing the same thing?

**Comment by s7oev** [comment]
Unfortunately, you have probably enrolled and forgot about it.

edX has introduced this "feature" relatively recently - once you enroll for a course to audit (i.e, free version), you are given access for the nominal length of the course. After this, the access is revoked.

The only possible workaround is a completely new account.

**Comment by jamwil** [comment]
Well shit. I guess that's not so hard. Thanks!

**Comment by Jack-Works** [comment]
Having this problem too. Sad
