### ISSUE TITLE
Precalculus

### ISSUE THREAD

**Issue by mohamednehad450** [ossu/computer-science#740]
Hi everyone,

is it okay to take the Precalculus course on KhanAcademy instead of futurelearn?

**Comment by waciumawanjohi** [comment]
Yes, we are recommending the resources that we think are most appropriate, but every student makes modifications that bit themselves. Khan Academy creates high quality math resources.

**Comment by krishnakumarg1984** [comment]
> Yes, we are recommending the resources that we think are most appropriate

@waciumawanjohi Could you please elaborate on this a bit, or point to a discussion where a comparison was made. I searched with various keyword combinations on the issues in this repository, and did not find anything comparing the Khan Academy precalculus course vs FutureLearn's. 

Why does OSSU think that FutureLearn precalculus is the "most appropriate"?

**Comment by waciumawanjohi** [comment]
Why is the precalculus course from the University of Padova in Extras/Courses? The largest factor is that it has [very high reviews](https://www.classcentral.com/course/precalculus-8988). In addition, I reached out the course developers with a question about future availability of the course and received a response within hours. Between good reviews and responsive faculty it earned a place in Extras.

**Comment by krishnakumarg1984** [comment]
@waciumawanjohi thanks a lot for explaining this.  I am right now in Week3 of this Pre-calculus FutureLearn course. I can also vouch that it is of a high standard. I have a PhD in engineering (with a thesis involving multivariable calculus, PDEs etc) and generally good at math, but I openly admit that in the first 2 weeks, I am learning quite a few concepts that I simply did not know or had forgotten before.  Highly recommend this course for the good teaching style and quality of content.

**Comment by krishnakumarg1984** [comment]
> Why is the precalculus course from the University of Padova in Extras/Courses? The largest factor is that it has [very high reviews](https://www.classcentral.com/course/precalculus-8988). In addition, I reached out the course developers with a question about future availability of the course and received a response within hours. Between good reviews and responsive faculty it earned a place in Extras.

@waciumawanjohi You have now contradicted your previous statement. This high-quality pre-calculus course offered by Univ of Padova on FutureLearn has just been replaced in a recent PR #786 with Khan Academy. This is vacillation and confuses new entrants to OSSU.  I am just taking the FutureLearn pre-calculus and I can absolutely vouch for its high quality.
