### ISSUE TITLE
OSSU Bachelor of Science in Computer Science Degree 

### ISSUE THREAD

**Issue by mattoy77** [ossu/computer-science#742]
Dear OSSU Students and Community:

On behalf of the Asia Caribbean Open Institute, I hope this finds you safe and well during this challenging time.

With sincerest thanks to OSSU Founder, Mr. Eric Douglas @ericdouglas, we wish to inform to you that we are working towards making the OSSU Computer Science project into a Bachelor's degree that will be made available to underprivileged students from developing countries across the globe. 

Our distance learning online Institute was built on the ideals set by U.N. Sustainable Development Goal No. 4 which aims to "ensure inclusive and equitable quality education and promote lifelong learning opportunities for all". The Institute is an advocacy initiative of the Caribbean ASEAN Council, an international socio-civic, non-government and non-profit organization established in Switzerland. Our registrar and academic representative, the Eastern Caribbean-Southeast Asia Chamber, is an NGO registered with the UK Register of Learning Providers. We strongly believe that education should be free and not only available to those who can afford it.

The Institute already offers Business programmes and awards Swiss degrees and diplomas. We will be including the OSSU Bachelor of Science in Computer Science (BSc-CS) as our latest programme. Just to be transparent, there is no intention to reinvent the wheel, change the effective OSSU curriculum or interrupt the affairs of the OSSU community. Our objective is to provide an opportunity for graduates of the OSSU CS programme to be competitive in the labour market by being able to present a degree certificate from our Institute.

We are ironing out details with our legal advisors in Geneva and London and will hopefully roll out the programme in the next few days. Rest assured, as part of our commitment to Mr. Douglas, we will make sure that current OSSU students and those that have finished the OSSU CS curriculum (with uploaded peer reviewed projects) can take advantage of this new development.

To learn more about our Institute, please visit http://www.asiacaribbean.institute

Thank you and we look forward to your support.

With kind regards,

- Matthew Pajares Yngson
Advisory Board Chair of the Asia Caribbean Open Institute
Representative Councillor of the Caribbean ASEAN Council

![OSSU CS Degree Collaboration](https://user-images.githubusercontent.com/67460639/85942924-7ba84880-b8e1-11ea-98af-fa9996a91189.jpg)

**Comment by spamegg1** [comment]
Very cool!

**Comment by mattoy77** [comment]
Thank you for the kind words and congratulations for finishing the OSSU CS programme! 

Yes, our primary intention is to provide free, if not extremely affordable education to students mostly in developing countries but our doors are very open to students from developed countries that don't want the burden of student loans. We know this is a major issue in the U.S. and we have been trying to address this matter since our advocacy started. Education laws are complex and vary depending on the country. Private for profit-making bodies have always been at the center of the student debt crisis. Unfortunately, we don't have the same funding as University of the People but we are doing what we can to alleviate the lack of more accessible education.

Our objective is to prove that self-paced education is as viable if not better than formal education in the labour market. We believe self-taught learners have a disciplined mindset and are more focused. I have personally taken around 50 different courses throughout the years from Coursera, edX, Futurelearn, and other MOOCs as well as from the Open University UK, the UN's UNITAR, Microsoft, Google, HP, etc. All of this combined learning has always been difficult to prove in the workplace because human resource professionals have always been instructed to look for a "real degree". We aim to make a dent in that traditional HR thinking and due to the pandemic, online learning is now an acceptable reality.

With regards to our requirement of being "underprivileged", we follow the UN's guide for developing countries and least developed countries but this is only a guide. Unlike Coursera, we don't make it difficult and waive fees whenever we can because each student is individually assessed at the application stage. Though some students from specific countries are automatically granted a reduced enrollment/registration fee, all students pay the same graduation fee because there is more worked involved. We only charge a nominal fee and by global standards, this is very low. Our Bachelor of Business Administration (BBA) will cost a total of €350 Euros which is probably cheaper than most desktops, laptops, and mobile devices nowadays. There is also no automated graduation process, each student will be individually assessed and for the degree programmes, an interview will be conducted by a member of our Advisory Board. Our BBA also requires a thesis defense.

The Institute is built on progressive flexibility and we will ensure that it stays that way or it defeats the entire purpose. 

We should be able to launch the OSSU CS programme before the end of the week. Our degrees and diplomas have been certified by UK solicitors/notaries so we just want to make sure that this is possible for the CS degree as well. We'll definitely give some concession to members of the OSSU community that have finished taking it and want a certificate to prove their accomplishment. To give you an idea, here's the verified certificate of our most recent graduate.

![Verified-Certification-front-back](https://user-images.githubusercontent.com/67460639/85962798-77bf0980-b967-11ea-8ada-9315a22d6b4a.jpg)

**Comment by spamegg1** [comment]
That sounds awesome! 

Thanks for the very detailed explanations. The low cost (€350 Euros sounds very affordable indeed) and the bureucratic ease should certainly give relief to a lot of learners. 

We should probably look up that UN guide and provide a link to students here so they can have an idea of what to expect.

> Our objective is to prove that self-paced education is as viable if not better than formal education in the labour market. We believe self-taught learners have a disciplined mindset and are more focused.

I agree, that is my goal as well. Unfortunately as far as I know, I'm the only one who finished so far (maybe someone can correct me). But the chance to get an actual degree will probably attract and motivate a lot of new learners. Once you make it official, we should announce it around here.

Maybe you could give a few details about the interview process so students can have an idea what to expect. I suppose it would be conducted over the internet? (flights would cost too much obviously) Does it take several days? Is there a written part or a submission? Is it like a job interview, or rather more academic in nature and spirit? 

Thanks a lot!

**Comment by waciumawanjohi** [comment]
Hi, I'm one of the current maintainers that Mr. Douglas mentioned. Please email me directly at code@waciuma.com. I'll make sure that the other maintainer of OSSU is included in our conversation.
