### ISSUE TITLE
Any alternatives to How to Code: Simple Data?

### ISSUE THREAD

**Issue by CBury** [ossu/computer-science#743]
I just started this course in the new "paid" Edx model and most of the exercises are not even visible to Audit students.  I'am feeling a little useless watch the classes and do not try the exercises.

**Comment by waciumawanjohi** [comment]
As stated in the curriculum:
> The How to Code courses are based on the textbook [How to Design Programs](https://htdp.org/2003-09-26/). The First Edition is available for free online and includes problem sets and solutions. Students are encouraged to do these assignments.
