### ISSUE TITLE
RFC: Software Engineering: Introduction and Software Development Capstone Project

### ISSUE THREAD

**Issue by spamegg1** [ossu/computer-science#747]
Problem: 
[Software Engineering: Introduction](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x) (SEI) and [Software Development Capstone Project](https://www.edx.org/course/software-development-capstone-project-ubcx-softengprjx) (SDCP) are mostly behind a paywall and are very poorly reviewed/supported.

Duration:
August 20, 2020

Proposal:
Replace them with [Fullstack Open](https://fullstackopen.com/en) (FSOpen).

Alternative:
Replace them with [CS50](https://cs50.harvard.edu/)'s second half, [Web Track](https://cs50.harvard.edu/x/2020/tracks/web/), and its [final project](https://cs50.harvard.edu/x/2020/project/) (preferably a web project).

Background:
I had many people ask me whether I took these two courses.
DISCLAIMER: I DID NOT FINISH these courses. (As far as I can tell, very few people did.) So I would love to hear your thoughts.

However I enrolled in both and browsed through the content, watched the videos, downloaded and looked at the source code.

I was neither able to even see any quizzes or exams in SEI because they were all behind paywalls, nor to attempt programming assignments in SDCP (I remember SDCP saying "audit learners can only submit once every 60 hours" but also saying "graded assessments are paid only!"). Then I quickly lost access to SEI. I even made a second edX account with a second email and enrolled, but eventually I lost access to that enrollment as well. 

The main point of contention comes from [a very detailed review](https://www.classcentral.com/course/edx-software-development-capstone-project-8198) from one of two poor (as in pain, not money) students who endured these courses for months and even paid money for them. One of them is a very long review, and it touches upon the rest of the UBC Micromasters program too, but please read it.

It is not logical to rely on two very negative reviews. So I looked for some [positive](https://www.classcentral.com/course/edx-software-engineering-introduction-8205) [reviews](https://www.coursetalk.com/providers/edx/courses/software-engineering-introduction) too (which were not very helpful), and combined it with my own experience. Also I went out of my way to take another class to learn the same subject from a highly acclaimed resource and make a healthier comparison. 

There are actually a few points where SEI + SDCP is better, or offers something FSOpen does not. Overall I think FSOpen is VASTLY superior.

Details:

Comparison of SEI + SDCP and FSOpen:

SEI + SDCP | FSOpen
:-- | --: 
U of British Columbia | U of Helsinki (well known for high quality CS courses) 
SEI very briefly teaches software methodologies: Agile, Sprint, Waterfall, how to write requirements/specification etc. | Does not cover software methodologies (can be covered easily with some reading, also covered by Software Architecture and Design in Advanced Programming) 
Videos (of high production quality, but of dubious value, and some irrelevant/untested by instructor's own admission) | No videos, but extremely comprehensive text, with tons of references to industry authorities and standards 
Does not teach the languages/tools used: Typescript, Node, Webpack. Must learn yourself|Teaches EVERYTHING, line by line, from scratch. Nothing assumed
Test/grader code is hidden|All code is fully open source
No solutions|Full solutions provided
SDCP has very difficult assignments, many students stuck. Requires teammates.|Simpler, easier exercises in smaller chunks that still teach all the skills. Can be completed solo.
Teaches object-oriented design patterns in Javascript | No OOP-style JS, but many other programming/design patterns taught (functional JS, avoiding mutating state directly) 
Running example code in SEI (web Mario game) provided "as-is" | Running example code is constantly updated after adding code in each section, with each evolution of the code available for download in different branches 
Significant time limitation on edX platform if you don't pay | No time limit, self-paced
All assignments, quizzes, exams behind paywalls. Even if you pay, no feedback for wrong answers on multiple choice questions|No quizzes, exams or graded assignments (but tons of programming exercises), instead it is project-based, do-it-yourself, free-open style learning
Not updated (last commit 3 years ago), abandoned by its instructors even for paid learners. Tons of unanswered questions in discussion boards|Updated yearly to catch up with all recent changes in web development, best practices; active repositories (last commit just a few months ago)
SEI teaches old style asynchronous callbacks, which leads to "callback hell". Must learn Async Promises yourself for SDCP (some dead links). |Teaches the new standard of "promise-based" callbacks, promise-chaining, async/await pattern
Does not teach latest tools/libs, You have to figure it all out yourself through searches, Stackoverflow etc.|Teaches many modern popular tools/libs: React, Express, Node, MongoDB, Heroku, Mongoose, ESLint, Axios, Typescript, Webpack, many popular Middleware libraries
Must pay to get code graded. No free certificate. Some promise of "Career Development Program" if you pay|Free certificate without any grading, Free U of Helsinki credit for people w/ Finnish social security number, chance to job interview with startup companies
Automated testing through Mocha and Chai|Teaches to write own tests in Mocha, mongo-mock. Also teaches testing React apps with Jest, and end-to-end testing with Cypress.io
Backend uses CSV and XML data with queries in Extended Backus-Naur form (a fairly complicated schema) |Backend focuses mostly on JSON data with queries in NoSQL variants like MongoDB (more modern)
Spends all of second course to make a RESTful frontend, backend, database query app. Very simple frontend |The same is accomplished by the end of Part 3 (of 9), then goes into much more detail and advanced modern topics (GraphQL, Redux, Typescript, custom React hooks etc.) By the end, 5-6 simple working web apps and 1-2 complex, very modern apps with custom hooks and CSS styling

**Comment by aryzach** [comment]
I've taken 1/3 of Fullstack Open and support this. I like it especially because it's one of the few applied / non-theory courses in Core CS, and web dev is a CS application where a lot of people end up working.

**Comment by waciumawanjohi** [comment]
I have heard the handful of students that have tried Software Engineering: Introduction (SE) and Software Development (SD) Capstone Project were not fans. I'm very open to replacing or removing it.

I like FSOpen. I don't have any problem recommending it to a student that wants to get into web development. 

But I'm not sure that FSOpen serves the purpose of a general software engineering course.

If we take the CS2013 guidelines and see that SE and SD don't meet requirements, we should remove those courses. We should not add FSOpen until we see that it meets unfulfilled reqs of the CS2013.

In the interim, I'm happy to merge in a pull request adding FSOpen to Extras/Courses, or to replace Full Stack Web Development in Advanced Applications with FSOpen.

**Comment by spamegg1** [comment]
@waciumawanjohi Sounds good. I did not know what to look for in the CS2013 guidelines, so I took the existing courses as the point of comparison, assuming they already covered what needs covering. It's true FSOpen is more of a programming course, not CS/SE.
