### ISSUE TITLE
Clarification needs on whether the introductory courses are just single courses or entire specialisation?

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#759]
In the intro CS section, the two courses listed **python for everybody** and **fundamentals of computer science** are both long specialisations on Coursera, consisting of multiple courses. 

The number of hours is listed as `58` and `123(?)` for these two courses respectively, and it is not directly clear whether we should judge whether it is single course or all the courses in the specialisation combined? Do the hours account only for the time spent on video lectures, or does it budget for the assignments and self-reading time?

It would be helpful if these entries were clarified as:

`python for everybody (single course)`  or `python for everybody (specialization)` etc.

**Comment by spamegg1** [comment]
I agree there needs to be clarification. There is quite a lot of confusion about this on Gitter chat. Many beginners come and ask about it.

Py4e is a standalone course, not on Coursera, so it's not a specialization, but I think you were just using that as an example. I don't think there is any confusion about Py4e. It's a "single" course so it takes 58 hours.

The main confusion is with Fundamentals of Computing. The current link goes to a Specialization, which implies that all of the Specialization must be taken. But I guess that's not very clear. The 138 hours is the combined total of all the individual courses. I guess that's not very clear either. 

A lot of beginners feel like they have to pay Coursera. Finding the individual course links, then finding the "Audit" links is quite tricky. Many on Gitter chat expressed doubts and frustration, and some people were willing to pay just to get over the frustration, until we explained to them how to find the Audit links. 

Now think about those who were too busy or too shy to come to Gitter... they might have paid already. OUCH.

There are explanations in the FAQ about Coursera but beginners usually would not know to look there. Most people won't look past the "front page." There is an explanation about Specializations right before Advanced Applications, but beginners would not know to look there either. 

I would propose replacing the single Fundamentals of Computing Specialization link with 7 individual course links. The total of 138 hours can be broken down into the 7 respective courses, or converted to "hours/week" (there are breakdowns on the Syllabi of individual courses). There can be a short explanation that these individual courses are short and that they are meant to be taken as a whole.

There is a bit of an issue with this. It might pollute the page with too many links, and it might scare beginners away or push them towards Py4e.

I think there can also be a broader discussion about whether a Specialization like FoC is appropriate in the Intro section at all: 
- The "Algorithmic Thinking" courses cover very, very advanced topics that are covered much later in Core Theory (graph search algorithms, connected components, the Master Theorem, Dynamic Programming, Clustering algorithms). I think these are way too difficult for beginners. Not to mention the unnecessary repetition in the curriculum.
- Coursera's Specializations are designed to give wide coverage as a "complete package" standalone mini-curricula in their own right. They are designed with the idea that students who take a Specialization will only take that Specialization, and then move onto starting their careers (therefore they provide very broad coverage, touching upon many things from Intro, Core, even Advanced CS Knowledge Areas). They do not fit very well into a broader curriculum of other courses, except maybe at the end.

It might be better to remove FoC entirely (all the Knowledge Areas that it covers in CS 2013 are already covered by other courses), or restrict it to the first 4 courses.

However I'm not going to open an RFC. I haven't taken FoC and I'm really busy. Please someone else do it, if you agree. It would be better coming from someone who finished FoC, who can give a review.

**Comment by waciumawanjohi** [comment]
@krishnakumarg1984, @spamegg1 You both make great points. I've written up an RFC that I believe addresses the concerns you raise. Your feedback there is welcome.

I'm closing this issue, but if you don't feel the RFC addresses the concerns, feel free to reopen this.

**Comment by krishnakumarg1984** [comment]
It's unclear whether all 5 courses of Py4E specialisation are recommended.

**Comment by waciumawanjohi** [comment]
The current link is to py4e.com and the intention is for students to complete the course. I've seen conversations about whether less than all the chapters should be recommended. If such a consensus emerges, we'll change the rec.
