### ISSUE TITLE
futurecoder

### ISSUE THREAD

**Issue by alexmojaki** [ossu/computer-science#760]
Hi! 

I'm developing a free open source online platform/course for complete beginners to teach themselves coding in Python. See the [GitHub repo](https://github.com/alexmojaki/futurecoder) for more information or try out the [demo here](https://futurecoder.herokuapp.com/).

It's looking pretty good so far, and when it's ready I'm confident that it can be extremely helpful to anyone learning how to code. I've added some awesome features that no other online courses have, and there's more to come. However, it's a big project and I'd be foolish to try and do the whole thing on my own. "If you want to go fast, go alone. If you want to go far, go together."

I'm posting this here because I'm looking for people who might be interested in contributing, either for coding the platform or for writing course content. I imagine that a community of people invested in open source education is a good place to ask. I hope me asking here is OK, the gitter channel didn't look right and I couldn't see any other alternative.

If anyone is interested, or knows someone who might be, please contact me at alex.mojaki@gmail.com.

**Comment by spamegg1** [comment]
I left a comment in your repo under Issues, check it out.
