### ISSUE TITLE
Deep Learning for Computer Vision

### ISSUE THREAD

**Issue by mberen** [ossu/computer-science#762]
I really enjoyed the coursera ML course from Andrew Ng! Afterwards I decided to explore more ML courses and I found this course: [https://web.eecs.umich.edu/~justincj/teaching/eecs498/](https://web.eecs.umich.edu/~justincj/teaching/eecs498/). All materials are free including assignments and lecture recordings, and it goes more in depth and is more up to date compared to the coursera course (which is especially important for ML since the field is moving so fast). I think it would be cool if this could incorporated some way, either in the curriculum or listed as an extra.

**Comment by waciumawanjohi** [comment]
That does look like an interesting course.

If there are contributors that are interested in creating an "Advanced Machine Learning" (Or Advanced AI, or Advanced Intelligent Systems), I could imagine this course fitting in.

As it is, this course is much more advanced and specialized for the core curriculum.

I will note, one need for the OSSU curriculum is to identify a course that more closely aligns with our curricular guidelines. As you note, the Ng course is a popular and enjoyable intro to deep learning. But it is a fairly narrow look at AI. Our guidelines suggest that students should be learning a wider variety of AI tools (such as hill climbing and A*). You can read more on page 121 of this doc: https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf

I'll leave this issue open for a few weeks in hopes that it inspires some contributors to propose an update to OSSU's AI coursework.

**Comment by mberen** [comment]
I agree, this definitely feels advanced and specialized, although I would say that lectures 1-12 are actually fairly generic (the vision stuff doesn't come out until 14 onwards). I'm up to lecture 6 right now and it does some very good explanations of concepts that were glossed over in the Ng course. 

I would personally love to see an "Advanced Machine Learning" track! OpenAI has some courses that may be worth looking into if something like that is attempted [https://www.coursera.org/search?query=deeplearning.ai&](https://www.coursera.org/search?query=deeplearning.ai&)

**Comment by waciumawanjohi** [comment]
Closing this issue as promised. Contributors are still encouraged to develop an Advanced Machine Learning section. Such a section should be based either on the [elective Intelligent Systems topics listed in CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=124) or some other similar standards guide for ML.
