### ISSUE TITLE
RFC: Standardize Intro to Programming

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#763]
**Problem**:
Intro to Programming is different in format and approach from the other sections of OSSU.

**Duration**:
Aug 15, 2020

**Background**:
The Intro to Programming (hereafter referred to as ITP) courses were added after acceptance of this [RFC](https://github.com/ossu/computer-science/issues/589). At the time, I hypothesized that giving students choice about the intro course would lower the debate about intro courses. My personal assessment is that this has been moderately successful. At the same time, this structure has come with downsides:
1. By giving students choice between two entry points, some students join the Gitter to ask which they should take. This has happened about a half dozen times since the adding ITP.
2. Some students have taken both of the ITP course options. This is not desirable, OSSU wants students to advance in the curriculum, and does not recommend taking excessive intro classes.

The two options were both Coursera specializations. Rather than link to the individual courses, there was a single link to the specialization. This led to issues:
1. Because individual Coursera courses can be audited, but entire specializations, students regularly ask in the Gitter about the need to pay.
2. Students have not been clear if the time estimates are for the whole specialization or just the first course in the specialization, as demonstrated in this [issue](https://github.com/ossu/computer-science/issues/759).

One of the courses, Python for Everybody (Py4E) has a freely available course site from the course creator. OSSU now recommends students use that site.

While the two options are meant for absolute beginners, they go to very different depths. Fundamentals of Computing (FoC) takes twice as long as Py4E. In this extra time, FoC covers more material. This leads to issues:
1. Students are meant to take different courses following their intro, depending on which path they chose. After FoC, students should take Missing Semester. After Py4E students should take Introduction to Computer Science and Programming using Python.
2. It’s not clear that all of the material in FoC is appropriate for students new to programming. In a recent [issue](https://github.com/ossu/computer-science/issues/759#issuecomment-666249721), a contributor (@spamegg1) noted that FoC goes quite deep into algorithmic complexity, which goes beyond the goals of an Introduction to Programming, or even an Introduction to Computer Science.
3. The advanced material in FoC is covered later in other OSSU courses.

It should be noted, there have been no complaints about either course. There have been a number of students who have praised (Py4E). When students have asked for recommendations of which course to take, there have been contributors that recommend Py4E and others that recommend (FoC).

**Proposal**:
To simplify the Intro to Programming section, OSSU should recommend only Python for Everybody. Doing so will address the above issues. There is no expected degradation of the curriculum, as Py4E is already a recommended course.

**Alternatives**:

1. Rather than recommending just Py4E, OSSU could recommend only FoC. This does not seem appropriate because of the questions about FoC’s depth.

2. Keep the curriculum as it is.

**Comment by waciumawanjohi** [comment]
Contributors can view the proposed change [here](https://github.com/ossu/computer-science/pull/764).

**Comment by spamegg1** [comment]
Very nice! Totally behind this. Awesome work as usual @waciumawanjohi

**Comment by kassumanete** [comment]
Im going to weigh in with my limited knowledge here. As an introductory course, FoC might go into a lot of depth, but I feel like the deeper topics covered in FoC are quiet simply put 'Fundamentals', which are of extreme importance to CS.
These topics might be covered later in OSSU, but I personally feel like being introduced to them early on will  help solidify them, and the redundancy will also help make them stick easier.
I propose option 2, keep the curriculum as is, yet put a note stating that it goes in depth. Some sort of warning?
Amazing write up though, and very well explaine! @waciumawanjohi

**Comment by krishnakumarg1984** [comment]
One thing that still remains unclear is the `number of hours` field. Is this the overall number of hours the student is expected to work (including video lectures, assignments, recommended readings, quizzes etc.)?

**Comment by waciumawanjohi** [comment]
@krishnakumarg1984 The duration and effort should be an approximation of total time committed, including watching lectures and completing assignments. These are generally taken directly from the hosting platform; both Coursera and edX report these numbers and we simply repeat that information here.

**Comment by krishnakumarg1984** [comment]
Thank you! I am doing the python for everybody specialisation in Coursera. 

I think it's certainly more than 58 hours.

**Comment by spamegg1** [comment]
https://www.coursera.org/specializations/python
Towards the bottom right of the page it says:
>>> Approx. 8 months to complete
Suggested 3 hours/week

That would make it `3 * 4 * 8 = 96` hours total.

**Comment by waciumawanjohi** [comment]
It's made more complicated by the fact that Py4E is on multiple platforms. I took the estimates from edX, which suggest 7 weeks for each course (there are 2) and 2-4 hours per week.

Py4E on Future Learn is similarly 6 weeks each for 2 courses, and 4 hours per week.

But perhaps the true solution is to stop trying to report effort and duration. The information is available through the platforms offering the courses. It's arguably of limited usefulness for students that are intending to take 20+ courses sequentially. The number that OSSU should be attempting to measure is how long does it take to complete the curriculum.

**Comment by spamegg1** [comment]
> But perhaps the true solution is to stop trying to report effort and duration. 

Yes, probably. Students can figure it out on their own from whatever platform they are using. If anyone asks, we can help them on Gitter.

**Comment by krishnakumarg1984** [comment]
There are further important considerations.

The Py4E website does not contain everything that Coursera offers. i.e. although the two platforms have a large intersection (~90-95%), they are not identical. For example, forums discussing assignments, tidbits on computing conversations with the instructor etc. (the conversations are on YouTube, but Coursera links to them directly at the end of each week for every course).

There is an even more important thing now. Coursera has been updated to integrate Py4E website in the curriculum. i.e. the click-through 'next/previous' pages to be marked complete fully mention Py4E website. Even the assignments require download of text files and example python files from the Py4E website.

Well, even the bespoke assignments autograder developed by Dr Charles at Py4E can automatically send grades to Coursera. The course website is mentioned in videos and the grading explanation is provided by Dr Charles.

I know Coursera pushes hard to make students pay, but having taken this specialisation, I think that this is the better superset.


Regarding the effort required, the 90-130 hours ballpark seem to be okay to me.

Final important thing: EdX only has course 1 and course 2 of the py4E textbook (only until chapter 11) and should not be used for providing time estimates.

**Comment by waciumawanjohi** [comment]
### Close of the Comment Period

**Findings**:
1) This RFC had very low engagement, with only 3 commenters and the proposer.
2) The effort/duration estimate for Py4E is currently undercounted.
3) Support for keeping FoC was voiced.
4) Support for removing FoC was voiced.

**Response**:
1. The intro courses of OSSU used to generate great amounts of debate and eat up lots of time and energy. That this is no longer the case suggests that most students and contributors are largely satisfied and unworried about the outcome of this iteration. That is a good outcome!
2. In supporting keeping Fundamentals of Computing there was a suggestion that FoC be preceded with a warning. This seems problematic. The section is already preceded by text explaining that FoC goes to greater depth than Py4E. But students still ask in gitter what the difference is between the courses, suggesting a warning may not be efficacious.
3. It seems clear that the duration estimate for Py4E should be raised.

**Conclusion**
The proposal will be merged in and the estimate for duration will be raised to 34 weeks.
