### ISSUE TITLE
Career guidance

### ISSUE THREAD

**Issue by karmicscientist** [ossu/computer-science#767]
Am a hospitality professional who has recently moved into digital marketing.
I would like to learn indept about computers but dont have thee money or time to pay for University.
Will this course help???

**Comment by waciumawanjohi** [comment]
1. This curriculum covers the material of an undergraduate degree in computer science. This is _very_ different from a degree in digital marketing. If you are only interested in topics related to digital marketing, I would advise finding a curriculum targeting your area of interest.
2. This curriculum is designed to minimize the financial cost of learning. It is perfect for those without the money to attend school.
3. This curriculum is time intensive. We estimate that it will take a student 2 years of dedicated study to complete. If you cannot devote to study, it will not be possible to complete the curriculum.

**Comment by karmicscientist** [comment]
Thank you for your reply.
I have another question!

So i have very basic computer understanding. Where would you suggest a novice like me should start learning from & what tonlearn first.
I am facinated by computers, but just took a different career path.
I dont wish to make it my main stream career, but i want to be smart in it.
This is becoming a hobby for life kind of pursit.

Please share your insight.

Thanks & regards

**Comment by waciumawanjohi** [comment]
This course may suit your needs:
https://www.edx.org/course/cs50s-understanding-technology

But honestly, this is outside of our expertise.

**Comment by karmicscientist** [comment]
Thank you
