### ISSUE TITLE
Is this suitable for an above-average 16 y/o having a computer aptitude?

### ISSUE THREAD

**Issue by Chaku-Daku** [ossu/computer-science#769]
I want to self-learn CS at a kinda comprehensive level.
I am fluent with the Physics and Maths used here, at least for the CS Into Courses.
I am a bright student and am well experienced with computers.
I am interested in CS, and am not in any doubt regarding it.
My experience in computers come from years of Googling how to do stuff and the gift of  some geeky cousins which built my analytical, like that guy who has been downloading pirated games since he was 6 and would research where it went wrong whenever any of his pirated games didn't work, and then, in the due course of time, learnt about stuff.
We have, in school. been taught Intro Level JAVA.
So, I have a good deal of Computer Experience, but not a lot of CS Experience. 
(I know this kinda sounds like I'm a braggart, I'm trying not to make it so, but I kinda suck at writing skills, whoopsie.)

**Comment by Chaku-Daku** [comment]
I'm nothing like gifted, but I'm actually at a good level.

**Comment by waciumawanjohi** [comment]
It sounds like you have an appropriate background to begin studying the courses in OSSU. And it sounds like you have drive and motivation to tackle the subject. Go for it. And let us know in [Gitter](https://gitter.im/open-source-society/computer-science) how it goes.
