### ISSUE TITLE
RFC: Replace Electricity and Magnetism

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#772]
**Problem**:
Electricity and Magnetism are more than the prerequisite knowledge for the follow on courses on Computer Structures

**Duration**:
Aug 30, 2020

**Background**:
There have been [questions in the past](https://github.com/ossu/computer-science/issues/668#issuecomment-599241388) about the appropriateness of the Electricity and Magnetism courses (E&M1 and E&M2).
These courses do not cover curriculum in the CS2013 (either core or elective). As such their only justification for inclusion in the curriculum would be as a prerequisite. The courses are currently listed in OSSU’s curriculum as prerequisites for Computation Structures 1: Digital Circuits.
But Computation Structures 1: Digital Circuits on Coursera details the following as the prereqs:
A working knowledge of electrical fundamentals (voltages, currents, simple components) or [CornellX ENGRI1210x: The Computing Technology Inside Your Smartphone](https://www.edx.org/course/the-computing-technology-inside-your-smartphone).
E&M2 course in particular goes far beyond voltages, currents, simple components, teaching, “magnetic field, how it is created by currents and magnetic materials, induction and inductors, and AC circuits.”

**Proposal**:
- Remove E&M1 and E&M2.
- Add [The Computing Technology Inside Your Smartphone](https://www.edx.org/course/the-computing-technology-inside-your-smartphone).

**Alternatives**:

1. Remove E&M1 and E&M2. In the pre-req section of Computation Structures 1 write _A working knowledge of electrical fundamentals (voltages, currents, simple components) or [CornellX ENGRI1210x: The Computing Technology Inside Your Smartphone](https://www.edx.org/course/the-computing-technology-inside-your-smartphone)_.
2. Keep E&M1, while dropping E&M2. From the course description E&M1 “serves as an introduction to charge, the electric field, the electric potential, current, resistance, and DC circuits with resistors and capacitors.”
3. Keep the curriculum as it is.

**Comment by spamegg1** [comment]
Something wrong with the title? "RFC: Standardize Intro to Programming"

**Comment by hanjiexi** [comment]
I am puzzled why the Computation Structures courses list as their prerequisite "A working knowledge of electrical fundamentals (voltages, currents, simple components) _**or**_ CornellX ENGRI1210x: The Computing Technology Inside Your Smartphone" (emphasis mine), as if these were comparable. The syllabus of the CornellX course does not appear to teach electrical fundamentals... it's more like a casual survey of computer systems topics, some of which is covered already in Nand2Tetris.

Given the irrelevance of electricity and magnetism to the rest of this curriculum, I think we should eliminate E&M1/E&M2. I have a feeling that it doesn't really need to be replaced with anything; I vaguely remember some students of Computation Structures saying that prerequisites were overkill, and as was mentioned, electricity and magnetism are not required in 2013. If we must insist on a replacement, I would suggest we replace it with the smallest, simplest possible thing we can, like an optional sequence of (very) quick explainer videos.

**Comment by spamegg1** [comment]
@hanjiexi That student you vaguely remember is probably me. That's what I suggested a few months ago, but I'm fine with the proposal. Anything in the right direction is good. I think Nand2Tetris 1 is good enough preparation.

**Comment by waciumawanjohi** [comment]
### Close of the Comment Period

**Findings**:
1. There is general support for removing E&M1/E&M2.
2. CornellX ENGRI1210x covers similar topics to a course already in the curriculum.

**Conclusion**
E&M1/E&M2 will be removed. The Prerequisite for Computation Structures 1: Digital Circuits will be Nand2Tetris II.
