### ISSUE TITLE
In HELP.md, change chat room platform to discord

### ISSUE THREAD

**Issue by faishalirwn** [ossu/computer-science#781]
I think in the "Ask in the chat room" section of HELP.md, Gitter should be replaced with Discord since OSSU has moved to Discord.

Link: https://github.com/ossu/computer-science/blob/master/HELP.md

**Comment by spamegg1** [comment]
@faishalirwn Good catch! 

Why don't you make a pull request with this change? You can change the text to say something like: "Each course on the curriculum has a Discord chat link in its Discussion column that you can use to talk to other students and ask for help".

This can help: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by waciumawanjohi** [comment]
Resolved by the above PR.
