### ISSUE TITLE
Trello template showing extra courses

### ISSUE THREAD

**Issue by pedrorrivero** [ossu/computer-science#787]
In the Trello template there is one extra course which does not show up in the curriculum page : 

> **Subsection**: Intro CS - Introduction to Programming
> **Course**: [Fundamentals of Computing](https://www.coursera.org/specializations/computerfundamentals)

**Comment by krishnakumarg1984** [comment]
The link is broken as well.

**Comment by pedrorrivero** [comment]
There are also two courses on Electricity and Magnetism which don't show up in the main curriculum.

**Comment by waciumawanjohi** [comment]
@krishnakumarg1984 Which link?
@pedrorrivero Fixed both of the issues you mentioned.

Thanks for the sharp eyes from both of you!

**Comment by krishnakumarg1984** [comment]
@waciumawanjohi The link to 'Fundamentals of Computing' in the quoted text by the OP.

**Comment by pedrorrivero** [comment]
@krishnakumarg1984 the link worked fine for me, it no longer matters though! Thanks for putting all this together @waciumawanjohi!

**Comment by waciumawanjohi** [comment]
Ah. Problem solved! The trello board no longer references that course, which was previously removed from the CS curriculum. 

To note, changes to the board that is linked on the CS curriculum won't update any copied board that a student has made.
