### ISSUE TITLE
Redundant Discord Link 

### ISSUE THREAD

**Issue by StevenKJo** [ossu/computer-science#790]
**Problem**:
Having a table attribute for each course directing to the same Discord server 37 times is redundant and a waste of table space. [Commit Addressed](https://github.com/ossu/computer-science/commit/c6b2e818742a38f530a8c0d84ff5f791b85b210b#commitcomment-42411332)

**Background**:
I loved that OSSU finally changed from Gitter to Discord, the channel organized community participation now its awesome. However as @waciumawanjohi stated in [issue 733](https://github.com/ossu/computer-science/issues/773) some information on a table can be duplicative and a waste, even though it links to a different discord channel it is not valuable to spam a redundant link 37 times to the same Discord server, even less valuable if you already joined the Discord and you can switch within channels inside the server. Maybe just improving the visibility of one single good joining link to the Discord server achieves the goal of optimizing community participation. 

**Proposal**:
Remove the 37 times redundant link from each table cell.

**Alternatives**:
- Increase visibility of the 1 single link from the community section.
- Use the space to provide bigger value that impacts students career path or at least not add unnecessary clutter to the curriculum. 
- Perhaps once for each section (Intro, Core, Math, etc.) instead of once for each listed course will at least reduce the 37 times spammed link to 9 times. At least its an improvement.

**Comment by waciumawanjohi** [comment]
For context:
This change was made in response to the discussion "Future of Cohorts" in the Cohorts repo (which has since been archived). The idea came from @spamegg1 who wrote at the time,

> Most people who ever come across OSSU will have a lazer sharp focus on the curriculum and nothing else. I never knew Gitter, Cohorts, or even Extras existed until recently. And I had been visiting the Curriculum page regularly for almost 2 years!
> 
> Also people will not read the "prose" inside README. They will just scroll down to the list of courses. Then some of them will come to Gitter and ask questions that are already answered in the "prose".
> 
> Therefore: on the curriculum, right next to each course, we must have links directly to a current cohort taking that class and its Gitter/whatever chat room. RIGHT NEXT TO EACH COURSE is by FAR the most important thing here. Kinda like this (just a mock-up):
> 
> Courses	| Duration	| Effort	| Prerequisites	| Students currently taking this class
> :-- | :--: | :--: | :--: | :--:
> [How to Code - Simple Data](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x)	| 7 weeks	| 8-10 hours/week	| none	| [Chat with your cohorts](https://gitter.im/open-source-society/computer-science)

> This way the cohorts/chatrooms are ANCHORED both in the curriculum and in people's minds. So the social aspects must be directly integrated into the curriculum.
> 
> It would make sense to have PERMANENT cohort/chatrooms for each class,

**Comment by waciumawanjohi** [comment]
I believe that @spamegg1 's hypothesis has been borne out. Since adding the links next to each course we have seen a remarkable jump in student participation in OSSU chatrooms. That participation is valuable, it's not clear to me what we could tell students that would be more important than, "If you want to talk to others taking this class, you can do so here."

**Comment by StevenKJo** [comment]
I agree with you and @spamegg1 that having really visible its really important for student participation, and maybe just having the community section is not enough for visibility. 

However I believe that whats been borne out its that Discord works better than Gitter because of its channels feature not the unnecessary 37 times redundant link to each course adding to the unnecessary clutter the curriculum has already. 

The discord server its long overdue and you never supported it since [issue 495](https://github.com/ossu/computer-science/issues/495#issuecomment-425270225) or maybe longer. Its awesome that you finally changed your mind, kudos for you and the good that made to the community and its participation. I love it!

So yeah, I agree with you guys that the link to the discord server should be more visible than it is right now just in the community section. But i dont think the most optimal solution its to spam the link redundantly 37 times!

**Comment by rachel83az** [comment]
Perhaps once for each section (Intro, Core, Math, etc.) instead of once for each listed course?

**Comment by waciumawanjohi** [comment]
This Issue has been open for a few months and has not attracted a wide base of support. While I agree that the current layout is a bit clunky, I do think that one of the valuable things that OSSU does is give like-minded CS self studiers a forum for discussion and support. I'm hesitant to make a change that makes that less visible. We should keep this feedback in mind during any future overhaul of the curriculum's UI.
