### ISSUE TITLE
Add quick Regexps course

### ISSUE THREAD

**Issue by rachel83az** [ossu/computer-science#796]
Regular expressions are extremely important in computer programming but Py4E barely scratches the surface. I suggest adding https://regexone.com/ at some point in the course. It should only take a couple of days to complete but should also provide a more thorough understanding of exactly how regexps work.

**Comment by waciumawanjohi** [comment]
Hi @rachel83az .
Can you provide more justification for adding to the curriculum? As noted in our [Contributing](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes) page, successful critiques of the curriculum will point out ways that OSSU is failing to uphold our curricular guidelines.

**Comment by oNjEncUREn** [comment]
Finding a place for regular expressions in the curriculum is tough.  The only place they're mentioned is in the Algorithms section under Automata Theory.   With that said, regular expressions are something developers will use thoroughly in their careers and should be something OSSU covers. 

With that said, I think there is a place for a regular expression course under the CS Tools section.

**Comment by spamegg1** [comment]
I promised myself I would stay out of this, but...

Since you haven't taken it, you might be unaware, but all the RE related stuff on page 60 of CS 2013 (DFAs and NFAs and their equivalence to RE) is covered by the Compilers course.

**Comment by qiujiangkun** [comment]
Regular Expression is a useful tool, but not worth adding to the curriculum as a whole course. I haven't seen any universities do so

**Comment by waciumawanjohi** [comment]
Adding to spamegg's observation, CS2013 specifies learning about regular expressions under the Knowledge Area _Algorithms_ and the topic _Basic Automata Computability and Complexity_. The OSSU course covering Automata is Theory of Computation. This course lists regular expressions as part of the curriculum.

**Comment by waciumawanjohi** [comment]
This proposal has had a few months to gather contributor feedback. Reading through the above:
- Study of regular expressions is part of our curricular guidelines. We have courses that address these guidelines.
- As well as being a computation theoretic topic, regular expressions are a useful day to day tool. There is some support for adding this tool to the CS Tools section of the curriculum, but it is not an obvious majority.

That said, we do keep track of "high-quality courses that, for one reason or another, didn't make it into the curriculum". @rachel83az , would you make a PR to add https://regexone.com/ to the CS Tools section of [extras/courses](https://github.com/ossu/computer-science/blob/master/extras/courses.md)? I will merge that in. It may be that in the future more students will find it there and advocate its inclusion in the main curriculum, something we can revisit after some time.
