### ISSUE TITLE
Number 002 on trello

### ISSUE THREAD

**Issue by ficast** [ossu/computer-science#801]
What should be the second card on trello?

![image](https://user-images.githubusercontent.com/61601716/94381302-4a712b80-010f-11eb-814e-0650db8682b9.png)

**Comment by waciumawanjohi** [comment]
A course no longer in the curriculum.

This also reminded me to move The Missing Semester down.

There is a good #TODO for anyone interested, updating [this script](https://github.com/ossu/computer-science/tree/JSON) so that it works with the current curriculum structure.
