### ISSUE TITLE
Invalid discord invite link

### ISSUE THREAD

**Issue by Selhar** [ossu/computer-science#815]
The [discord invite link](https://discord.com/invite/5pUhfpX) is invalid.

**Comment by rachel83az** [comment]
Instructions on how to create a permanent discord invite can be found here: https://support.discord.com/hc/en-us/articles/208866998-Invites-101

**Comment by Silential** [comment]
the discord link is not expired, I just used it. is it not working for you?

**Comment by Selhar** [comment]
It's working now. When i opened this issue i was getting an error saying the link is expired. I'll close this thread.
