### ISSUE TITLE
RFC: Formal Concept Analysis

### ISSUE THREAD

**Issue by spamegg1** [ossu/computer-science#818]
**Issue:**

This course in Advanced Theory covers (almost entirely) topics not mentioned in the [CS 2013 curriculum guidelines](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf).

**Duration:**

November 12, 2020 - December 12, 2020

**Background:**

I finished this course. I wrote a lengthy review [here](https://github.com/spamegg1/reviews/#concept).

**Proposal:**

Remove the course from the curriculum.

**Details:**

The course (while excellent) is a graduate level math course covering a specialized version of Lattice Theory. You can read more details in my review.

The only relevant topics covered in this course that are mentioned in the [CS 2013 curriculum guidelines](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf) are:
```
IM/Data Mining [Elective]: (page 118)
    Learning Outcomes 4.
        Describe how to extend a relational system to find patterns using association rules.
        Identify and characterize sources of noise, redundancy, and outliers in presented data.
```
However this topic is mentioned only briefly in the second half of the last week (out of 6 weeks), at the very end of the course. The rest 5 1/2 weeks of the course are not relevant to [CS 2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf).

**Comment by waciumawanjohi** [comment]
Reading the course syllabus and reading your review I agree that this is beyond the undergraduate curriculum. Concur with your proposal.
