### ISSUE TITLE
Translating the curriculum to another language 

### ISSUE THREAD

**Issue by M0hanad0** [ossu/computer-science#819]
Can I translate the OSSU/computer science curriculum to Arabic.

**Comment by rachel83az** [comment]
There is a Chinese version so I think Arabic would go well with that. It would be nice if there were more translations in other languages.

**Comment by waciumawanjohi** [comment]
The Chinese version is more ambitious than a translation. The authors have identified Chinese language online courses that match OSSU goals. (At least, that is the intention)

@M0hanad0 Yes, your efforts would be welcome. Before including such a translation, OSSU would need to check to make sure the contribution makes sense. At the moment I don't know any regular contributors that speak and read Arabic. But if you put in the time to make a translation, I'll be happy to put in the time to find some proofreaders.

Closing this issue, but feel free to reopen with any further questions.
