### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Uniminin** [ossu/computer-science#825]
Section: [#advanced-programming](https://github.com/ossu/computer-science#advanced-programming)
The link http://lpn.swi-prolog.org/lpnpage.php?pageid=top for the course `Learn Prolog Now!` is dead.
Current upstream: http://www.learnprolognow.org/lpnpage.php?pageid=online

**Comment by waciumawanjohi** [comment]
Both versions are working for me. But the http://www.learnprolognow.org is the first hit on Google, and [this other old host](http://cs.union.edu/~striegnk/learn-prolog-now/lpnpage.php?pageid=online) points to learnprolognow.org, so sounds like a fine switch.
