### ISSUE TITLE
Too many courses for Advanced Applications?

### ISSUE THREAD

**Issue by qiujiangkun** [ossu/computer-science#830]
I read this and found out **Advanced Applications** has too much workload compared with other advanced courses. Moreover, many courses in Advanced Applications are not related to each other. Like `Modern Robotics` has little to do with `Fullstack Open` or `Big Data`.
May a better wording help?
> Courses in Advanced CS are electives. Choose one subject (e.g. Advanced programming) you want to become an expert in and take **all the courses under that heading**. You can also create your own custom subject, but we recommend getting validation from the community on the subject you choose.

**Comment by spamegg1** [comment]
You pick ONLY ONE Advanced Application.
> The Advanced CS study should then end with one of the Specializations under Advanced applications. A Specialization's Capstone, if taken, may act as the Final project,

**Comment by waciumawanjohi** [comment]
@qiujiangkun If you have suggestions for wording that would make this clearer (that students are only to do one of the Advanced Applications), I'm interested in hearing them!

**Comment by qiujiangkun** [comment]
These seem to contradict with **all the courses under that heading**.

> After completing every required course in Core CS, students should choose a subset of courses from Advanced CS based on interest. Not every course from a subcategory needs to be taken. But students should take every course that is relevant to the field they intend to go into.

> The Advanced CS study should then end with one of the Specializations under Advanced applications. A Specialization's Capstone, if taken, may act as the Final project

I would like to rephrase it as the following
- Courses in Advanced CS are electives. Choose one advanced subject (e.g. Advanced programming) you want to become an expert in and take all relevant courses under that section and one of the Advanced applications.  You can also create your own custom subject, but we recommend getting validation from the community on the subject you choose.
- You need to have a final project to validate, consolidate, and display your knowledge, to be evaluated by their peers worldwide. This project can also be one of the Specializations in Advanced applications, an entirely new project, or an existing project that needs help. (This part was missing)
