### ISSUE TITLE
RFC: Adding a book to go along with cs50 course

### ISSUE THREAD

**Issue by mehtaRohit** [ossu/computer-science#842]
Students are told to skip the CS50 after the C class. Going through the reason given [here](https://github.com/ossu/computer-science/blob/master/FAQ.md#why-do-you-recommend-skipping-the-second-half-of-cs50) and based on my learning experience with the course and the C language, I would say **Practical C Programming by Steve Oualline** is very nice book to accompany cs50.
In my opinion, this book is good for people beginning to code for first time and learning C for the first time.
The book follows easy to read and practical (as name implies) approach to teach programming in real world using C, with practice problems accompanying each chapter.
The ebook is freely available on [PDF Drive](www.pdfdrive.com).

I would like to know what the OSSU community thinks!

P.S. If by any unintented chance I am violating any copyright claims, Please let me know!

**Comment by spamegg1** [comment]
That looks like a non-free book (O'Reilly Media published it), it's probably piracy to download it, so we should not suggest that.

There are a lot of Amazon links to non-free books in [extras/readings.md](https://github.com/ossu/computer-science/blob/master/extras/readings.md)

I don't see any C-specific books there, so maybe @mehtaRohit you can recommend adding an Amazon link to [extras/readings.md](https://github.com/ossu/computer-science/blob/master/extras/readings.md)

**Comment by mehtaRohit** [comment]
@spamegg1 alright. Forking and creating a PR.

And closing this issue.
