### ISSUE TITLE
My learning path

### ISSUE THREAD

**Issue by cwrocker** [ossu/computer-science#846]
Let's try this out

**Comment by bradleygrant** [comment]
I suspect you intended to Fork this project to your own GitHub account. That way, you can use the OSSU course path as a base to remix and create your own learning path.

Here's a doclink to help you get started:

https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

**Comment by cwrocker** [comment]
Thank you. My bad. I was using a mobile app
