### ISSUE TITLE
Advice on where to start

### ISSUE THREAD

**Issue by nuel99** [ossu/computer-science#848]
Good evening sir/ma. 
Just coming across OOSU/Comp sci. Thanks for the opportunity. Please is it advisable to skip the introduction to programming aspect and move to the intro to comp sci; I've got a knowledge of programming already or do I restart ?. Thanks

**Comment by alekhood317** [comment]
Whatttt

**Comment by waciumawanjohi** [comment]
Hi @nuel99 Welcome to OSSU!
If you already know how to program, you can skip Intro to Programming. This is particularly true if you know how to program in Python. The Intro to CS course expects you to be able to program in Python by week 2 of the course. If that sounds manageable, dive in! If you'd like a gentler introduction to Python, Py4E (the course in Intro to Programming) will be just right.

**Comment by nuel99** [comment]
Thanks sir. Will continue with intro to CS.
