### ISSUE TITLE
When is version 9 released ?

### ISSUE THREAD

**Issue by nhanvu327** [ossu/computer-science#851]
In here https://github.com/ossu/computer-science/blob/master/CHANGELOG.md. it says "The curriculum is currently undergoing review for v9". Just want to ask what is the status and maybe an estimate of when it is gonna be released ?

**Comment by waciumawanjohi** [comment]
The text continues, "As Requests for Comment in this effort are completed, **changes are made immediately to the curriculum.** When the overall review is complete we will notate the version bump to v9." The day that v9 is declared, the curriculum will look almost exactly the same as the day before.
