### ISSUE TITLE
Skipping "How to Code"

### ISSUE THREAD

**Issue by HowToDisappear** [ossu/computer-science#855]
I'm considering picking a course from the core programming section of OSSU, but having read comments and glanced through the course syllabus of "How to code" it seems to be aimed at complete beginners. And to be honest the fact that you need to learn and code in some kind of "student" language doesn't feel appealing (e.g. read some comments on class central). 
So do you think it'd safe to skip to "Programming languages" set of courses (prerequisites seem ok to me)? Or will I be missing out on some important concepts?
(I have some experience coding in Python, JS and C).

**Comment by waciumawanjohi** [comment]
This is a great question to ask in [the discord](https://discord.gg/wuytwK5s9h). As this does not represent an issue with the curriculum that needs a change, I am closing this issue.
