### ISSUE TITLE
[Course Tracking] Include a Notion page for tracking the progress of, and encouraging work for, OSSU.

### ISSUE THREAD

**Issue by fellowish** [ossu/computer-science#856]
I have created a Notion page which allows the use of various databases. Moreover, the databases interact with each other, and also pushes the student to show "Proof of Work" for any course they take or finish, which also interacts with the databases inside of the Notion page.

[OSSU Page Link](https://www.notion.so/OSSU-6eedb408468844ec9ace47bdc0f30bd7)

It simply seemed like the best free option to use. Trello is rather clumsy in implementation (as much as I like Trello, it doesn't have many features is comparison). If you have a Notion account, you can make a duplicate of the page and simply edit it to your heart's content.

I feel like this would be much better for user retention and productivity.

(Also, don't mind the possum drawing for the logo. OSSU just reminded me of them because it shared 4 letters with the animal's name. )

**Comment by waciumawanjohi** [comment]
Hi Fellowish,
I love the fact that you want to create tools for OSSU! That's awesome; it's students becoming contributors that make OSSU grow.

At the same time, as you've pointed out, the tool you've created duplicates functionality that we already have with our Trello board. Students are able to duplicate Trello boards, edit them and track their progress with them. I certainly understand that everyone has their favorite tool, but getting an open source project to drop one tool in favor of another requires more than an opinion that the current tool is clumsy in implementation.

In addition, every tool that we add is a tool that we take on the cost of maintenance. Updating the curriculum means updating each tool. It's a challenge that means any new tool should deliver significant value for students.

As I said, I'm glad to see you thinking about the curriculum and bringing your ideas. The next one may be the thing that revolutionizes OSSU!
