### ISSUE TITLE
RFC: Add Leetcode link under Core Theory as an additional assignment

### ISSUE THREAD

**Issue by VitaliyVoloshin** [ossu/computer-science#859]
Tim Roughgarden's course (and book series) provides students with great amount of practise problems, but still closely tied only to classical algorithms being discussed in them.

Suggestion: include leetcode.com problems as additional assignments.

A quote from teachyourselfcs.com:

> For practice, our preferred approach is for students to solve problems on Leetcode. These tend to be interesting problems with decent accompanying solutions and discussions. They also help you test progress against questions that are commonly used in technical interviews at the more competitive software companies. We suggest solving around 100 random leetcode problems as part of your studies.

**Comment by VitaliyVoloshin** [comment]
I found out that this platform was mentioned earlier on https://github.com/ossu/computer-science/issues/783

One of the participants claimed that:

> Also, leetcode et al. cater very specifically to the job interview market. You'd typically begin doing this 6 months prior to a standard coding interview. No one is questioning their merit, they are extremely high quality of course, but may be not the focus of a CS class.

In my opinion, it is, indeed, more related to a tech interviews rather than computer science. But, nevertheless, it still seems to be an important part of mastering algorithms and a major differentiator that separates average coders from solid programmers (like, for example, implementing some parts of a small kernel during OS course)

**Comment by waciumawanjohi** [comment]
Quoting from the contribution guide:

If you have specific and substantive criticisms of the curriculum, i.e. problems related to the progression/content of courses it would be appropriate to [open an issue](https://help.github.com/articles/creating-an-issue/). While it is acceptable to point out problems, all successful changes naturally require a plan for fixing the problem.
OSSU’s curricular guidelines are [here](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md). Successful critiques of the curriculum will point out ways that OSSU is failing to uphold these guidelines. Examples are:

* OSSU lists a course as required when the course topics are elective in the curricular guide.
* OSSU does not having a course to cover required topics from the curricular guide.
* OSSU lists multiple courses that cover the same topics when fewer courses could suffice.
* OSSU recommends a course to teach a topic, but there exists a higher quality course that covers the same material.

You state that the recommended algorithms course has
> great amount of practise problems, but still closely tied only to classical algorithms being discussed in them.

A course that says it is going to teach and asses topics XYZ, and then goes on to teach and assess exactly XYZ is fulfilling its responsibility. This is not a shortcoming.

There are myriad things that a learner can learn. In creating the curriculum, we are creating a guide to the best resources to learn a small sliver of the universe. Adding an "additional assignment" of 1700 problems is not a good fit for that goal. (Even though I suspect many OSSU students will try leetcode at some point!)
