### ISSUE TITLE
Advanced Programming -> Learn Prolog Now! link broken

### ISSUE THREAD

**Issue by Saif-XI-Coderz** [ossu/computer-science#868]
Dear Maintainers,
As indicated in title, this link is broken. Can you guys please verify?
Thanks in advance.

URL: http://www.learnprolognow.org/lpnpage.php?pageid=online

![image](https://user-images.githubusercontent.com/7271727/109462731-60e43000-7a7d-11eb-9e5c-ab7791561155.png)

**Comment by spamegg1** [comment]
That website goes offline occasionally for a day or two, it happened before.
It's back now. It always comes back.
There isn't much we can do about it, it's on their server side. It might be due to regular maintenance or something like that.

@Saif-XI-Coderz Can you close the issue?

**Comment by Saif-XI-Coderz** [comment]
Thanks for responding. I checked the site again, i noticed though it's now online, it's content pages are all blank and shows nothing.

![image](https://user-images.githubusercontent.com/7271727/109949090-68f9d500-7cf4-11eb-811c-8f0061cd62dc.png)

I discovered that the website has it's repo on GitHub: https://github.com/LearnPrologNow/lpn
But it needs some compiling (makefile) to make all the pages display properly (something I dn't yet know how to do).

I would say we either:
1. Remove it.
2. Replace it (I have no idea with what).
3. Compile the source, convert to pdf/html and make that accessible to learners (lots of work, I know)
4. At the very least give learners a heads up about the site (un)reliabilty.

What do you think?

PS: I reached out to the authors, dnt know if they'll respond.

**Comment by spamegg1** [comment]
I was able to compile the repo you pointed to. Got a PDF, here it is
[lpn.pdf](https://github.com/ossu/computer-science/files/6085884/lpn.pdf)
It compiled with quite a lot of errors but it seems fairly legible and OK.
We can replace the link with this file, maybe?

**Comment by Saif-XI-Coderz** [comment]
Yes I can take over.

Should this issue be closed before or after PR?

**Comment by spamegg1** [comment]
You can close it now if you want.

**Comment by spamegg1** [comment]
Looks like the pages are fully back.
To me it seems like this will be a regular occurrence.
So I'll make a PR to add a link to the PDF version I compiled.

**Comment by Saif-XI-Coderz** [comment]
I was gonna create the PR, but it could have taken a while.
Thanks for taking care of this on top of your busy schedule.
