### ISSUE TITLE
RFC: Update Link for Effective Thinking Through Mathematics course in extras

### ISSUE THREAD

**Issue by licjon** [ossu/computer-science#870]
**Problem:**
This link doesn't work: https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0

**Alternatives:**
This link seems to work: https://learning.edx.org/course/course-v1:UTAustinX+UT.9.10x+3T2016/home

**Comment by waciumawanjohi** [comment]
👍
Make a pull request to fix this and we'll merge it in!

**Comment by waciumawanjohi** [comment]
Resolved by https://github.com/ossu/computer-science/pull/871
