### ISSUE TITLE
Intro to Networking

### ISSUE THREAD

**Issue by rachel83az** [ossu/computer-science#887]
It has been noted that the current "course" for learning networking is insufficient for the task for whatever reason. Some possible alternatives include:

- https://learn.saylor.org/course/view.php?id=84 - Appears to be a very basic overview of networking and networking technology. Includes a number of quizzes/assessments to check understanding. I don't know if there is any practical/hands-on experience within the course.
- https://www.youtube.com/watch?v=qiQR5rTSshw One single massive video instead of the current playlist where videos could go missing randomly. FreeCodeCamp.org created this to assist in studying for the CompTIA exam. There are timestamps in the description to allow jumping to a specific topic. 
- https://www.professormesser.com/network-plus/n10-007/n10-007-training-course/ More study for the CompTIA Network+ exam.  Only videos. But Professor Messer videos are great. Arguably easier to watch than the current playlist. 
- http://gaia.cs.umass.edu/kurose_ross/online_lectures.htm This course is 2 chapters away from completion. Sections have both knowledge checks and problems to solve. Students may be expected to purchase/rent the book but someone else would have to review if it's actually _necessary_ to do so. This one appears to be THE BEST whole solution, assuming the book isn't strictly required.
- http://ini740.rocks/F20/ This one says that it's a graduate-level course but it appears to be more like a high-level undergrad course. There are labs and homework assignments to complete. This one uses the 7th edition of the Kurose book. The book appears to be more necessary here than the above course on the authors' website.

**Comment by MOSTAFAEZZAT** [comment]
I agree it's more suitable for Network specialization than introduction

**Comment by rachel83az** [comment]
That's a good point. Perhaps adding an actual networking specialization would be a good option

**Comment by tykavanaugh** [comment]
Messer's stuff is awesome, though I'm not sure if it might be too in depth as a whole.

**Comment by rachel83az** [comment]
I think "too in-depth" might be true of most networking things out there. I'm not sure how much networking OSSU students are supposed to learn, TBH.

**Comment by waciumawanjohi** [comment]
> how much networking OSSU students are supposed to learn

The 4 pages of the CS2013 starting here: https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=133
address that question.

**Comment by Slakesslumban** [comment]
Its would be a good idea to have a  specialization in ""Networking""

**Comment by waciumawanjohi** [comment]
This issue has been open for a few months. It is time to resolve it.

Findings:
- There have been a handful of upvotes for this issue.
- The Kurose-Ross course is currently pinned in the discord channel for intro to networking.
- Resources from the Kurose-Ross course site are used for some of the assignments in the current course.

Response:
Kurose-Ross team is creating an increasing ecosystem for learning networking. This contrasts with the open Stanford course, which is not even offered any longer by the university. OSSUnians have demonstrated their appreciation of these resources, including the submitter above writing "This one appears to be THE BEST whole solution..."

Conclusion:
OSSU will adopt the Kurose-Ross course for networking.
