### ISSUE TITLE
Invalid discord link

### ISSUE THREAD

**Issue by baditaflorin** [ossu/computer-science#892]
"We have a discord server! Discord This should be your first stop to talk with other OSSU students. Why don't you introduce yourself right now? Join the OSSU Discord"

the link does not work.

**Comment by waciumawanjohi** [comment]
What happens when you follow the link?

**Comment by Michael1370** [comment]
The link is working fine for me currently.

**Comment by SkylarKitchen** [comment]
The link works fine for me.

**Comment by waciumawanjohi** [comment]
Having not heard back from the original author of this issue, and having received feedback from multiple folks that the link is working properly, I'm going to close this issue.
