### ISSUE TITLE
Adding an optional C-like language course

### ISSUE THREAD

**Issue by Michael1370** [ossu/computer-science#893]
A number of courses list knowing a C-like programming language or often specifically C++ as a prerequisite. This doesn't appear to be covered by the earlier courses.

While courses are chosen based on concepts rather than languages and it is possible for students to learn this themselves, it would be beneficial to have an optional course or other resource listed which covers the basics. Ideally this would be something completely self-paced similarly to Python for Everybody.

**Comment by waciumawanjohi** [comment]
Learning specific programming languages is not part of our [curricular guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md), and so we wouldn't have a particular course on C++. At the same time, it _is_ important to be able to find high quality resources on how to get up to speed with a language. For that reason, our FAQ has an entry pointing students to good resources: https://github.com/ossu/computer-science/blob/master/FAQ.md#what-is-a-good-course-to-learn-a-particular-language
