### ISSUE TITLE
Introduction to Machine Learning from MIT

### ISSUE THREAD

**Issue by JoeMartis** [ossu/computer-science#894]
Apologies if this is not the proper venue for this suggestion - I would like to recommend adding Introduction to Machine Learning from MIT Open Learning Library. This is a direct port of a residential MIT course that does not exist publicly anywhere else. The course is free, self paced and chock full of interactive assessments. https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/about

**Comment by waciumawanjohi** [comment]
That sounds very interesting. OSSU currently has a machine learning course. It will be helpful for all reviewers if you're able to compare these two courses and point out why the new offering should either replace or be recommended in addition to the old course. I recommend reading through the [contributing guidelines](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md) and using the `Request for Comment Template` when you are ready to propose a change.

Leaving this open for a week for visibility. Contributors are welcome to discuss here or on [Discord](https://discord.gg/NcXHDjy). (More OSSUnians talk regularly on the Discord)

**Comment by waciumawanjohi** [comment]
Closing this issue as the visibility period has passed and there has been no further comment.
