### ISSUE TITLE
Do we need the Contributor Over Time chart? 

### ISSUE THREAD

**Issue by starsz** [ossu/computer-science#895]
Hi, we have generated a chart of contributors over time, which may be helpful to you.

You can take a look about: 
https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=ossu/computer-science

**Comment by oss-su** [comment]
It's interesting.

**Comment by waciumawanjohi** [comment]
Interesting indeed! Thank you for sharing.

As this issue has not attracted any further comment in more than a month, I am closing it.
