### ISSUE TITLE
RFC: i recommend making an app for the uni and it's user friendly one and instead of going into diff courses i recommend that you get a lecturer who explain in les than 15min per vid and there is like a shorts 3min having the main points and a little quiz or questions on the subject of every vid . The porpuse of that is to make it as easy as posible for the learner to learn and there's an arabic app for learning languages applies all what is said and it's awsome and it makes the learner instead of working 100% he works only 5% which is hearing a lesson or 2 a day and doing the questions and revising the shorts of the old lessons that the app will tell them to see. I hope you tale what i said into consideration

### ISSUE THREAD

**Issue by mohamedhany2004** [ossu/computer-science#896]
**Problem:**
Give a 1 sentence description of a problem with the current OSSU Curriculum. Successful critiques of the curriculum will point out ways that OSSU is failing to uphold [our curricular guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md). Examples are:

* OSSU lists course X as required when the course's topics are elective in our curricular guidelines.
* OSSU does not having a course to cover required topic X from our curricular guidelines.
* OSSU lists courses X, Y and Z that cover the same topics when fewer courses could suffice.
* OSSU recommends course X to teach a topic, but there exists a higher quality course that covers the same material.

**Duration:**
This should most often be 1 month from the date of posting.

**Background:**
Give an in depth description of the problem. Describe a solution to the problem. Describe the advantages and disadvantages of this solution. This section should be a few paragraphs.

**Proposal:**
Give a bullet point list of changes that are being proposed. These can link to a Pull Request.

**Alternatives:**
Give a bullet point list of alternative ways to address the problem.

**Comment by waciumawanjohi** [comment]
Thanks for the feedback!
