### ISSUE TITLE
Remove dead links on `courses.md` and `readings.md`

### ISSUE THREAD

**Issue by micalevisk** [ossu/computer-science#907]
After running

```bash
lychee https://raw.githubusercontent.com/ossu/computer-science/835c2c101d7c27ac8beb93dfb8af9aab22a85565/extras/courses.md
```

```bash
lychee https://raw.githubusercontent.com/ossu/computer-science/835c2c101d7c27ac8beb93dfb8af9aab22a85565/extras/readings.md
```

I've found the following dead links

- https://github.com/ossu/computer-science/blob/835c2c101d7c27ac8beb93dfb8af9aab22a85565/extras/courses.md#L81
- https://github.com/ossu/computer-science/blob/835c2c101d7c27ac8beb93dfb8af9aab22a85565/extras/readings.md#L36

**Comment by waciumawanjohi** [comment]
The entire faculty subdomain for UMass Lowell is down. I wonder if that's an error. There are still live links from Levasseur's entry in the UMass directory to that faculty site:
https://www.uml.edu/profile/kenneth_levasseur

**Comment by waciumawanjohi** [comment]
Big Data course has been removed from EDx. Making a commit to remove it.

Thanks for the heads up!
