### ISSUE TITLE
Add Brand-new (Sep 2020) Gilbert Strang textbook Linear Algebra for Everyone in lieu of (or in addition to) the classic Introduction to Linear Algebra

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#910]
**Problem:**

* OSSU recommends Gilbert Strang's _Introduction to Linear Algebra_ in readings, but there exists a higher quality course/textbook that covers the same material from the same author (that is a bit more accessible).

**Duration:**
1 month (until July 31, 2021)

**Background:**
Prof Gilbert Strang's _Introduction to Linear Algebra_ is a timeless classic and is probably the de-facto textbook/reference material for linear algebra. However, at times, I found the language a bit difficult, at least during the first read. With the second pass read of the tougher portions, I am usually able to resolve the ideas a bit more. Usually, It takes me 2-3 readings to understand the language and concepts covered. 

**Proposal:**
I propose to supplement or supplant this with Prof Strang's brand new (Sep 2020) project [Linear Algebra for Everyone](http://math.mit.edu/~gs/everyone/).  In the spirit of __Py4E__, this is a complete course/project/texbook from Prof Strang that makes the language of Linear Algebra a bit more accessible (IMHO).

I haven't raised a PR yet for this, but would like to collect the general feedback/thoughts from OSSU-ians regarding this change/update to a much loved classic textbook.

**Comment by waciumawanjohi** [comment]
I've watched Strang's 2020 Vision of Linear Algebra videos. He remains an insightful educator of linear algebra! I would not object to replacing _Introduction to Linear Algebra_ with _Linear Algebra for Everyone_.

Worth noting that 18.06 at MIT this semester uses _Introduction to Linear Algebra_ as a reference, but is explicit that they do not follow the book. [link](https://github.com/mitmath/1806/blob/master/summaries.md)

**Comment by robme-l** [comment]
I looked up Linear Algebra for Everyone, and could not find a free version of the book, if we want to stick purely to Open Source, should the video course 18.06 be sufficient?

**Comment by waciumawanjohi** [comment]
The OCW course includes not only lectures, there are also lecture notes that add up to quite a bit of text instruction. There are also a number of free linear algebra textbooks that you can find through a google search. And if you still want to read LA4Everyone you can check with your library system to see if you can borrow a copy through interlibrary loan.

Note that the OCW course is from 2011 and LA4Everyone is Strang's flag in the sand to teach linear algebra with different emphasis. My impression is that LA is taught in a distinctly different manner today than it was a decade ago (which frustrates me).
