### ISSUE TITLE
Thoughts on the awesome-courses (https://github.com/prakhar1989/awesome-courses) repository?

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#911]
Following the `curriculum` tag here at the OSSU GitHub repository, I discovered the [`awesome-courses`](https://github.com/prakhar1989/awesome-courses) repository, whose description is:

>List of awesome university courses for learning Computer Science! 

Obviously, I see a direct overlap in _intent_.

- The courses listed there do not appear in OSSU's list of courses (barring one or two in the whole list). Does it mean that the other list is complimentary, i.e. providing valuable additional material to students?
- Is it worthwhile to include that repository in OSSU's [other curricula](https://github.com/ossu/computer-science/blob/master/extras/other_curricula.md) page?
- Most importantly, if any OSSU-ians have taken or attempted to take some courses listed in the  [`awesome-courses`](https://github.com/prakhar1989/awesome-courses) repository, can they please provide a brief critique/review so that it will appear as a version of record here, and we can potentially discuss their inclusion.

**Comment by Alaharon123** [comment]
It's a very useful repo for finding alternative courses to the ones in OSSU. It's basically an entire repo of extra/courses, just with a couple more restrictions iirc. It doesn't belong in other curricula because it's not a curriculum, it's a bunch of courses purposely including a lot of overlap: it's curated for including as much as possible within its guidelines, not for a set of courses one person should take. I agree with you though that it should probably be linked *somewhere* in OSSU. Dunno where though.

**Comment by krishnakumarg1984** [comment]
Thank you for your thoughts. I have a related, but separate thought.

There should be a page in the Wiki which collates courses that were evaluated for inclusion, but didn't make it, along a short statement stating their reason for exclusion. That Wiki page should be linked to from the main README.md. This really helps for posterity wherein next generation of students can refer, and potentially avoid bringing up an RFC for courses that have already been dealt with 4 years before (and it would help not to have to dig through years of individual GitHub issues).

**Comment by waciumawanjohi** [comment]
> There should be a page in the Wiki which collates courses that were evaluated for inclusion, but didn't make it

I'm concerned that this could become unwieldy. I also imagine that this information should be discoverable by searching the Github issues.

**Comment by waciumawanjohi** [comment]
PR #996 adds an FAQ entry that points students to awesome-courses. Leaving the PR open for two weeks to invite improvements, will merge afterwards.

**Comment by waciumawanjohi** [comment]
I will note that Awesome Courses has not been updated in over a year. This despite the fact that there are open pull requests that are actionable. It may be necessary to remove the link to this repo in the future.
