### ISSUE TITLE
RFC: Change link for Linear Algebra & other courses if possible.

### ISSUE THREAD

**Issue by rachel83az** [ossu/computer-science#920]
OSSU currently links to https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/ for Linear Algebra. OCW is great but it's not the friendliest experience for students. Instead, I suggest using the Open Learning Library link of https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.06SC+2T2019/about instead. It's literally the same content but laid out in a more student-friendly (less distracting/confusing) format. 

OLL uses the edX backend so the navigation will be more familiar. Except the courses _do not expire_ as they do on edX. 

Instead of Calculus on edX, there are: 

- Calc 1a: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/about
- Calc 1b: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.2x+3T2019/about
- Calc 1c: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.3x+1T2020/about

Math for Computer Science already has the OLL link as the main source so I feel like there is precedent for this.

**Comment by waciumawanjohi** [comment]
Linking these two related issues:
[Proposal to switch Math for CS to Open Learning Library](https://github.com/ossu/computer-science/issues/832). Accepted and merged.
[Proposal to switch Calculus to OCW](https://github.com/ossu/computer-science/issues/838). Open.

I will say that the discussion on Calculus (Issue 838) revolved around the differences in material on edX vs OCW. You make a very important point; that edX eventually removes access from students auditing the course. Based on that, I support making the change from edX to OLL or OCW. If you support Issue 838, I think we can make the change to OCW this week (it has been open for quite awhile). This issue could then remain open to gather feedback from OSSUnians on their preference between OLL and OCW.

I'm agnostic on the question of switching Linear Algebra to OLL. Issue 832 suggested sticking with OCW, but there wasn't an in depth conversation or comparison.

**Comment by waciumawanjohi** [comment]
Note that this commit has changed Calculus to the OLL version:
https://github.com/ossu/computer-science/commit/80ac876827213627dd3accac53697ab08d2fdd4f

This issue remains open for student comments on the linear algebra recommendation!

**Comment by Alaharon123** [comment]
The thing with the OLL Linear Agebra course is that it splits each section up into so many different pages. [This one page](https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/ax-b-and-the-four-subspaces/the-geometry-of-linear-equations/) is 6 different pages in the OLL version. And that is the case for every page in the two versions of the course. The OLL version *is* slightly more user-friendly so you don't have to start by getting used to the layout, but I think it's less functional after you've spent the couple minutes to understand how the OCW version of the course is layed out. If Linear Algebra was early in the curriculum, I would agree with you that it's a tradeoff worth making for the OLL version, but with where it is, I think it's a bad tradeoff personally.

**Comment by krishnakumarg1984** [comment]
The EdX TOS and acquisition etc is bringing in some real dichotomy i.e. the courses themselves are of high quality, but they aren't great for wallet-friendly continued access etc.

For the time-being, a workaround can be to cherry-pick alternatives wherever they are of comparable quality which don't dilute the learning experience. In cases like the linear algebra version on OCW, perhaps we stick with EdX and provide a healthy dose of warning in the main page which unambiguously states that EdX might revoke access after a run for non-paid students.

**Comment by waciumawanjohi** [comment]
> In cases like the linear algebra version on OCW, perhaps we stick with EdX

I just want to clarify that [OCW](https://ocw.mit.edu/index.htm) and [edX](https://www.edx.org/) are two different platforms, and [OLL](https://openlearning.mit.edu/courses-programs/open-learning-library) is a third.

**Comment by riceeatingmachine** [comment]
Hello, I took the EdX courses and the big advantage of EdX is that there are TAs who are very active and very helpful as they answer learner questions fast and promptly. I would therefore support EdX being the primary link with a note to the alt.

**Comment by waciumawanjohi** [comment]
In the month following this RFC no consensus emerged. Contributors spoke in favor of using edX (1), OLL (1), and OCW (1), and spoke against using edX (1), OLL (1) and OCW (1). Since that month there hasn't been any further engagement. Based on that, I'm going to close the RFC.
