### ISSUE TITLE
RFC: Update Core Maths description

### ISSUE THREAD

**Issue by sanonasu** [ossu/computer-science#921]
**Problem:**
Since making calculus required in core maths the sentence introducing it now seems confusing, because it mentions electives.

**Duration:**
1 month

**Background:**
The description now reads "In addition to their math elective, students must complete the following course on discrete mathematics" even though math electives are now efectively gone

**Proposal:**
- Remove the first clause of the sentence and leave the line saying "Students must complete the following course on discrete mathematics."

**Alternatives:**
- Write a new sentence entirely to reflect that the section now encompasses more than one course.
- Add optional electives and don't change the sentence(?)

**Comment by waciumawanjohi** [comment]
Good catch! Thanks.
