### ISSUE TITLE
Request For Comment: Add Ethics Course

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/computer-science#937]
**Problem:**
OSSU CS does not give students the proper education in Ethics

**Duration:**
September 17,2021.

**Background:**
OSSU promises the equivalent of an undergraduate degree in Computer Science. In order to evaluate our recommended courses, we use the Curriculum Guidelines for Undergraduate Programs in Computer Science (CS2013). CS2013 specifies a number of knowledge areas a curriculum must cover, one of which is social issue and professional practice. 

CS 2013 Says
While technical issues are central to the computing curriculum, they do not constitute a complete educational program in the field. Students must also be exposed to the larger societal context of computing to develop an understanding of the relevant social, ethical, legal and professional issues. This need to incorporate the study of these non-technical issues into the ACM curriculum was formally recognized in 1991.

Topics covered under this are

- Analytical Tools
- Professional Ethics
- Intellectual Property
- Privacy and Civil Liberties
- Professional Communication

Learning Outcomes 

- Students will be able to recognize the social, legal, ethical, and cultural issues inherent in the discipline
of computing.
- Students will be able to recognize social, legal, and ethical standards vary
internationally.
- Students will develop the ability to ask serious questions about the social impact of computing.
- Students will be knowledgeable about the interplay of ethical issues, technical
problems, and aesthetic values that play an important part in the development of computing
systems.
- Students will be able to understand their individual, collective responsibility and distribution of responsibility in engineering.
- Students will be able to understand the ethical aspects of technological risks.
- Students will understand about intellectual property rights
- Students will understand about Data Privacy 

**Proposal:**

Add these courses to core CS curriculum as **Core Ethics** 
- [Ethics, Technology and Engineering](https://www.coursera.org/learn/ethics-technology-engineering)

This course will take duration of 9 weeks with effort of 2hours/week to complete.

- [Intellectual Property Law in Digital Age ](https://www.coursera.org/learn/intellectual-property-law-in-digital-age)

This course will take duration of 4 week with effort of 2hours/ week to complete.

- [Data Privacy Fundamentals](https://www.coursera.org/learn/northeastern-data-privacy)

This course will take duration of 3 weeks with effort of 3hours/week to complete.

Add this course as **Professional Practice** as an elective material

- [Oral Communication for Engineers](https://www.coursera.org/learn/oral-communication)

This course will take duration of 6 weeks with 4hours/week to complete.

- [Interpersonal Communication of Engineers](https://www.coursera.org/learn/interpersonal-communication)

This course will take duration of 6 weeks with 4hours/week to complete.

- [Writing Skills for Engineers](https://www.coursera.org/learn/engineering-writing)

This course will take duration of 4 week with effort of 4hours/week.

**Alternatives:**
Add this course to curriculum
- [Responsible Innovation : Ethics, Safety and Technology](https://www.edx.org/course/responsible-innovation-ethics-safety-and-technolog?index=product&queryID=79b7303b6bc719e56843861c24d195f8&position=3)
Paired with this textbook
[Responsible Innovation: Ethics, Safety and Technology Textbook](https://textbooks.open.tudelft.nl/index.php/textbooks/catalog/book/24)
~~~~

**Comment by waciumawanjohi** [comment]
1. Great call out. I love this RFC.
2. I assumed that "Topics covered under this are" was a reference to the topics covered by the CS2013. This list is instead a list of the topics covered by the proposed ethics course.
3. The list of topics required in CS2013 is:

Topic | Core-Tier1 hours | Core-Tier2 hours | Includes Electives
:-- | :--: | :--: | :--:
Social Context | 1 | 2 | N
Analytical Tools | 0 | 2 | N
Professional Ethics | 2 | 2 | N
Intellectual Property | 0 | 2 | Y
Privacy and Civil Liberties | 0 | 2 | Y
Professional Communication | 0 | 1 | Y
Sustainability | 1 | 1 | Y

4. The CS2013 states "Computer science educators may opt to deliver this core and elective material in stand-alone courses, integrated into traditional technical and theoretical courses, or as special units in capstone and professional practice courses. The material in this familiarity area is best covered through a combination of one required course along with short modules in other courses." This means that while it is good for us to consider an ethics course, we should also have an ongoing commitment to note when courses include high value integrations of ethical and social considerations.
5. The recommended course uses the _Engineering Criteria 2000 of the Accreditation Board for Engineering and Technology_ as its curricular framework. ABET is a widely respected and adopted accreditation organization for engineering fields; in years past OSSU referred to their guidelines side-by-side with the CS2013 (written by the ACM and IEEE).

I support this RFC and am interested in hearing others' thoughts on it.

**Comment by aayushsinha0706** [comment]
After comment by @waciumawanjohi  I made some edits in the RFC. 

After examining the CS 2013 documents properly and it's topics and sub topics. Following Edits have been made

Edit 1- Changed the Topics covered according to CS 2013 document.

Edit 2- Added two more learning outcomes.

Edit 3- Ethics education is incomplete without education of intellectual property and privacy & civil liberties. 

Edit 4- Added **Professional Communication** courses and proposed it to be an elective material 

Edit 5 - Specified duration and effort of each course completion.

**Comment by waciumawanjohi** [comment]
> Edit 3- Ethics education is incomplete without education of intellectual property and privacy & civil liberties. So added two new courses and proposed it to be under Core curriculum as Core Ethics

Am I correct that this means the proposal is now for 3 courses total? How many hours are being proposed? We should keep an eye on whether courses are aligning with the number of hours expected in CS2013 and protect students from an overlong curriculum.

> Edit 4- Added Professional Communication courses and proposed it to be an elective material.

What are your thoughts on how you would represent this optional course in the curriculum? In the core curriculum, OSSU is fairly determined, valuing clarity. Elective material is generally in advanced courses.

**Comment by aayushsinha0706** [comment]
> Am I correct that this means the proposal is now for 3 courses total? How many hours are being proposed? We should keep an eye on whether courses are aligning with the number of hours expected in CS2013 and protect students from an overlong curriculum.

 [Ethics, Technology and Engineering](https://www.coursera.org/learn/ethics-technology-engineering)

This course will take duration of 9 weeks with effort of 2hours/week to complete.

Topics covered by it are 
- Analytical Tools [ 2 core tier 1 hours]
- Professors Practice [ 2 core tier 1 and 2 core tier 2 hours]

The effort is less compared to what CS2013 document says 


[Intellectual Property Law in Digital Age ](https://www.coursera.org/learn/intellectual-property-law-in-digital-age)

This course will take duration of 4 week with effort of 2hours/ week to complete.

Topics covered by it are
-Intellectual Property [ 2 core tier 1 hours]

The effort matches with what CS2013 document says.

[Data Privacy Fundamentals](https://www.coursera.org/learn/northeastern-data-privacy)

This course will take duration of 3 weeks with effort of 3hours/week to complete.

Topics covered by it are 
- Privacy and Civil Liberties [ 2 core tier 1 hours]

The effort is a bit more than what CS2013 document says but it can be reduced by increasing duration to complete the course.

The two new courses that were added after the edit are very less demanding and it can be completed with ease.

**Comment by aayushsinha0706** [comment]
> What are your thoughts on how you would represent this optional course in the curriculum? In the core curriculum, OSSU is fairly determined, valuing clarity. Elective material is generally in advanced courses.

It can be offered as an **Advanced Technical Communication**

According to CS2013 doc it can be offered as an elective material. 

Communication skills are not only important for engineering career but it can open to new careers like this 

[Technical Writer, Software Engineering Role at Google](https://careers.google.com/jobs/results/132434177778688710-technical-writer-software-engineering/?category=DATA_CENTER_OPERATIONS&category=DEVELOPER_RELATIONS&category=HARDWARE_ENGINEERING&category=INFORMATION_TECHNOLOGY&category=MANUFACTURING_SUPPLY_CHAIN&category=NETWORK_ENGINEERING&category=PRODUCT_MANAGEMENT&category=PROGRAM_MANAGEMENT&category=SOFTWARE_ENGINEERING&category=TECHNICAL_INFRASTRUCTURE_ENGINEERING&category=TECHNICAL_SOLUTIONS&category=TECHNICAL_WRITING&company=Google&company=YouTube&q=%22Technical%20Writer,%20Software%20Engineering%22)  

There are many role like this in other corporations as well.

There are open source programs like this which put it's emphasis on Technical Writing

[Google Season of Docs](https://developers.google.com/season-of-docs)

So students will not only go into traditional software engineering roles but can also switch to Technical Writing roles as well like a lot of people in Google did like here

[Technical Writing at Google](https://developers.google.com/tech-writing/becoming/meet)

**Comment by hiro776** [comment]
I believe licensing/copyright/IP rights are the things that every developer should have a good understanding of.

**Comment by waciumawanjohi** [comment]
> It can be offered as an Advanced Technical Communication
According to CS2013 doc it can be offered as an elective material.

The courses recommended as Advanced Technical Communication go well beyond the recommendations from CS2013, which specifies 1 core lecture hour of _Professional Communication_ content and then possible electives. I am also wary of adding an advanced section that isn't a Computer Science discipline. These courses may be a better fit under Extras/Courses.

**Comment by waciumawanjohi** [comment]
As to the main recommendation, the addition of
- Ethics, Technology and Engineering
- Intellectual Property Law in Digital Age
- Data Privacy Fundamentals
as *Core Ethics*, the proposal has had a good amount of attention and all feedback on the idea has been positive. I think this is ready for a PR!

**Comment by waciumawanjohi** [comment]
Closed by #971
