### ISSUE TITLE
please heeeelp! where can I find exercises and practices web site in problem solving???(but i need best of them and free) 

### ISSUE THREAD

**Issue by abdo111-ui** [ossu/computer-science#939]

**Comment by aymenBenadra** [comment]
try Hackerrank, Hackerearth, exorcism... these are great ones

**Comment by waciumawanjohi** [comment]
This is a great question to ask on [our Discord](https://discord.gg/wuytwK5s9h)! 

As described in OSSU:CS readme, our github issues are meant for "[i]f there is a problem with a course, or a change needs to be made to the curriculum..."

**Comment by hassanah391** [comment]
Code forces and chefcode.
