### ISSUE TITLE
New Curriculum updates are not reflected in the Spreadsheet

### ISSUE THREAD

**Issue by r0hitm** [ossu/computer-science#947]
The new curriculum update, added three new courses to the Core Programming.
However, the [spreadsheet](https://docs.google.com/spreadsheets/d/1bkUU90y4rKYQHwY5AR2iX6iiPTrPEsYs75GkCAkrgm4/edit?usp=drivesdk) is not updated to accommodate the new content.

**Comment by anitamaria722** [comment]
There are a lot of links to courses that doesn´t work.

**Comment by yousef11s** [comment]
unsubscribe

**Comment by MattRieke** [comment]
I have updated the spreadsheet to reflect the new curriculum content.

**Comment by waciumawanjohi** [comment]
Thank you @MattRieke
