### ISSUE TITLE
Add visual introduction to Linear Algebra in the extra readings (based on Strang's "Linear Algebra for Everyone")

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#951]
My earlier proposal to add Prof Strang's latest Linear Algebra course (Linear Algebra for Everyone) to extra readings/textbooks  has been positively recieved. See #910 

I am currently enjoying an amazing companion to Prof Strang's LA4E course called "Visual introduction to linear algebra". It provides a nice, clear & intiutive understanding of concepts (like Sanderson's 3B1B, but a bit more formal/technical) through diagrams & other visualisations.  The drawings & illustrations are of exceptional quality vector graphics.

Hence, in the same vein, I'd like to ask the moderators to consider adding this resource. [The art of linear algebra](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra).  The project owner is very active in updating the material through frequent commits.

**Comment by waciumawanjohi** [comment]
Having given this resource a quick perusal, I like it!
Diagrams are great. A picture is worth a thousand words. And it is certainly worth a PR.

**Comment by saerosV** [comment]
Hi @waciumawanjohi, how are you doing? I think this issue could be closed already.

**Comment by waciumawanjohi** [comment]
Closed by #956
