### ISSUE TITLE
RFC:  Addition to the Curriculum - Introduction to Numerical Analysis

### ISSUE THREAD

**Issue by DionGR** [ossu/computer-science#966]
**Recommendation:**
Add an Introduction to Numerical Analysis course to the curriculum. 

Numerical Analysis is quite an important and often overlooked subject when it comes to CS. It touches topics from floating point precision all the way to the most optimal way to do certain calculations in order to achieve minimal accuracy loss of data and the algorithms that come with it. I truly believe it gives a student:

* A better understanding of machine numbers and how they are represented.
* A way to apply all the calculus theory a student has learned, giving it a more practical use other than it being a "good-to-know".
* Insight on how  algorithms are used in order to achieve maximum precision efficiently.

I truly believe this course could be a part of Advanced Math, as it requires some Linear Algebra knowledge and probably stuff from the Mathematics for Computer Science course.

### **Numerical Analysis**
_**Elective Course**_

_Prerequisites:_ Math for Computer Science & (optional) Linear Algebra (helpful, not mandatory)

|       CS2013 Requirements         |[HSE University](https://www.coursera.org/learn/intro-to-numerical-analysis#syllabus)                         |[MIT  18.330](https://ocw.mit.edu/courses/mathematics/18-330-introduction-to-numerical-analysis-spring-2012/) | [MIT 18.335J](https://ocw.mit.edu/courses/mathematics/18-335j-introduction-to-numerical-methods-spring-2019/index.htm) |
|----------------|---------|-----------------------------|--------|
|**Error, stability, convergence, including truncation and round-off**|✔|✔| ✔ |
|**Function approximation including Taylor’s series, interpolation, extrapolation, and regression**            |  ✔* |✔| ✔* |
|**Numerical differentiation and integration (Simpson’s Rule, explicit and implicit methods)**        |✔|✔|✔ |
|**Differential equations (Euler’s Method, finite differences)**         |✔|✔| ✔**|

*: Uncertain whether everything is covered.
**: No Euler's method found.

**Comment by waciumawanjohi** [comment]
Glad to have your suggestions Dion!

Adding a course on numerical analysis would be a substantive change to the curriculum. The contributing guidelines for such changes are [here](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes). As noted, it is important to tie such proposals to curricular guidelines. Can you do so?

**Comment by DionGR** [comment]
> Glad to have your suggestions Dion!
> 
> Adding a course on numerical analysis would be a substantive change to the curriculum. The contributing guidelines for such changes are [here](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes). As noted, it is important to tie such proposals to curricular guidelines. Can you do so?

Yes, whenever I find time I'll try to prepare something.

**Comment by MattRieke** [comment]
Where do you recommend this course be added Core Math, Advanced Math, Extras/Courses. or somewhere else?

**Comment by r0hitm** [comment]
I suggest core math

**Comment by seunyemo** [comment]
Please I'm having issues logging in using GitHub. I await your quick
response as it is delaying my studying process. Thank you.

**Comment by DionGR** [comment]
> Where do you recommend this course be added Core Math, Advanced Math, Extras/Courses. or somewhere else?

Numerical Analysis requires some Linear Algebra, therefore I believe we are forced to have it under Advanced Math.

**Comment by DionGR** [comment]
> Glad to have your suggestions Dion!
> 
> Adding a course on numerical analysis would be a substantive change to the curriculum. The contributing guidelines for such changes are [here](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes). As noted, it is important to tie such proposals to curricular guidelines. Can you do so?

I did a little digging, and this is the table I came up with. I will add it to the main post aswell.


### **Numerical Analysis**
_**Elective Course**_

_Prerequisites:_ Math for Computer Science & (optional) Linear Algebra (helpful, not mandatory)


|       CS2013 Requirements         |HSE University                         |MIT  18.330 | MIT 18.335J |
|----------------|---------|-----------------------------|--------|
|**Error, stability, convergence, including truncation and round-off**|✔|✔| ✔ |
|**Function approximation including Taylor’s series, interpolation, extrapolation, and regression**            |  ✔* |✔| ✔* |
|**Numerical differentiation and integration (Simpson’s Rule, explicit and implicit methods)**        |✔|✔|✔ |
|**Differential equations (Euler’s Method, finite differences)**         |✔|✔| ✔**|

*: Uncertain whether everything is covered.
**: No Euler's method found.

**Comment by waciumawanjohi** [comment]
Apologies for my slow response. Numerical Analysis can be found in CS2013. But that is as an elective course, not as part of the core undergraduate curriculum. I wouldn't support its inclusion in the curriculum as it is today.

Something that would change my judgement would be if it were added as part of an Advanced [Computational Science](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=71) block of courses.

**Comment by waciumawanjohi** [comment]
I wrote a quick post that I didn't think this was a good fit for the curriculum, but after reading everything here again, I've changed my mind. This is a good case.

You point out that there are three different offerings. The 18.330 course seems very sparse to me. I do not think there is sufficient material for students to study. I am curious about your and others judgement comparing the [HSE course](https://www.coursera.org/learn/intro-to-numerical-analysis#instructors) to the [OCW 18.335J course](https://ocw.mit.edu/courses/mathematics/18-335j-introduction-to-numerical-methods-spring-2019/).

**Comment by DionGR** [comment]
> I wrote a quick post that I didn't think this was a good fit for the curriculum, but after reading everything here again, I've changed my mind. This is a good case.
> 
> You point out that there are three different offerings. The 18.330 course seems very sparse to me. I do not think there is sufficient material for students to study. I am curious about your and others judgement comparing the [HSE course](https://www.coursera.org/learn/intro-to-numerical-analysis#instructors) to the [OCW 18.335J course](https://ocw.mit.edu/courses/mathematics/18-335j-introduction-to-numerical-methods-spring-2019/).

18.330 is the tightest match with CS2013. It might look lackluster, but it is a great for an Introduction to Numerical Analysis for a Computer Scientist. Same goes for HSE. I would recommend these for the Base Topics.

OCW 18.335J is a large course and it would be better suited for Advanced Topics, as it covers a ton of things that are definitely optional and might be of interest to people who are trying to go in-depth.

That's my personal insight on these courses.

**Comment by waciumawanjohi** [comment]
I would approve a PR to add the HSE course today, as there are a hundreds of high course reviews. Would you like to write that up?

**Comment by DionGR** [comment]
> I would approve a PR to add the HSE course today, as there are a hundreds of high course reviews. Would you like to write that up?

Will do.

**Comment by DionGR** [comment]
Also perhaps mention OCW 18.335J as an alternative to that?

**Comment by waciumawanjohi** [comment]
> Also perhaps mention OCW 18.335J as an alternative to that?

I have no objections to that.

**Comment by DionGR** [comment]
> > Also perhaps mention OCW 18.335J as an alternative to that?
> 
> I have no objections to that.

Opened the necessary pull request.

Thanks for taking this suggestion into consideration.

Closed.
