### ISSUE TITLE
RFC:  Software Engineering: Introduction course on edX

### ISSUE THREAD

**Issue by zico-son** [ossu/computer-science#969]
**Problem:**
Software Engineering: Introduction course on edX it's access expired on Sep 23, 2019.  Can you change it?

**Comment by waciumawanjohi** [comment]
[Software Engineering: Introduction](https://www.edx.org/course/software-engineering-introduction) is currently being offered. You can check by opening that link in an incognito browser window. I suspect that you have previously registered for the course and your personal access has expired.

**Comment by zico-son** [comment]
No, I've just enrolled in it yesterday
![Screenshot 2021-11-05 184618](https://user-images.githubusercontent.com/77364329/140547642-d19ea6db-58ae-4957-bb4b-03e8b7fa96c7.png)
