### ISSUE TITLE
RFC: Addition of Mobile Development in Final Project

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/computer-science#973]
**Problem:**
Curriculum lacks mobile development as an elective as stated in Platform Based Development of CS2013 (page-143 to 144)

**Duration:**
10 December 2021

**Background:**
OSSU promises the equivalent of an undergraduate degree in Computer Science. In order to evaluate our recommended courses, we use the Curriculum Guidelines for Undergraduate Programs in Computer Science (CS2013). CS2013 specifies a number of knowledge areas a curriculum must cover, one of which is platform based development (pbd).

What CS2013 says:
Platform-based development is concerned with the design and development of software applications that reside on specific software platforms. In contrast to general purpose programming, platform-based development takes into account platform-specific constraints. For instance web programming, multimedia development, mobile computing, app development, and robotics are examples of relevant platforms that provide specific services/APIs/hardware that constrain development.

While we have courses for Industrial Platform(Modern Robotics Specialisation), Web Platform(Full Stack 2021), Game Platform(Game Design and Development with Unity)

We don't have any for mobile development.  While mobile development can be divided into two parts Android Development and iOS Development.

Let us see what CS2013 says about app development (reference to page 143-144)

PBD/Mobile Platforms
[Elective]
Topics:
• Mobile programming languages
• Challenges with mobility and wireless communication
• Location-aware applications
• Performance / power tradeoffs
• Mobile platform constraints
• Emerging technologies

Learning Outcomes:
1. Design and implement a mobile application for a given mobile platform. [Usage]
2. Discuss the constraints that mobile platforms put on developers. [Familiarity]
3. Discuss the performance vs. power tradeoff. [Familiarity]
4. Compare and contrast mobile programming with general purpose programming. [Assessment]

**Proposal:**
Include these two courses in final project
[Android App Development Specialisation](https://www.coursera.org/specializations/android-app-development?)
[iOS Application Development](https://www.coursera.org/specializations/swift-5-ios-app-developer)

**Comment by waciumawanjohi** [comment]
Two thoughts:
1. It is true that Mobile Platforms is an elective option outlined in the CS2013. At the same time, there are many electives which are not covered in the final project options. I worry about the final project list becoming (or being) a legacy list of courses that is not very strategic in its choices.
2. The RFC lays out a rationale for adding _some_ mobile development courses, but no justification for adding _these_ specific courses. (As opposed to other courses on mobile development)

**Comment by aayushsinha0706** [comment]
> Two thoughts:
> 
> 1. It is true that Mobile Platforms is an elective option outlined in the CS2013. At the same time, there are many electives which are not covered in the final project options. I worry about the final project list becoming (or being) a legacy list of courses that is not very strategic in its choices.

The solution of first thought can be resolve by adding these courses in extra/courses as Extra Courses for Final Project.

> 2. The RFC lays out a rationale for adding _some_ mobile development courses, but no justification for adding _these_ specific courses. (As opposed to other courses on mobile development)

Now why these courses are selected for mobile development

1. Let us first discuss for android development specialisation. Its first course is "Java for android" it covers topic "mobile development programming language."

2. While third course covers topics like Challenges with mobility and wireless communication.

3. The 4th course and 5th course (Capstone Project) provides a learning outcome of designing and implementing a mobile application for a given mobile platform.

Let us talk about iOS specialisation 

1.  The first course introduces the student to Swift5 programming which covers topic Mobile programming languages

2. The second course helps you to build an iOS application using swift which covers learning outcome designing and implementing a mobile application for a given mobile platform.

3.  The third course introduces to iOS and Networking which covers topic challenges with mobility and wireless communication.

4. The fourth course introduces to basics of monetization on iOS which also cover topics Mobile platform constraints and learning outcome "Discuss the constraints that mobile platforms put on developers. "

**Comment by waciumawanjohi** [comment]
>  justification for adding _these_ specific courses.

I find the most helpful justification for learning resources are comparisons of external reviews, followed by comparisons of ratings, followed by direct comparison with other courses. I appreciate the overview of the material in the course, but it doesn't help me understand if these courses are better than other available options.

**Comment by waciumawanjohi** [comment]
> The solution of first thought can be resolve by adding these courses in extra/courses as Extra Courses for Final Project.

Perhaps. I think I will simply remain dissatisfied with the current structure until there's impetus and buy-in to change it. As it is, you've made a case for adding mobile dev, it fits the current structure. I'd like to hear more about whether these are the right courses to recommend for mobile dev. Once there's solid justification for the course choice, I see no reason not to support this RFC.

**Comment by waciumawanjohi** [comment]
Closing this issue as there has not been an update to this RFC in 2 months. As mentioned above, the proposer has justified the addition of _some_ Mobile Development set of courses. In addition there should be justification for a particular set (justification that the courses proposed will be better for learners than other possible mobile development courses). Contributors should feel free to reopen the issue with such justification.
