### ISSUE TITLE
RFC: Dated link to course "Operating Systems: Three Easy Pieces"

### ISSUE THREAD

**Issue by jcob-sikorski** [ossu/computer-science#979]
- Current link points to site dated back to 2018 which is unreadable and confusing.

More user friendly 2020 version of site exists: [https://pages.cs.wisc.edu/~shivaram/cs537-sp20/](url)

**Comment by waciumawanjohi** [comment]
While the 2020 course page is more readable, lacking a link to lectures is a significant drawback.

**Comment by waciumawanjohi** [comment]
You may be interested in the conversation in #926 and #976.

**Comment by waciumawanjohi** [comment]
Closing this issue as there has not been additional discussion.
