### ISSUE TITLE
Login with Github functionality not working on website

### ISSUE THREAD

**Issue by Raeskaa** [ossu/computer-science#991]
**Problem**
![image](https://user-images.githubusercontent.com/84667136/151675456-be9130f4-abf0-4e86-91b6-81bba0ed5768.png)
As I try to log in with my Github account, for some reason I can't. It just shows this
![image](https://user-images.githubusercontent.com/84667136/151675913-cc4bf9c3-4f2a-4de3-8bce-9fa709b726ad.png)

**Solution:** 
- tutorialspoint.com/firebase/firebase_github_authentication.htm
- ( I'll solve this issue )

**Comment by spamegg1** [comment]
Please read: https://github.com/ossu/computer-science/blob/master/FAQ.md#why-is-the-firebase-ossu-app-different-or-broken

**Comment by Raeskaa** [comment]
@spamegg1 
Can we remake the app? 
We can add more features like a progress board and badges for people completing respective courses which will help them track their progress and a community discussion page for doubts and stuff?

**Comment by spamegg1** [comment]
@Raeskaa Come to Discord: https://discord.gg/wuytwK5s9h where we have most of that stuff in one place.

**Comment by waciumawanjohi** [comment]
Closing as the question has been answered.
