### ISSUE TITLE
Adding a course about "Information Retrieval"

### ISSUE THREAD

**Issue by hamzakat** [ossu/computer-science#993]
Hey everyone. I am a junior BSc student, and currently, I am taking a course about Information Retrieval. The course relies on the famous Stanford textbook, which is however available for free. 
By looking at the curriculum here, I found no course related to this topic. I believe it must be listed under the "Core Applications" section because it is considered an essential application of the data structure and database theories. This topic by the way seems to be underrated, but still crucial.

This is the homepage of the textbook and it includes two other links for published slides and assignments from two different universities.
[https://nlp.stanford.edu/IR-book/information-retrieval-book.html](https://nlp.stanford.edu/IR-book/information-retrieval-book.html)

I wonder if it can be listed in the curriculum.

**Comment by waciumawanjohi** [comment]
Hi Hamzakat,
Glad to hear that you are taking a course you find fascinating and valuable. And to hear of free high quality materials.

As our [contributing guide](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md#substantive-changes) points out, successful proposals to change the curriculum will refer to our curricular guidelines. You can read an example of such a successful proposal [here](https://github.com/ossu/computer-science/issues/970) (and find many other such RFCs in closed issues).

I'm closing this issue for the moment, but feel free to reopen it with additional information.
